PHASE_5_META = {
    "number": 5,
    "name": "Capstone & Future Pathways",
    "essential_question": "How do I turn a semester of help desk experience into a professional portfolio, a polished capstone project, and a clear next step toward a tech career?",
    "overview": "Phase 5 closes out the semester by asking students to prove what they have learned instead of just practicing it. Students build a knowledge base article or video tutorial for a real recurring school tech issue, assemble a ticket portfolio that shows their growth, and prepare for life after this class with a resume, a LinkedIn profile, and a mock interview with District IT. The unit ends with a real presentation and a semester-long reflection on how far each student climbed the Apprentice-to-Professional ladder.",
    "vocabulary_bank": [
        {"word": "Knowledge Base Article", "definition": "A written how-to guide that helps someone solve a common problem on their own, without needing to submit a ticket.",
         "syllables": "NAH-lij BAYSS AR-tik-uhl",
         "morphology": "Old English cnawan (to know) + -ledge; Greek basis (a step, foundation); Latin articulus (a small joint or distinct part) — literally, a distinct piece of writing forming part of a base of known information."},
        {"word": "Portfolio", "definition": "An organized collection of your best work from the semester, used as evidence of your skills and growth.",
         "syllables": "por-FOH-lee-oh",
         "morphology": "Italian portafoglio, from Latin portare (to carry) + folium (a leaf or sheet of paper) — literally, something that carries loose sheets."},
        {"word": "Capstone", "definition": "The final project of the course that shows everything you learned, usually a knowledge base article or a video tutorial.",
         "syllables": "KAP-stohn",
         "morphology": "Latin caput (head, top) + Old English stan (stone) — literally, the finishing stone placed on top of a structure to complete it."},
        {"word": "LinkedIn Profile", "definition": "A professional online profile that lists your experience, skills, and certifications for employers and colleges to see.",
         "syllables": "LINGKT-in PROH-fyle",
         "morphology": "'Linked' + 'In' (a branded compound meaning connected within a professional network) + Latin pro- (forward) + filare (to spin a thread) — literally, an outline drawn forward to represent you."},
        {"word": "Mock Interview", "definition": "A practice job interview, run like the real thing, so you can build confidence and get feedback before an interview that counts.",
         "syllables": "MOK IN-tur-vyoo",
         "morphology": "Old French mocquer (to mock, imitate) + Old French entrevoir (entre- 'between' + voir 'to see') — literally, a practiced 'seeing between' two people."},
    ],
    "unit_assessment": {
        "title": "Unit 5 Assessment: Capstone & Future Pathways",
        "questions": [
            {"type": "multiple_choice", "q": "Which of the following best describes a knowledge base article?", "choices": ["A. A private note only technicians can read", "B. A step-by-step guide that helps a user solve a common problem without submitting a ticket", "C. A list of every ticket ever submitted to the help desk", "D. A resume written for an IT job"], "answer": "B"},
            {"type": "multiple_choice", "q": "What percentage of the final course grade comes from Capstone & Portfolio?", "choices": ["A. 35%", "B. 20%", "C. 15%", "D. 10%"], "answer": "D"},
            {"type": "multiple_choice", "q": "A strong resume bullet point turns a ticket into what?", "choices": ["A. A joke about the user", "B. An action verb, the task, and the result", "C. A list of every tool used", "D. A copy of the original ticket text"], "answer": "B"},
            {"type": "multiple_choice", "q": "In a STAR-format interview answer, what does the 'R' stand for?", "choices": ["A. Reason", "B. Repair", "C. Result", "D. Reflection"], "answer": "C"},
            {"type": "multiple_choice", "q": "Put the performance levels in order from the ladder used all semester.", "choices": ["A. Technician, Apprentice, Professional, Lead Tech", "B. Apprentice, Technician, Lead Tech, Professional", "C. Lead Tech, Apprentice, Technician, Professional", "D. Professional, Lead Tech, Technician, Apprentice"], "answer": "B"},
            {"type": "multiple_choice", "q": "Why should a student proofread their LinkedIn profile before making it public?", "choices": ["A. Because employers and recruiters may actually see it", "B. LinkedIn deletes unprofessional profiles automatically", "C. It has no effect on how you're perceived", "D. Only college professors read LinkedIn"], "answer": "A"},
            {"type": "short_answer", "q": "Explain the difference between a ticket portfolio and a capstone project.", "sample_answer": "A ticket portfolio is a curated collection of real tickets and repair logs that shows the range of your skills across the semester. The capstone is a single, finished project (a knowledge base article or video tutorial) built to teach someone else how to solve one specific, common problem."},
            {"type": "short_answer", "q": "Describe one thing a technician should do to prepare for a mock interview with District IT.", "sample_answer": "They should review their ticket portfolio for specific examples, practice STAR-format answers to common questions like 'tell me about a hard ticket you solved,' and rehearse professional behaviors like eye contact and a firm handshake."},
            {"type": "short_answer", "q": "Using the four performance levels (Apprentice, Technician, Lead Tech, Professional), describe how a student might show growth in their portfolio.", "sample_answer": "A student could include early tickets where they were shadowing and logging intake, then later tickets where they handled repairs solo, and finally a ticket where they helped train or supervise someone else, showing a climb up the tiers."},
            {"type": "short_answer", "q": "What is the purpose of the one-page writeup on the hardest ticket of the semester?", "sample_answer": "It asks students to reflect honestly on a real challenge, what made it difficult, how they solved it (or got help), and what they learned, turning a hard moment into evidence of growth and problem-solving."},
        ],
    },
    "days": [73, 82],
}

PHASE_5_LESSONS = [
    {
        "day": 73,
        "unit": 5,
        "lesson_in_unit": 1,
        "title": "Capstone Kickoff: Choosing Your Knowledge Base Topic",
        "objectives": [
            "I can explain the purpose of the capstone project and how it's graded.",
            "I can choose a common school tech issue to document based on real ticket history.",
            "I can describe what a finished knowledge base article or video tutorial looks like.",
        ],
        "vocab": [
            {"word": "Capstone", "definition": "The final project of the course that shows everything you learned, usually a knowledge base article or a video tutorial.",
             "example": "Jordan's capstone will be a knowledge base article on fixing a Chromebook that won't charge.",
             "syllables": "KAP-stohn",
             "morphology": "Latin caput (head, top) + Old English stan (stone) — literally, the finishing stone placed on top of a structure to complete it."},
            {"word": "Knowledge Base Article", "definition": "A written how-to guide that helps someone solve a common problem on their own, without needing to submit a ticket.",
             "example": "A good knowledge base article means five fewer tickets about the same Wi-Fi login problem.",
             "syllables": "NAH-lij BAYSS AR-tik-uhl",
             "morphology": "Old English cnawan (to know) + -ledge; Greek basis (a step, foundation); Latin articulus (a small joint or distinct part) — literally, a distinct piece of writing forming part of a base of known information."},
        ],
        "warm_up": "Look back through your ticket log or the class ticket system. What's one issue you've helped fix more than once this semester?",
        "mini_lesson": [
            {"heading": "What Is the Capstone?", "body": "The capstone is your final, culminating project for the course. It's worth 10% of your grade under Capstone & Portfolio, and it's meant to prove what you've learned all semester by teaching someone else. You'll pick a common school tech issue and build either a knowledge base article or a short video tutorial that walks a beginner through solving it."},
            {"heading": "What Makes a Good Knowledge Base Article (or Video)?", "body": "It has a clear title that names the exact problem. It's written or filmed for someone who has never done this before, so no unexplained jargon. Steps are numbered, one action at a time, with a screenshot or clear shot showing what to look for. Good ones also say what to do if the steps don't fix it."},
            {"heading": "Picking a Topic That Matters", "body": "The best topics are common enough that many people hit them, but specific enough to explain clearly in one article or a few-minute video. Think about tickets you've seen more than once: a Chromebook that won't charge, a forgotten password, a printer that won't connect, a projector with no signal. Avoid anything so rare or so complex it can't be explained cleanly."},
        ],
        "activity": {
            "title": "Ticket Mining",
            "instructions": "Have students pull up their personal ticket log or a class list of anonymized recurring tickets from the semester. Ask them to shortlist three candidate capstone topics, then write one sentence for each explaining who would benefit from a guide on that topic. Circulate and help students narrow to their final pick before the period ends.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "Which Topic Actually Helps?",
            "scenario": "A student pulls three candidate capstone topics from the class ticket system's semester history: Wi-Fi login issues (22 tickets this semester, always the same few steps), cracked screen protectors (3 tickets, mostly cosmetic), and one obscure BIOS setting a single teacher's laptop needed changed (1 ticket, complex and device-specific). The student has access to a practice Chromebook, a spare laptop for testing, and about a week to research, outline, and draft.",
            "task": "Using the ticket frequency numbers and the 'common enough, specific enough' criteria from today's lesson, students rank the three candidate topics from strongest to weakest capstone choice and justify the top pick in 2-3 sentences.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What percentage of your final grade is the Capstone & Portfolio category?", "choices": ["A. 35%", "B. 20%", "C. 15%", "D. 10%"], "answer": "D"},
                {"type": "multiple_choice", "q": "A good capstone topic should be...", "choices": ["A. As rare and complex as possible", "B. Common enough to help many people, specific enough to explain clearly", "C. A secret only technicians should know", "D. Copied directly from an official manual"], "answer": "B"},
                {"type": "short_answer", "q": "Name one tech issue from this semester that would make a strong knowledge base topic, and explain why.", "sample_answer": "A guide on Chromebooks that won't charge would work well because it comes up often, has a clear set of steps to check, and would save the help desk repeat tickets."},
            ],
        },
        "exit_ticket": {"prompt": "What topic did you pick for your capstone, and why is it a good fit for a knowledge base article or video tutorial?"},
        "slide_bullets": [
            "Capstone = your final project, 10% of your grade (Capstone & Portfolio)",
            "Choose: knowledge base article OR video tutorial",
            "Pick a common, recurring school tech issue",
            "Written or filmed for a total beginner",
            "Today: mine your ticket log for a topic",
        ],
        "academic_vocab": {
            "word": "Evaluate",
            "definition": "To judge the quality, value, or accuracy of something using evidence.",
            "syllables": "ee-VAL-yoo-ayt",
            "morphology": "Latin e- (out) + valere (to be strong, to be worth) + -ate (a verb-forming suffix)",
            "example": "Students had to evaluate three candidate ticket topics before choosing the strongest one for their capstone.",
        },
    },
    {
        "day": 74,
        "unit": 5,
        "lesson_in_unit": 2,
        "title": "Researching & Outlining Your Capstone",
        "objectives": [
            "I can research a tech issue thoroughly enough to explain it to a beginner.",
            "I can build a step-by-step outline before writing a full draft.",
            "I can decide whether an article or a video format fits my topic best.",
        ],
        "vocab": [
            {"word": "Knowledge Base Article", "definition": "A written how-to guide that helps someone solve a common problem on their own, without needing to submit a ticket.",
             "example": "Before writing the knowledge base article, Jordan tested every step on a spare Chromebook first.",
             "syllables": "NAH-lij BAYSS AR-tik-uhl",
             "morphology": "Old English cnawan (to know) + -ledge; Greek basis (a step, foundation); Latin articulus (a small joint or distinct part) — literally, a distinct piece of writing forming part of a base of known information."},
        ],
        "warm_up": "Think of a time you learned something from a YouTube tutorial or help article. What made it easy (or hard) to follow?",
        "mini_lesson": [
            {"heading": "Research Like a Tech", "body": "Don't write from memory alone. Pull up official resources the way you would on a real ticket, and actually test every step yourself on a practice device before you claim it works. If you skip a step or get details wrong, you'll confuse the exact beginner you're trying to help."},
            {"heading": "Outlining Before Writing", "body": "A messy first draft usually means there was no outline. List every step in order, one action per line, and note where a screenshot or camera shot needs to go. If a step depends on something happening first (like the device being powered off), say so."},
            {"heading": "Article or Video?", "body": "Choose the format that fits the problem. Physical repairs or anything hands-on (like replacing a part) are often easier to follow as video, since viewers can watch exactly where your hands go. Software walkthroughs with menus and settings are often clearer as an article with screenshots, since readers can pause and match the picture to their own screen."},
        ],
        "activity": {
            "title": "Outline Draft",
            "instructions": "Have students draft a bullet-point outline of every step for their chosen topic, in order, noting where a screenshot or shot goes. Pair students up and have each partner try to literally follow the other's outline step by step, flagging anything missing or unclear with a sticky note or comment.",
        },
        "application": {
            "type": "case_study",
            "title": "The Outline That Skipped a Step",
            "scenario": "A student's draft outline for a knowledge base article titled 'How to Reset Your School Wi-Fi Password' reads: Step 1, go to the password reset page and click 'Forgot Password.' Step 2, check your email for a reset link. It jumps straight from clicking the button to checking email, without ever mentioning that the reset email is sent to the specific school email address on file, which may not be the address a student expects to check first.",
            "task": "Students identify the missing step in the outline, explain exactly what a beginner following it literally would get stuck on, and rewrite the outline inserting the missing step in the correct place.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Why should you test your own steps before writing them up?", "choices": ["A. To make the guide longer", "B. To make sure the steps actually work and nothing important is missing", "C. It isn't necessary if you already know the fix", "D. So you can skip writing an outline"], "answer": "B"},
                {"type": "multiple_choice", "q": "A hands-on physical repair is often best explained as...", "choices": ["A. A single sentence", "B. A video, so viewers can see exactly where your hands go", "C. A list with no order", "D. An article with no images"], "answer": "B"},
                {"type": "short_answer", "q": "Why is outlining before writing helpful, especially for a technical topic?", "sample_answer": "An outline forces you to put every step in the right order and catch missing steps before you invest time writing full sentences or filming, which saves rework later."},
            ],
        },
        "exit_ticket": {"prompt": "What's the trickiest step in your outline, and how will you make sure a beginner understands it?"},
        "slide_bullets": [
            "Test every step yourself before you write it up",
            "Outline first: one action per step, in order",
            "Note where a screenshot or camera shot goes",
            "Article vs. video: match format to the problem",
            "Today: draft an outline, then trade for a partner test",
        ],
        "academic_vocab": {
            "word": "Organize",
            "definition": "To arrange things in a clear, logical order or structure.",
            "syllables": "OR-guh-nyze",
            "morphology": "Greek organon (a tool, instrument) + -ize (a suffix meaning 'to make or do')",
            "example": "A clear outline helped students organize every step of their capstone in the right order before writing a full draft.",
        },
    },
    {
        "day": 75,
        "unit": 5,
        "lesson_in_unit": 3,
        "title": "Drafting the Knowledge Base Article or Tutorial Script",
        "objectives": [
            "I can write clear, plain-language instructions for a technical process.",
            "I can plan visuals that support and clarify my written or spoken steps.",
            "I can apply code-switching skills to write for a non-technical audience.",
        ],
        "vocab": [
            {"word": "Knowledge Base Article", "definition": "A written how-to guide that helps someone solve a common problem on their own, without needing to submit a ticket.",
             "example": "The final knowledge base article used short sentences and no unexplained jargon.",
             "syllables": "NAH-lij BAYSS AR-tik-uhl",
             "morphology": "Old English cnawan (to know) + -ledge; Greek basis (a step, foundation); Latin articulus (a small joint or distinct part) — literally, a distinct piece of writing forming part of a base of known information."},
        ],
        "warm_up": "Reread one sentence you wrote in a past ticket note. Would a total beginner understand it? Rewrite it if not.",
        "mini_lesson": [
            {"heading": "Plain Language Rules", "body": "This is the same code-switching skill from earlier this semester, applied to writing instead of talking. Use short sentences. If you have to use a technical term, define it the first time. Say exactly what to click, press, or unplug, not vague phrases like 'go into settings somewhere.'"},
            {"heading": "Show, Don't Just Tell", "body": "Visuals carry weight a paragraph can't. For an article, screenshots with an arrow or circle around the exact button save readers from hunting. For a video, plan close-up shots of small parts or tiny icons, and make sure your framing and lighting actually show what you're doing."},
            {"heading": "Structure That Works", "body": "Start with a title that names the exact problem. State who the guide is for. Number your steps. End with a short troubleshooting note: what to try, or who to ask, if the steps don't fix it. That last part is what separates a real knowledge base article from a rushed one."},
        ],
        "activity": {
            "title": "Draft Sprint",
            "instructions": "Run a 20-minute silent drafting sprint. Students write the full body of their article or storyboard and record the first three steps of their video, working straight from yesterday's outline. No editing yet, just getting the content down.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "Rewrite It for a Beginner",
            "scenario": "A rough capstone draft includes these two sentences pulled straight from a technical manual: 'Navigate to the network configuration pane and toggle the SSID broadcast setting,' and 'Initiate a factory reset by depressing the recessed button for a minimum of ten seconds.' Both are accurate, but neither would mean anything to a beginner who has never opened a settings menu or seen a recessed button before.",
            "task": "Students rewrite each sentence in plain, beginner-friendly language, following today's rules: short sentences, any necessary term defined, and the exact physical action named (what to click, or exactly where to press and for how long).",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which instruction is written in the clearest plain language?", "choices": ["A. Navigate to the appropriate configuration pane", "B. Click the gear icon in the bottom-right corner", "C. Adjust your settings as needed", "D. Go into the system somewhere"], "answer": "B"},
                {"type": "multiple_choice", "q": "What should a knowledge base article include at the end?", "choices": ["A. Nothing, steps are enough", "B. A joke to keep it light", "C. A short troubleshooting note for when the steps don't work", "D. A list of every certification you're working on"], "answer": "C"},
                {"type": "short_answer", "q": "Why does plain language matter more in a capstone than in a note you'd write for another technician?", "sample_answer": "Your capstone audience is a beginner, not another technician, so it has to work without any inside knowledge, meaning every technical term needs to be defined or avoided."},
            ],
        },
        "exit_ticket": {"prompt": "Read the first sentence of your draft out loud. Would someone who's never touched a Chromebook understand it? If not, fix it now."},
        "slide_bullets": [
            "Plain language = code-switching applied to writing",
            "Define any term you must use",
            "Plan screenshots or shots before you write the step",
            "Structure: title, audience, numbered steps, troubleshooting note",
            "Today: 20-minute draft sprint, no editing yet",
        ],
        "academic_vocab": {
            "word": "Clarify",
            "definition": "To make something easier to understand by removing confusion.",
            "syllables": "KLAIR-uh-fy",
            "morphology": "Latin clarus (clear, bright) + -ficare (to make)",
            "example": "Rewriting a jargon-heavy sentence into plain language helped clarify the instructions for a total beginner.",
        },
    },
    {
        "day": 76,
        "unit": 5,
        "lesson_in_unit": 4,
        "title": "Peer Review & Revision",
        "objectives": [
            "I can give and receive specific, actionable feedback on a technical draft.",
            "I can test whether written instructions actually work by following them literally.",
            "I can revise my capstone draft based on real feedback.",
        ],
        "vocab": [
            {"word": "Portfolio", "definition": "An organized collection of your best work from the semester, used as evidence of your skills and growth.",
             "example": "Jordan's revised draft will later become one of the strongest pieces in their portfolio.",
             "syllables": "por-FOH-lee-oh",
             "morphology": "Italian portafoglio, from Latin portare (to carry) + folium (a leaf or sheet of paper) — literally, something that carries loose sheets."},
        ],
        "warm_up": "What's one piece of feedback you got this semester (on a ticket, a repair, anything) that actually made your work better?",
        "mini_lesson": [
            {"heading": "The Follow-It-Literally Test", "body": "The fastest way to find gaps in your instructions is to have someone follow them exactly as written, with no help from you. If they get stuck, that's not their fault, it means a step is missing or unclear. This is the same thing Sam does when he reads a jargon-filled ticket note."},
            {"heading": "Giving Useful Feedback", "body": "Good feedback is specific, kind, and actionable, the same professionalism standard you've used all semester on Live Desk. Instead of 'this is confusing,' say exactly where you got stuck and what you needed to know. Instead of only pointing out problems, say what's working too."},
            {"heading": "Revising for Clarity", "body": "Revision means using the feedback, not just reading it. Cut jargon your partner flagged. Reorder steps that confused them. Add anything they had to guess. A capstone that survives a real test run is far stronger than one that only looked finished to its own author."},
        ],
        "activity": {
            "title": "Peer Test-Drive",
            "instructions": "Have students swap drafts (or storyboards) with a partner. The partner follows the steps literally, with zero help from the author, and marks every point of confusion with a sticky note or comment. Authors then spend the rest of the period revising based on the exact friction points their partner hit.",
        },
        "application": {
            "type": "case_study",
            "title": "Stuck on Step 4",
            "scenario": "A peer tester follows a classmate's video-tutorial draft exactly as filmed. At step 4, the narration says 'plug it into the port,' but the device on screen has three visually similar ports next to each other, and nothing in the narration or the shot makes clear which one is correct. The tester pauses the video, rewinds twice, and eventually guesses wrong, plugging into the wrong port entirely.",
            "task": "Students write the specific, actionable feedback the tester should give the author (not just 'this was confusing'), and describe the one concrete revision the author should make to step 4 so a future viewer wouldn't get stuck the same way.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "If someone gets stuck following your instructions exactly as written, that usually means...", "choices": ["A. They didn't try hard enough", "B. A step is likely missing or unclear", "C. The topic was a bad choice", "D. Feedback isn't useful at this stage"], "answer": "B"},
                {"type": "multiple_choice", "q": "Which is an example of specific, actionable feedback?", "choices": ["A. This is confusing", "B. I got stuck on step 4 because I didn't know which icon was the gear icon", "C. It's fine I guess", "D. Just start over"], "answer": "B"},
                {"type": "short_answer", "q": "Why is the follow-it-literally test more useful than just reading your draft over yourself?", "sample_answer": "Authors already know what they meant, so they naturally fill in gaps in their head. A partner following the steps exactly as written has no hidden knowledge, so they expose real confusion the author can't see on their own."},
            ],
        },
        "exit_ticket": {"prompt": "What's one specific change you're making to your draft based on your partner's feedback today?"},
        "slide_bullets": [
            "Follow-it-literally test finds real gaps",
            "Feedback should be specific, kind, actionable",
            "Same professionalism standard as Live Desk",
            "Revise using the actual friction points, not guesses",
            "Today: swap, test-drive, revise",
        ],
        "academic_vocab": {
            "word": "Critique",
            "definition": "To carefully evaluate something's strengths and weaknesses and give specific feedback.",
            "syllables": "kri-TEEK",
            "morphology": "Greek kritikos (able to judge or discern), from krinein (to judge, decide)",
            "example": "Partners had to critique each other's drafts by pointing out exactly where the instructions broke down.",
        },
    },
    {
        "day": 77,
        "unit": 5,
        "lesson_in_unit": 5,
        "title": "Finalizing Your Capstone & Building Your Ticket Portfolio",
        "objectives": [
            "I can finalize a polished knowledge base article or video tutorial.",
            "I can select and organize evidence for my ticket portfolio.",
            "I can connect my capstone and portfolio to my growth across performance levels this semester.",
        ],
        "vocab": [
            {"word": "Portfolio", "definition": "An organized collection of your best work from the semester, used as evidence of your skills and growth.",
             "example": "Jordan's portfolio included tickets from their first week shadowing Sam all the way to solo repairs.",
             "syllables": "por-FOH-lee-oh",
             "morphology": "Italian portafoglio, from Latin portare (to carry) + folium (a leaf or sheet of paper) — literally, something that carries loose sheets."},
            {"word": "Capstone", "definition": "The final project of the course that shows everything you learned, usually a knowledge base article or a video tutorial.",
             "example": "By Friday, every student needs a finished capstone ready to present.",
             "syllables": "KAP-stohn",
             "morphology": "Latin caput (head, top) + Old English stan (stone) — literally, the finishing stone placed on top of a structure to complete it."},
        ],
        "warm_up": "Which ticket from this semester are you proudest of, and why?",
        "mini_lesson": [
            {"heading": "What Goes in Your Portfolio", "body": "Your portfolio is not every ticket you ever touched, it's your best evidence. Choose four to six pieces that show range: an early intake ticket, an escalation you handled well, a hands-on repair with a before-and-after, and something tied to certification prep. Include repair logs and short reflections, not just raw ticket text."},
            {"heading": "Capstone & Portfolio Is 10% of Your Grade", "body": "This category rewards a finished, polished capstone and a portfolio that's actually organized, not just a folder dump. Checklist: capstone is complete and tested, portfolio has 4-6 labeled pieces, each piece has a one-sentence caption explaining what it shows about you."},
            {"heading": "From Apprentice to Technician (and Beyond)", "body": "Your portfolio should tell the story of your climb up the performance ladder: Apprentice, Technician, Lead Tech, Professional. Pick evidence that shows where you started and where you are now, not just your favorite moments. Growth, not perfection, is what this category is really grading."},
        ],
        "activity": {
            "title": "Portfolio Assembly",
            "instructions": "Have students select their four to six strongest tickets or repair logs from the semester and organize them into a folder or binder in the class ticket system or portfolio template. For each piece, students write a one-sentence caption explaining what it shows about their growth as a technician.",
        },
        "application": {
            "type": "simulation",
            "title": "Six Slots, Ten Candidates",
            "scenario": "A student has ten possible portfolio pieces from the semester: a Week 1 intake ticket where they shadowed Sam and logged everything wrong; a Phase 2 Chromebook screen replacement with before-and-after photos; a Phase 3 networking ticket they solved alone; a Phase 3 escalation they correctly sent to District IT; a Core 1 practice exam score sheet; a reflection on a permission-level mistake from Phase 4; a signal flow repair under time pressure; a solo printer ticket; a peer-feedback form from capstone drafting; and a note from a teacher thanking them for a fix. The portfolio template only has room for four to six labeled pieces.",
            "task": "Students select 4-6 of the ten pieces that together best show a full range of skills and real growth across the performance ladder (not just the strongest or easiest pieces), and justify in one sentence why they left one specific piece out.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "A strong ticket portfolio should include...", "choices": ["A. Every single ticket from the whole semester", "B. Four to six pieces that show range and growth", "C. Only your very first ticket", "D. Only tickets where nothing went wrong"], "answer": "B"},
                {"type": "multiple_choice", "q": "What does the Capstone & Portfolio grading category reward?", "choices": ["A. Speed only", "B. A finished, polished capstone and an organized portfolio", "C. The number of tickets submitted", "D. Attendance"], "answer": "B"},
                {"type": "short_answer", "q": "Why should a portfolio show a range of tickets, not just your favorite success?", "sample_answer": "A range of tickets, including early ones and harder ones, shows real growth over the semester rather than just cherry-picking a single good moment."},
            ],
        },
        "exit_ticket": {"prompt": "What's the strongest piece of evidence in your portfolio, and what does it prove about you as a technician?"},
        "slide_bullets": [
            "Portfolio = your best 4-6 pieces, not everything",
            "Include repair logs and short reflections too",
            "Capstone & Portfolio = 10% of your final grade",
            "Show growth: Apprentice to Technician to Lead Tech",
            "Today: assemble your portfolio and caption each piece",
        ],
        "academic_vocab": {
            "word": "Curate",
            "definition": "To thoughtfully select and organize the best items from a larger collection.",
            "syllables": "KYOOR-ayt",
            "morphology": "Latin curare (to take care of, look after)",
            "example": "Jordan had to curate just four to six tickets that best showed real growth across the semester.",
        },
    },
    {
        "day": 78,
        "unit": 5,
        "lesson_in_unit": 6,
        "title": "Building Your Resume for an IT Career",
        "objectives": [
            "I can translate help desk experience into resume-ready bullet points.",
            "I can identify which certifications and skills belong on an entry-level IT resume.",
            "I can format a resume that a hiring manager or district recruiter would take seriously.",
        ],
        "vocab": [
            {"word": "Portfolio", "definition": "An organized collection of your best work from the semester, used as evidence of your skills and growth.",
             "example": "Jordan pulled the strongest lines for their resume straight out of their portfolio.",
             "syllables": "por-FOH-lee-oh",
             "morphology": "Italian portafoglio, from Latin portare (to carry) + folium (a leaf or sheet of paper) — literally, something that carries loose sheets."},
        ],
        "warm_up": "If a District IT recruiter looked at your semester of work, what's one sentence you'd want on your resume?",
        "mini_lesson": [
            {"heading": "Resume Basics for a First Job", "body": "A resume needs clean formatting: your name and contact info at the top, a skills section, and an experience section, even if your 'job' is the Student Help Desk. Keep it to one page. No typos, no unprofessional email addresses, consistent formatting throughout."},
            {"heading": "Turning Tickets Into Bullet Points", "body": "Use the formula: action verb, plus the task, plus the result. Instead of 'fixed computers,' try 'Diagnosed and resolved over 40 Chromebook hardware issues, maintaining a fast turnaround time.' Specific numbers and outcomes make a bullet point believable and strong."},
            {"heading": "What to List", "body": "List certifications in progress or earned (CompTIA A+ Core 1, Google IT Support, CareerSafe, ACER Chromebook Repair), your current performance level, and your capstone project. These prove real, verifiable skill, not just a class you sat through."},
        ],
        "activity": {
            "title": "Resume Builder Workshop",
            "instructions": "Have students draft three to five resume bullet points pulled directly from their own ticket portfolio and repair logs, using the action verb plus task plus result formula. Partners then swap drafts to check for strong action verbs, real numbers where possible, and no unexplained jargon a recruiter wouldn't know.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "Turn the Ticket Into a Bullet",
            "scenario": "A raw ticket note in the class system reads: 'fixed printer thing for Ms. Alvarez, took a while, had to restart stuff twice.' It's accurate but vague, uses no numbers, and wouldn't mean anything to a recruiter skimming a stack of resumes.",
            "task": "Students rewrite the raw ticket note as a polished resume bullet point using the action-verb-plus-task-plus-result formula from today's lesson, inventing one reasonable, specific detail (like a time saved or a device count) where the original note is too vague to use as-is.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which resume bullet point is strongest?", "choices": ["A. Did computer stuff", "B. Was on the help desk", "C. Diagnosed and resolved over 40 Chromebook hardware issues with a fast turnaround", "D. Fixed things sometimes"], "answer": "C"},
                {"type": "multiple_choice", "q": "What formula makes a resume bullet point strong?", "choices": ["A. Adjective plus opinion", "B. Action verb plus task plus result", "C. A list of every tool you own", "D. A full paragraph of narrative"], "answer": "B"},
                {"type": "short_answer", "q": "Why should certifications in progress, like CompTIA A+ Core 1, be listed on a resume even before you pass the exam?", "sample_answer": "Listing certifications in progress shows a recruiter that you're actively building verifiable, industry-recognized skills, not just claiming general experience."},
            ],
        },
        "exit_ticket": {"prompt": "Share your strongest resume bullet point from today. What ticket or repair did it come from?"},
        "slide_bullets": [
            "Resume: one page, clean format, no typos",
            "Formula: action verb + task + result",
            "Pull real numbers and outcomes from your portfolio",
            "List certifications in progress, not just finished ones",
            "Today: draft and peer-check 3-5 bullet points",
        ],
        "academic_vocab": {
            "word": "Quantify",
            "definition": "To express something as a specific, measurable number or amount.",
            "syllables": "KWAHN-tuh-fy",
            "morphology": "Latin quantus (how much) + -ficare (to make)",
            "example": "Turning 'fixed computers' into 'resolved over 40 hardware issues' meant learning to quantify the work on a resume.",
        },
    },
    {
        "day": 79,
        "unit": 5,
        "lesson_in_unit": 7,
        "title": "LinkedIn Profile & Your Professional Online Presence",
        "objectives": [
            "I can set up a LinkedIn profile that reflects my help desk experience and certifications.",
            "I can write a professional summary that highlights my growth this semester.",
            "I can identify what to keep public versus private online as a job-seeking teen.",
        ],
        "vocab": [
            {"word": "LinkedIn Profile", "definition": "A professional online profile that lists your experience, skills, and certifications for employers and colleges to see.",
             "example": "Jordan's LinkedIn Profile listed the Student Help Desk as their first real work experience.",
             "syllables": "LINGKT-in PROH-fyle",
             "morphology": "'Linked' + 'In' (a branded compound meaning connected within a professional network) + Latin pro- (forward) + filare (to spin a thread) — literally, an outline drawn forward to represent you."},
        ],
        "warm_up": "What's one thing you'd want a future employer to know about you that isn't obvious from a resume alone?",
        "mini_lesson": [
            {"heading": "Why LinkedIn (Even at 16)", "body": "A LinkedIn Profile is often someone's first digital impression of you, before they ever meet you. It can connect you to internships, part-time jobs, and recommendations from people like Ms. Faraday or District IT staff who've actually seen your work."},
            {"heading": "Profile Essentials", "body": "A strong profile has a clear photo, a headline that says what you do (not just 'student'), an About summary in your own voice, an experience section listing the Student Help Desk role with real accomplishments, and a certifications section listing what you've earned or are working toward."},
            {"heading": "Privacy & Professionalism Online", "body": "Anything public should be something you'd be fine with a recruiter, teacher, or future boss seeing. This is the same code-switching skill from earlier this semester, applied to writing about yourself: professional tone, no jargon that assumes the reader already knows your world."},
        ],
        "activity": {
            "title": "Profile Draft",
            "instructions": "Using a provided worksheet or template (since not every student may create a live account today), have students draft their LinkedIn headline, About summary, and one experience bullet for the Student Help Desk role. Invite a few volunteers to share their headline or summary for quick class feedback.",
        },
        "application": {
            "type": "case_study",
            "title": "What Should Stay Off the Profile?",
            "scenario": "A student drafts a LinkedIn About summary with three sentences: an inside joke referencing a coworker's messy desk that only makes sense to people at the Help Desk, a complaint about a teacher who 'never explains anything right,' and a genuine accomplishment describing having fixed over 40 Chromebooks this semester with a fast turnaround.",
            "task": "Students identify which of the three sentences should be cut before the profile goes public, which should stay, and explain the professional-image reasoning behind each decision.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What should a LinkedIn headline say instead of just 'student'?", "choices": ["A. Nothing, headlines don't matter", "B. What you actually do, like a role or focus area", "C. A joke to stand out", "D. Your full class schedule"], "answer": "B"},
                {"type": "multiple_choice", "q": "A good rule for what to post publicly on a professional profile is...", "choices": ["A. Post anything, privacy doesn't matter online", "B. Only post what you'd be fine with a future employer seeing", "C. Never list any real experience", "D. Copy someone else's profile exactly"], "answer": "B"},
                {"type": "short_answer", "q": "Why does a LinkedIn Profile matter even for a student who isn't job hunting yet?", "sample_answer": "It builds a professional first impression online before anyone meets you in person, and it can connect you to recommendations, internships, or opportunities you wouldn't find otherwise."},
            ],
        },
        "exit_ticket": {"prompt": "What's one sentence from your About summary that best captures your growth this semester?"},
        "slide_bullets": [
            "LinkedIn Profile = your professional first impression online",
            "Headline should say what you do, not just 'student'",
            "List the Student Help Desk as real work experience",
            "Same code-switching skill, applied to writing about yourself",
            "Today: draft headline, About summary, one experience bullet",
        ],
        "academic_vocab": {
            "word": "Portray",
            "definition": "To present or represent something in a particular way.",
            "syllables": "por-TRAY",
            "morphology": "Latin pro- (forth) + trahere (to draw) — literally, to draw forth a likeness",
            "example": "Jordan's LinkedIn About summary had to portray a professional, focused version of their semester at the Help Desk.",
        },
    },
    {
        "day": 80,
        "unit": 5,
        "lesson_in_unit": 8,
        "title": "Mock Interview Prep with District IT",
        "objectives": [
            "I can prepare clear, honest answers to common interview questions using real examples from my semester.",
            "I can practice professional interview behavior, including greeting, eye contact, and follow-up questions.",
            "I can reflect on my growth from Apprentice toward Lead Tech using my own capstone story.",
        ],
        "vocab": [
            {"word": "Mock Interview", "definition": "A practice job interview, run like the real thing, so you can build confidence and get feedback before an interview that counts.",
             "example": "Jordan's Mock Interview with District IT felt nerve-wracking at first, but it was good practice for the real thing.",
             "syllables": "MOK IN-tur-vyoo",
             "morphology": "Old French mocquer (to mock, imitate) + Old French entrevoir (entre- 'between' + voir 'to see') — literally, a practiced 'seeing between' two people."},
        ],
        "warm_up": "What's one interview question you're nervous about being asked, and why?",
        "mini_lesson": [
            {"heading": "What District IT Interviewers Ask", "body": "Expect questions like: tell me about a time you fixed something difficult, how do you handle a frustrated user, and what's a mistake you learned from. These questions want real examples, not general statements, so know a few specific tickets you can talk through in detail."},
            {"heading": "STAR Answers", "body": "Structure answers with STAR: Situation, Task, Action, Result. Say what was going on, what you needed to do, exactly what you did, and what happened because of it. Pull real examples straight from your ticket portfolio so your answers are specific, not vague."},
            {"heading": "Interview Professionalism", "body": "This is Professionalism & Service in action: arrive on time, dress appropriately, greet with a handshake and eye contact, and send a short thank-you note afterward. These small things separate a memorable candidate from a forgettable one."},
        ],
        "activity": {
            "title": "Mock Interview Rounds",
            "instructions": "Pair students up (or rotate them through a visiting District IT staff member if one is available) and have them take turns as interviewer and candidate using provided question cards built around ticket experience and professionalism. After each round, have partners give each other one specific piece of feedback before switching roles.",
        },
        "application": {
            "type": "realistic_fiction",
            "title": "The Question Nobody Practiced",
            "scenario": "During a mock interview round, a District IT interviewer named Mr. Alvarado leans forward and asks a student named Dee a question none of the practice cards had covered: 'Tell me about a time a fix you tried didn't work the first time. What did you do?' Dee pauses, caught off guard, staring at the table for a second too long. Then Dee remembers a real ticket from Phase 3, a Wi-Fi problem where the first fix (restarting the router) didn't hold, and starts talking through what actually happened next: testing a second theory, escalating part of it, and eventually finding the real cause. Dee's voice steadies as the story goes on, landing on a clear result at the end.",
            "task": "Students write a 3-4 sentence STAR-format answer (Situation, Task, Action, Result) that Dee could give to this exact question, using a real or plausible invented ticket example where an initial fix failed before the real solution was found.",
        },
        "reading": {
            "type": "realistic_fiction",
            "title": "Ticket #82: Ready for Lead Tech",
            "body": "Jordan's laptop screen showed a single slide: a knowledge base article titled \"Chromebook Won't Charge? Try This First.\" Ms. Faraday sat at the front table with a legal pad. Sam leaned against the supply cabinet, arms crossed, the same way he had on Jordan's very first day.\n\n\"Whenever you're ready,\" Ms. Faraday said.\n\nJordan cleared their throat. \"Back in September, I got a ticket that said 'Chromebook broken, please fix ASAP.' I opened the case before I even asked what was wrong. Sam had to stop me and make me go back and actually talk to the kid first. Turned out the charger cable was just bent, not the battery.\"\n\nSam smirked but didn't interrupt.\n\n\"That ticket is the whole reason I wrote this,\" Jordan went on, clicking to the next slide. \"Five steps, no jargon, a photo of exactly what a bad charging port looks like versus a good one. If a kid or a teacher can fix it themselves in two minutes, that's two minutes Sam doesn't have to spend, and one less ticket for someone else to solve solo.\"\n\nMs. Faraday made a note. \"Walk me through how you tested it.\"\n\n\"I made three people who'd never seen it before follow my steps exactly, word for word, no help from me,\" Jordan said. \"Two of them got it on the first try. One got stuck on step three because I forgot to say which port to check. So I added a photo.\"\n\n\"That's exactly the follow-it-literally test,\" Ms. Faraday said, nodding. \"Good instinct.\"\n\nWhen Jordan finished, Ms. Faraday stepped out to grab the next presenter's laptop, leaving Sam and Jordan alone by the supply cabinet.\n\n\"Remember when you couldn't write a ticket note without three acronyms in it?\" Sam said.\n\n\"Don't remind me,\" Jordan said, laughing. \"You made me rewrite that thing four times.\"\n\n\"Three,\" Sam said. \"I'm generous like that.\" He picked up a spare screwdriver, spun it once, and set it back down. \"You know you started here basically afraid to touch a Chromebook without me standing over your shoulder. Now you just walked a room through a repair without flinching once, and you tested it better than half the guides I've seen from actual manufacturers.\"\n\nJordan didn't say anything right away. It was strange, hearing it out loud.\n\n\"I mean it,\" Sam said. \"Next semester, if you want it, you're basically ready to run this desk as Lead Tech. Not basically. Ready.\"\n\n\"What about you?\" Jordan asked.\n\nSam shrugged, already halfway to the door. \"District IT's been asking me to shadow a real network closet. Guess we're both moving up.\"",
            "questions": [
                "What mistake from Jordan's very first ticket does the capstone article directly try to prevent from happening to someone else?",
                "How did Jordan test whether their knowledge base article actually worked before presenting it?",
                "What does Ms. Faraday mean when she calls Jordan's testing method 'the follow-it-literally test,' and where has this reading series used that idea before?",
                "What specific evidence does Sam use to tell Jordan they're ready for Lead Tech, rather than just saying 'good job'?",
                "How does the ending, with both Jordan and Sam moving up, connect to the performance-level ladder used all semester?",
            ],
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What does the 'A' stand for in a STAR-format interview answer?", "choices": ["A. Attitude", "B. Action", "C. Advice", "D. Answer"], "answer": "B"},
                {"type": "multiple_choice", "q": "Why should you prepare specific ticket examples before a mock interview?", "choices": ["A. Interviewers only care about general statements", "B. Specific examples make your answers believable and memorable", "C. It's not necessary if you're confident", "D. Specific examples are only useful for resumes, not interviews"], "answer": "B"},
                {"type": "short_answer", "q": "Describe one professional behavior, besides your answers, that matters during an interview.", "sample_answer": "Things like arriving on time, dressing appropriately, making eye contact, offering a handshake, and sending a short thank-you note afterward all show professionalism beyond just what you say."},
            ],
        },
        "exit_ticket": {"prompt": "Using STAR, write a two-sentence draft answer to: 'Tell me about a difficult ticket you solved this semester.'"},
        "slide_bullets": [
            "Mock Interview = real practice before the interview that counts",
            "STAR: Situation, Task, Action, Result",
            "Use real examples from your ticket portfolio",
            "Professionalism & Service applies here too",
            "Reading: series finale, Ticket #82",
        ],
        "academic_vocab": {
            "word": "Validate",
            "definition": "To confirm that something is accurate, true, or well-supported.",
            "syllables": "VAL-uh-dayt",
            "morphology": "Latin validus (strong) + -ate (a verb-forming suffix)",
            "example": "Using a real ticket example helped validate Dee's claim of experience during the mock interview.",
        },
    },
    {
        "day": 81,
        "unit": 5,
        "lesson_in_unit": 9,
        "title": "Capstone Presentation Day",
        "objectives": [
            "I can present my capstone project clearly and confidently to an audience.",
            "I can answer follow-up questions about my technical process and decisions.",
            "I can give constructive, professional feedback to classmates presenting their capstones.",
        ],
        "vocab": [
            {"word": "Capstone", "definition": "The final project of the course that shows everything you learned, usually a knowledge base article or a video tutorial.",
             "example": "Every student in the class presented their capstone today, some to District IT staff in the room.",
             "syllables": "KAP-stohn",
             "morphology": "Latin caput (head, top) + Old English stan (stone) — literally, the finishing stone placed on top of a structure to complete it."},
            {"word": "Portfolio", "definition": "An organized collection of your best work from the semester, used as evidence of your skills and growth.",
             "example": "Jordan referenced two portfolio tickets while answering a question about their capstone.",
             "syllables": "por-FOH-lee-oh",
             "morphology": "Italian portafoglio, from Latin portare (to carry) + folium (a leaf or sheet of paper) — literally, something that carries loose sheets."},
        ],
        "warm_up": "What's the one sentence you want your audience to remember about your capstone?",
        "mini_lesson": [
            {"heading": "Presenting Like a Professional", "body": "This is Professionalism & Service on display. Make eye contact with your audience instead of reading straight off your slides. Speak at a steady pace. Be ready for questions, since a real presentation isn't just a monologue, it's a conversation."},
            {"heading": "What Your Audience Wants to Know", "body": "Cover the problem you chose to solve, your process for building and testing it, the result, and one thing you'd do differently with more time. Connecting your capstone back to your growth on the performance ladder makes the presentation land harder."},
            {"heading": "Handling Questions From District IT", "body": "If District IT staff are in the room, treat their questions like a real professional audience would ask them. It's completely fine to say 'I don't know, but here's how I'd find out,' which sounds far more credible than guessing."},
        ],
        "activity": {
            "title": "Capstone Showcase",
            "instructions": "Have students present their knowledge base article or video tutorial to small groups, the whole class, or District IT guests if available, within a set time limit, followed by one audience question each. Have peers complete a short peer-feedback form noting one strength and one suggestion for each presenter.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "The Question You Didn't Expect",
            "scenario": "During a capstone presentation on resetting a school Wi-Fi password, a District IT staff member in the audience asks, 'What would you do if a user didn't have admin rights to install the fix your guide describes?' The presenter's guide assumed the user could freely change network settings, and the question exposes a scenario the presenter genuinely hadn't considered while researching or testing the topic.",
            "task": "Students draft a calm, credible answer the presenter could give on the spot, following today's guidance that it's fine to say 'I don't know, but here's how I'd find out,' and specific to this exact permissions question rather than a generic response.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What's the best response if you don't know the answer to an audience question during your presentation?", "choices": ["A. Make up an answer that sounds confident", "B. Say you don't know, but explain how you'd find out", "C. Ignore the question", "D. Ask the audience to leave"], "answer": "B"},
                {"type": "multiple_choice", "q": "A strong capstone presentation should cover the problem, the process, the result, and...", "choices": ["A. Every certification you've ever heard of", "B. What you'd do differently with more time", "C. A list of unrelated tickets", "D. Nothing else, those three are enough"], "answer": "B"},
                {"type": "short_answer", "q": "Why should you connect your capstone presentation back to the performance-level ladder (Apprentice, Technician, Lead Tech, Professional)?", "sample_answer": "It shows the audience not just what you built, but how far you've grown as a technician over the semester, which is exactly what the Capstone & Portfolio category is meant to measure."},
            ],
        },
        "exit_ticket": {"prompt": "What's one piece of feedback you received today, and how will you use it?"},
        "slide_bullets": [
            "Presentation = Professionalism & Service in action",
            "Cover: problem, process, result, what you'd change",
            "Be ready for real questions, including from District IT",
            "It's okay to say 'I don't know, but here's how I'd find out'",
            "Today: present, ask questions, give peer feedback",
        ],
        "academic_vocab": {
            "word": "Advocate",
            "definition": "To speak up in support of yourself or an idea.",
            "syllables": "AD-vuh-kayt",
            "morphology": "Latin ad- (to) + vocare (to call) — literally, one called to speak on another's behalf",
            "example": "During the capstone presentation, students had to advocate for the value of their own project, not just describe it.",
        },
    },
    {
        "day": 82,
        "unit": 5,
        "lesson_in_unit": 10,
        "title": "Course Wrap-Up: Turning In Your Work and Looking Ahead",
        "objectives": [
            "I can submit a complete capstone, ticket portfolio, and hardest-ticket reflection.",
            "I can reflect honestly on my growth across the four performance levels this semester.",
            "I can identify next steps toward a certification or IT career pathway after this course.",
        ],
        "vocab": [
            {"word": "Portfolio", "definition": "An organized collection of your best work from the semester, used as evidence of your skills and growth.",
             "example": "Today every student turned in a finished portfolio alongside their capstone.",
             "syllables": "por-FOH-lee-oh",
             "morphology": "Italian portafoglio, from Latin portare (to carry) + folium (a leaf or sheet of paper) — literally, something that carries loose sheets."},
            {"word": "Capstone", "definition": "The final project of the course that shows everything you learned, usually a knowledge base article or a video tutorial.",
             "example": "The capstone, portfolio, and one-page writeup together make up the last grade of the semester.",
             "syllables": "KAP-stohn",
             "morphology": "Latin caput (head, top) + Old English stan (stone) — literally, the finishing stone placed on top of a structure to complete it."},
        ],
        "warm_up": "On day one of this course, you were... Where are you now? Write one sentence comparing the two.",
        "mini_lesson": [
            {"heading": "Final Turn-In Checklist", "body": "Today you turn in three things: your finished portfolio (organized tickets and evidence of growth), your finalized capstone (knowledge base article or video), and a one-page writeup on the hardest ticket you handled all semester, covering what happened, how you solved it, and what you learned."},
            {"heading": "Where You Landed on the Ladder", "body": "Look back at the four levels: Apprentice, Technician, Lead Tech, Professional. Be honest about where you started and where you are now. Most students land somewhere around Technician or Lead Tech by the end of one semester, and that's real progress. Professional is rare and mostly aspirational this early, and that's fine too."},
            {"heading": "What's Next", "body": "This course doesn't have to be the end. Certification exams (CompTIA A+, Google IT Support, CareerSafe, ACER Chromebook Repair) stay open after the semester ends. Tech Warrior Club, a recommendation letter from Ms. Faraday, or a real pathway through District IT are all still available if you want to keep going."},
        ],
        "activity": {
            "title": "Semester Reflection Circle",
            "instructions": "Have students complete a short written reflection answering: your proudest moment, your hardest ticket, the biggest skill you gained, and one goal for what's next. Close the period with students sharing one takeaway aloud in a circle, then collect the three final deliverables: portfolio, capstone, and hardest-ticket writeup.",
        },
        "application": {
            "type": "case_study",
            "title": "Writing the Hardest-Ticket Reflection",
            "scenario": "A student stares at a blank page for the required one-page hardest-ticket writeup, unsure which ticket to write about. One option is a hard networking ticket from Phase 3 that they eventually solved correctly after two wrong theories. The other option is a signal flow problem from Phase 4 that they never fully resolved on their own, and had to hand off to Sam partway through.",
            "task": "Students decide which type of ticket, the one eventually solved or the one left unresolved, would make a stronger hardest-ticket reflection for this assignment, and write a 2-3 sentence outline of what that writeup should cover, based on today's guidance about what the reflection is meant to show.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What three things are due today?", "choices": ["A. A resume, a LinkedIn profile, and a mock interview form", "B. A portfolio, a finalized capstone, and a one-page hardest-ticket writeup", "C. Only the capstone", "D. A certification exam score report"], "answer": "B"},
                {"type": "multiple_choice", "q": "Which is true about the performance-level ladder after one semester?", "choices": ["A. Every student should reach Professional", "B. Most students land around Technician or Lead Tech, and that's real progress", "C. The ladder doesn't apply after the capstone", "D. Apprentice is the highest level"], "answer": "B"},
                {"type": "short_answer", "q": "Name one option a student has for continuing IT skill-building after this course ends.", "sample_answer": "A student could keep working toward a certification exam like CompTIA A+ or Google IT Support, join Tech Warrior Club, or pursue a pathway through District IT."},
            ],
        },
        "exit_ticket": {"prompt": "What's one goal you're taking with you from this course into whatever comes next?"},
        "slide_bullets": [
            "Turn in today: portfolio, finalized capstone, hardest-ticket writeup",
            "Be honest about where you landed on the ladder",
            "Apprentice to Technician to Lead Tech to Professional",
            "Certifications stay open after the semester ends",
            "Reflection circle: proudest moment, hardest ticket, next goal",
        ],
        "academic_vocab": {
            "word": "Reflect",
            "definition": "To think back carefully on an experience to understand what it means or taught you.",
            "syllables": "ri-FLEKT",
            "morphology": "Latin re- (back) + flectere (to bend) — literally, to bend back and look again",
            "example": "The final writeup asked students to reflect honestly on the hardest ticket of their whole semester.",
        },
    },
]
