PHASE_4_META = {
    "number": 4,
    "name": "Professional Certification Intensive",
    "essential_question": "What does it actually take to pass an industry-standard IT certification exam, and how do I close my own gaps before test day?",
    "overview": (
        "This phase shifts from hands-on repair to focused exam preparation across the three "
        "certification tracks the Help Desk supports: CompTIA A+ Core 1, Google IT Support, "
        "and the AVIXA AV Technologist path. Students review blueprint domains, take timed "
        "practice exams, and use real ticket data from their own semester to study smarter, "
        "not just longer."
    ),
    "vocabulary_bank": [
        {"word": "Core 1 (CompTIA)", "definition": "The first of two exams in the CompTIA A+ certification, covering mobile devices, networking, hardware, virtualization/cloud, and hardware troubleshooting.",
         "syllables": "CORE-won (KOM-tee-uh)",
         "morphology": "CompTIA is an acronym for the Computing Technology Industry Association, the group that writes this exam; 'Core' plus the numeral 1 marks this as the first of two required exams (Core 2 is the second)."},
        {"word": "System Administration", "definition": "Managing user accounts, permissions, updates, and settings on computers and networks so they run correctly and securely.",
         "syllables": "SIS-tuhm ad-min-uh-STRAY-shun",
         "morphology": "Greek systema (an organized whole, things standing together) + Latin administrare (ad- 'to' + ministrare 'to serve, manage')."},
        {"word": "Signal Flow", "definition": "The path a signal takes from its source (like a microphone or laptop) through processing equipment to its destination (like a speaker or projector).",
         "syllables": "SIG-nul FLOH",
         "morphology": "Latin signum (a mark or sign) + Old English flowan (to flow, move steadily) — literally, the steady path a signal moves along."},
        {"word": "Stress Test", "definition": "Deliberately pushing hardware or software to its limits to see how it performs under heavy load, used to catch problems before they happen in real use.",
         "syllables": "STRESS TEST",
         "morphology": "Latin stringere (to draw tight, put pressure on) + Latin testum (an earthen pot, used in early metal-assaying — the origin of 'testing' something's quality)."},
        {"word": "Practice Exam", "definition": "A timed, exam-style set of questions used to check readiness and identify weak spots before the real certification test.",
         "syllables": "PRAK-tis eg-ZAM",
         "morphology": "Greek praktikos (fit for action, from prattein 'to do') + Latin examen (the tongue of a balance scale, a means of weighing accurately)."},
        {"word": "Certification Blueprint", "definition": "The official outline of exactly what topics and in what proportion a certification exam will test.",
         "syllables": "sur-tuh-fuh-KAY-shun BLOO-print",
         "morphology": "Latin certus (sure, settled) + -ficare (to make) + 'blueprint,' a compound from the blue-toned copies once made of architectural plans."},
    ],
    "unit_assessment": {
        "title": "Phase 4 Assessment: Professional Certification Intensive",
        "questions": [
            {"type": "multiple_choice", "q": "Which domain group belongs to the CompTIA A+ Core 1 exam?",
             "choices": ["A. Mobile devices, networking, hardware, virtualization/cloud, hardware troubleshooting", "B. Only mobile devices", "C. Only networking", "D. Signal flow and audio mixing"],
             "answer": "A"},
            {"type": "multiple_choice", "q": "Managing user accounts, permissions, and updates on a computer is best described as:",
             "choices": ["A. Signal flow", "B. System administration", "C. A stress test", "D. A certification blueprint"],
             "answer": "B"},
            {"type": "multiple_choice", "q": "In an AV setup, signal flow refers to:",
             "choices": ["A. How loud a speaker can get", "B. The path a signal takes from source to destination through the equipment in between", "C. The brand of projector being used", "D. The number of cables in a closet"],
             "answer": "B"},
            {"type": "multiple_choice", "q": "Why do techs run a stress test on a repaired device before returning it to service?",
             "choices": ["A. To make the device look busy", "B. To catch problems under heavy load before the user experiences them", "C. Because it's required by warranty", "D. To use up spare time"],
             "answer": "B"},
            {"type": "multiple_choice", "q": "A certification blueprint is most useful for:",
             "choices": ["A. Deciding what to study and how much time to spend on each topic", "B. Replacing the need to study at all", "C. Only listing which questions are true or false", "D. Choosing which certification costs less"],
             "answer": "A"},
            {"type": "multiple_choice", "q": "After a timed practice exam, the most useful next step is to:",
             "choices": ["A. Immediately retake the exact same exam", "B. Review missed questions to find patterns in weak areas, then target that review", "C. Ignore the results and move to a different certification", "D. Memorize the answer key without understanding why"],
             "answer": "B"},
            {"type": "short_answer", "q": "Explain why a live-ticket day during cert review week is useful, even though it isn't itself a practice exam.", "sample_answer": "It tests whether review material transfers to real, unpredictable problems, not just multiple-choice questions, and builds genuine confidence and skill that a written exam alone can't measure."},
            {"type": "short_answer", "q": "Pick one certification thread from this phase (CompTIA, Google IT Support, or AVIXA) and describe one specific gap you identified in your own knowledge and how you're addressing it.", "sample_answer": "Answers will vary; should name a specific blueprint domain, a specific weakness found through practice questions, and a specific study action taken."},
        ],
    },
    "days": [55, 72],
}

PHASE_4_LESSONS = [
    {
        "day": 55,
        "unit": 4,
        "lesson_in_unit": 1,
        "title": "CompTIA A+ Core 1: What's Actually on the Exam",
        "objectives": [
            "I can name the five domain groups covered by the CompTIA A+ Core 1 exam.",
            "I can explain what a certification blueprint is and why it matters for studying.",
            "I can self-rate my current confidence in each Core 1 domain.",
        ],
        "vocab": [
            {"word": "Core 1 (CompTIA)", "definition": "The first of two exams in the CompTIA A+ certification, covering mobile devices, networking, hardware, virtualization/cloud, and hardware troubleshooting.",
             "example": "Core 1 is the exam we're reviewing this week using Professor Messer's free video series.",
             "syllables": "CORE-won (KOM-tee-uh)",
             "morphology": "CompTIA is an acronym for the Computing Technology Industry Association, the group that writes this exam; 'Core' plus the numeral 1 marks this as the first of two required exams (Core 2 is the second)."},
            {"word": "Certification Blueprint", "definition": "The official outline of exactly what topics and in what proportion a certification exam will test.",
             "example": "The Core 1 blueprint tells us hardware and networking make up a big chunk of the exam, so we should study those hardest.",
             "syllables": "sur-tuh-fuh-KAY-shun BLOO-print",
             "morphology": "Latin certus (sure, settled) + -ficare (to make) + 'blueprint,' a compound from the blue-toned copies once made of architectural plans."},
        ],
        "warm_up": "Without looking anything up, list three IT topics you think a hardware certification exam would probably test.",
        "mini_lesson": [
            {"heading": "Why a Blueprint Beats Guessing", "body": "Studying without a blueprint means guessing what matters. CompTIA publishes an exact blueprint for Core 1: percentages showing how much of the exam covers mobile devices, networking, hardware, virtualization/cloud, and hardware troubleshooting. Professor Messer's free review series follows this same structure, which is why we're using it this phase."},
            {"heading": "The Five Domains", "body": "Core 1 covers: Mobile Devices (laptops, tablets, phones), Networking (cables, wireless, hardware), Hardware (components, peripherals, power), Virtualization and Cloud Computing (basic concepts), and Hardware and Network Troubleshooting (methodology). Most of what you already learned in Phases 1-3 maps directly onto these domains."},
        ],
        "activity": {
            "title": "Blueprint Self-Assessment",
            "instructions": "Give students the five Core 1 domain names. Have them rate their confidence 1-5 in each, then pair up and explain to a partner which domain they feel weakest in and why. Collect the self-ratings to use for grouping students in later review days.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "Where Should the Study Hours Go?",
            "scenario": "The Core 1 blueprint weights its five domains unevenly: Mobile Devices 14%, Networking 20%, Hardware 27%, Virtualization/Cloud 12%, and Troubleshooting 27% of the exam. A student named Priya rated her own confidence 1-5 in each domain after today's warm-up: Mobile Devices 4, Networking 2, Hardware 3, Virtualization/Cloud 4, Troubleshooting 3. Priya has exactly six hours of study time before her scheduled testing window and wants to spend it where it will do the most good, not just on whatever feels most comfortable to review. She knows that a high blueprint percentage paired with low confidence is a bigger problem than a high blueprint percentage paired with high confidence, and that a domain she already feels solid in probably doesn't need six hours split evenly across everything.",
            "task": "Using Priya's confidence ratings and the blueprint percentages, students calculate a rough 'priority score' for each domain (a higher blueprint percentage combined with a lower confidence rating should produce a higher priority score), rank all five domains from most to least urgent to study, and write one sentence justifying which domain should get the most of Priya's six hours.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which of these is NOT one of the five Core 1 domains?",
                 "choices": ["A. Mobile Devices", "B. Networking", "C. Signal Flow", "D. Hardware Troubleshooting"], "answer": "C"},
                {"type": "multiple_choice", "q": "A certification blueprint is most useful because it:",
                 "choices": ["A. Guarantees a passing score", "B. Tells you what topics matter and how much", "C. Replaces the need for practice questions", "D. Is only used after the exam"], "answer": "B"},
                {"type": "short_answer", "q": "Which Core 1 domain do you feel most confident in already, based on what we've done in this course? Why?", "sample_answer": "Answers vary; should connect to specific Phase 1-3 experience, e.g. hardware from Chromebook repair or networking from Phase 3."},
            ],
        },
        "exit_ticket": {"prompt": "Name the one Core 1 domain you most need to review, and one specific thing you'll do this week to study it."},
        "slide_bullets": [
            "CompTIA A+ Core 1: five domains",
            "Mobile Devices, Networking, Hardware, Virtualization/Cloud, Troubleshooting",
            "Blueprint = official map of what's tested and how much",
            "Professor Messer review series follows the same structure",
            "This week: self-assess, then target your weak spots",
        ],
        "academic_vocab": {
            "word": "Prioritize",
            "definition": "To decide what to focus on first based on what matters most or is most urgent.",
            "syllables": "pry-OR-uh-tyze",
            "morphology": "Latin prior (former, earlier, more important) + -itize (a suffix meaning 'to make into')",
            "example": "After rating her confidence in all five Core 1 domains, Priya had to prioritize which domain to study first.",
        },
    },
    {
        "day": 56,
        "unit": 4,
        "lesson_in_unit": 2,
        "title": "Mobile Devices Deep Dive",
        "objectives": [
            "I can list common mobile device components tested on Core 1.",
            "I can connect Phase 2 Chromebook repair skills to the Mobile Devices domain.",
        ],
        "vocab": [
            {"word": "Core 1 (CompTIA)", "definition": "The first of two exams in the CompTIA A+ certification.",
             "example": "Today's review focuses on the Mobile Devices portion of Core 1.",
             "syllables": "CORE-won (KOM-tee-uh)",
             "morphology": "CompTIA is an acronym for the Computing Technology Industry Association, the group that writes this exam; 'Core' plus the numeral 1 marks this as the first of two required exams (Core 2 is the second)."},
        ],
        "warm_up": "List every internal Chromebook component you remember replacing or learning about in Phase 2.",
        "mini_lesson": [
            {"heading": "Mobile Devices on the Exam", "body": "Core 1's Mobile Devices domain covers laptop hardware and disassembly, mobile device accessories, connection types, and mobile OS basics. You already have hands-on experience with a lot of this from Phase 2 Chromebook repair - screens, batteries, keyboards, daughterboards."},
            {"heading": "What's New Beyond Chromebooks", "body": "The exam also expects familiarity with tablets, smartphones, and their accessories (styluses, docking stations, wearables) even though our Help Desk mostly services Chromebooks. Professor Messer's videos cover these device types we haven't handled hands-on."},
        ],
        "activity": {
            "title": "Chromebook-to-Blueprint Mapping",
            "instructions": "Have students list Phase 2 repair skills on one side of a page and match each to a Core 1 Mobile Devices exam topic on the other side. Discuss as a class which exam topics have zero hands-on match and need extra video review.",
        },
        "application": {
            "type": "case_study",
            "title": "The Phone Nobody's Repaired",
            "scenario": "During lunch, a teacher walks into the Help Desk holding a personal Android tablet with a spiderwebbed, cracked digitizer covering the screen. She explains she uses it to project reading passages onto the classroom board every morning and asks if 'the computer kids' can take a quick look before her next class starts in twenty minutes. The Help Desk normally only services school-issued Chromebooks, and nobody on shift has ever opened a tablet like this one before. It does, however, use several of the same connection types and battery concepts covered in today's Mobile Devices domain review, even though the internal layout looks nothing like a Chromebook.",
            "task": "Students decide, using today's lesson on Mobile Devices sub-topics, whether to attempt any hands-on triage of the tablet, only offer general troubleshooting advice, or refer the teacher elsewhere, and justify the decision in 2-3 sentences using at least one specific Core 1 Mobile Devices concept.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which Phase 2 skill maps most directly onto the Core 1 Mobile Devices domain?",
                 "choices": ["A. FAFSA forms", "B. Chromebook screen and battery replacement", "C. Filing taxes", "D. Stock market basics"], "answer": "B"},
                {"type": "short_answer", "q": "Name one mobile device type the exam covers that our Help Desk doesn't typically repair.", "sample_answer": "Smartphones or tablets - our Help Desk mostly services Chromebooks."},
            ],
        },
        "exit_ticket": {"prompt": "What's one Mobile Devices exam topic you need to review through video, since we don't repair it hands-on at our desk?"},
        "slide_bullets": [
            "Mobile Devices domain: laptops, tablets, phones, accessories",
            "Phase 2 Chromebook skills map directly onto this domain",
            "New territory: tablets, smartphones, wearables",
            "Use Professor Messer for device types we don't repair here",
        ],
        "academic_vocab": {
            "word": "Categorize",
            "definition": "To sort things into groups based on shared characteristics.",
            "syllables": "KAT-uh-guh-ryze",
            "morphology": "Greek kategoria (an accusation, later 'category, class') + -ize (a suffix meaning 'to make or do')",
            "example": "Students categorized each Phase 2 repair skill under the correct Core 1 Mobile Devices sub-topic.",
        },
    },
    {
        "day": 57,
        "unit": 4,
        "lesson_in_unit": 3,
        "title": "Hardware Networking for Core 1",
        "objectives": [
            "I can identify network hardware and cable types tested on Core 1.",
            "I can connect Phase 3 networking fundamentals to this exam domain.",
        ],
        "vocab": [
            {"word": "Certification Blueprint", "definition": "The official outline of exactly what topics and in what proportion a certification exam will test.",
             "example": "The blueprint groups cables, connectors, and network devices under the Networking domain.",
             "syllables": "sur-tuh-fuh-KAY-shun BLOO-print",
             "morphology": "Latin certus (sure, settled) + -ficare (to make) + 'blueprint,' a compound from the blue-toned copies once made of architectural plans."},
        ],
        "warm_up": "From Phase 3, name every piece of network hardware you can remember (cables, devices, connectors).",
        "mini_lesson": [
            {"heading": "Networking on Core 1", "body": "The Networking domain covers cables and connectors (Ethernet, fiber, coax), network devices (switches, routers, access points), and wireless standards. Phase 3's IP address, DNS, and Wi-Fi versus Ethernet content lines up directly with this domain."},
            {"heading": "Filling the Gaps", "body": "The exam goes a bit deeper than our Phase 3 work into cable categories (Cat 5e vs Cat 6) and connector types (RJ-45, coax, fiber). This is a good spot to use Professor Messer's cable-identification videos since we don't have every cable type on hand at our desk."},
        ],
        "activity": {
            "title": "Cable and Connector ID Station",
            "instructions": "Set out any cables/connectors available in the repair space (Ethernet, HDMI, USB types). Students identify each and note which Core 1 sub-topic it falls under, then use video resources to fill in any cable types not physically available.",
        },
        "application": {
            "type": "simulation",
            "title": "The Supply Closet Audit",
            "scenario": "The Help Desk's supply closet inventory currently shows: 3 Cat 5e cables, 0 Cat 6 cables, 2 HDMI cables, 5 RJ-45 connectors, and 1 spool of fiber cable that has never been used. District IT has asked the Help Desk to wire two new Chromebook carts into the classroom network before next week, and each cart needs one Cat 6 cable run to the nearest wall jack plus a working RJ-45 connector crimped onto each end. The fiber spool is not needed for this job since fiber only runs between the building's main network closets, not to individual classroom carts.",
            "task": "Students use the inventory list and the job requirements to calculate exactly what's missing to complete both cart installations, then write a short supply request naming the exact cable and connector types and quantities needed, using correct Core 1 Networking terminology.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which of these is a network cable type covered on Core 1?",
                 "choices": ["A. Spudger", "B. Ethernet", "C. FICA", "D. FERPA"], "answer": "B"},
                {"type": "short_answer", "q": "Name one Phase 3 concept that overlaps with the Core 1 Networking domain.", "sample_answer": "IP addresses, DNS, or Wi-Fi vs Ethernet troubleshooting."},
            ],
        },
        "exit_ticket": {"prompt": "Name one cable or connector type you're still unsure about identifying, and where you'll go to review it."},
        "slide_bullets": [
            "Networking domain: cables, connectors, devices, wireless standards",
            "Phase 3 content overlaps heavily here",
            "New depth: cable categories, connector types",
            "Use video review for cable types not on hand",
        ],
        "academic_vocab": {
            "word": "Differentiate",
            "definition": "To recognize and explain the specific differences between similar things.",
            "syllables": "dif-uh-REN-shee-ayt",
            "morphology": "Latin differre (to carry apart, to differ) + -ate (a verb-forming suffix)",
            "example": "Being able to differentiate a Cat 5e cable from a Cat 6 cable matters on the Core 1 Networking domain.",
        },
    },
    {
        "day": 58,
        "unit": 4,
        "lesson_in_unit": 4,
        "title": "Core 1 Practice Set + Where I Stand",
        "objectives": [
            "I can answer practice questions covering Mobile Devices, Networking, and Hardware.",
            "I can identify my remaining weak spots ahead of the Google IT Support review week.",
        ],
        "vocab": [
            {"word": "Practice Exam", "definition": "A timed, exam-style set of questions used to check readiness and identify weak spots before the real certification test.",
             "example": "Today's Core 1 practice set is shorter than a full practice exam, but it works the same way.",
             "syllables": "PRAK-tis eg-ZAM",
             "morphology": "Greek praktikos (fit for action, from prattein 'to do') + Latin examen (the tongue of a balance scale, a means of weighing accurately)."},
        ],
        "warm_up": "In one sentence, name the Core 1 domain you feel best prepared for after this week.",
        "mini_lesson": [
            {"heading": "Practice Sets vs. Full Exams", "body": "Today isn't a full timed practice exam yet - that comes in Week 16. Today is a shorter practice set focused just on this week's three domains: Mobile Devices, Networking, and Hardware, so we can catch gaps early instead of waiting until the end of the phase."},
            {"heading": "Reading Your Own Results", "body": "After the practice set, don't just look at your score - look at which specific questions you missed and why. A wrong answer because you didn't know a term is different from a wrong answer because you misread the question. Both matter, but they need different fixes."},
        ],
        "activity": {
            "title": "Core 1 Practice Set",
            "instructions": "Administer a 15-question practice set covering this week's three domains. Afterward, have students categorize each miss as 'didn't know it' or 'misread it,' then write one specific study action for next week.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "Reading the Miss Pattern",
            "scenario": "A student named Marcus missed six questions on today's practice set: two from Mobile Devices, one from Networking, and three from Hardware. Looking back at his answer sheet, on the two Mobile Devices misses he had picked an answer choice that didn't even relate to the question being asked, suggesting he read too fast. On the Networking miss, he left the term 'RJ-45' blank because he genuinely didn't recognize it. On all three Hardware misses, he picked answers that were close but not quite right, and later realized he'd mixed up two similar-sounding component names.",
            "task": "Using Marcus's pattern of misses, students categorize each of his six missed questions as 'didn't know it' or 'misread it,' tally which domain has the most misses overall, and write one specific study action Marcus should take before the Google IT Support review week begins.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "The best reason to categorize a missed practice question as 'didn't know it' vs 'misread it' is to:",
                 "choices": ["A. Assign blame", "B. Choose the right kind of fix for each type of mistake", "C. Make the score look better", "D. Skip reviewing entirely"], "answer": "B"},
                {"type": "short_answer", "q": "What is one specific study action you'll take before the next Core 1 checkpoint?", "sample_answer": "Answers vary; should name a specific domain and a specific resource or method."},
            ],
        },
        "exit_ticket": {"prompt": "Which Core 1 domain from this week needs the most additional review before the real exam?"},
        "slide_bullets": [
            "Practice set: Mobile Devices, Networking, Hardware",
            "Look at WHY you missed a question, not just the score",
            "'Didn't know it' vs 'misread it' need different fixes",
            "Set one specific study goal for next week",
        ],
        "academic_vocab": {
            "word": "Evaluate",
            "definition": "To judge the quality, value, or accuracy of something using evidence.",
            "syllables": "ee-VAL-yoo-ayt",
            "morphology": "Latin e- (out) + valere (to be strong, to be worth) + -ate (a verb-forming suffix)",
            "example": "After the practice set, students had to evaluate whether each miss came from not knowing the content or from misreading the question.",
        },
    },
    {
        "day": 59,
        "unit": 4,
        "lesson_in_unit": 5,
        "title": "Google IT Support: Operating Systems Review",
        "objectives": [
            "I can compare basic administrative tasks across Windows, macOS, ChromeOS, and Linux.",
            "I can explain why the Google IT Support cert covers system administration broadly.",
        ],
        "vocab": [
            {"word": "System Administration", "definition": "Managing user accounts, permissions, updates, and settings on computers and networks so they run correctly and securely.",
             "example": "System administration looks a little different on Windows versus ChromeOS, but the core ideas are the same.",
             "syllables": "SIS-tuhm ad-min-uh-STRAY-shun",
             "morphology": "Greek systema (an organized whole, things standing together) + Latin administrare (ad- 'to' + ministrare 'to serve, manage')."},
        ],
        "warm_up": "Name one task you've done as a Help Desk tech that counts as system administration, even if you didn't call it that at the time.",
        "mini_lesson": [
            {"heading": "What Google IT Support Covers", "body": "The Google IT Support Certificate, hosted on Coursera, covers troubleshooting, networking, operating systems, system administration, and security - a broader software-focused counterpart to CompTIA's hardware-heavy Core 1. This week we focus on the operating systems and system administration modules."},
            {"heading": "OS Administration Basics Across Platforms", "body": "Every OS handles user accounts, permissions, and updates differently, but the underlying concepts repeat: who can access what, how software stays current, and how settings get managed centrally. ChromeOS management through Google admin console is a real-world example students already touch through school devices."},
        ],
        "activity": {
            "title": "OS Comparison Chart",
            "instructions": "Have students build a comparison chart with rows for user accounts, permissions, and updates, and columns for Windows, macOS, ChromeOS, and Linux. Fill in what they know from experience, then use Coursera module content to complete any gaps.",
        },
        "application": {
            "type": "case_study",
            "title": "Same Task, Four Operating Systems",
            "scenario": "The district rolls out a new spreadsheet app to every school device on the same morning. By lunch, the Help Desk has four tickets about it: a teacher on a Windows laptop who can't find the 'install' button in Control Panel, a teacher on a school MacBook whose app is 'stuck downloading' in the App Store, a student on a ChromeOS Chromebook whose app icon shows a small cloud instead of opening, and a computer science teacher on a Linux lab machine who says the app 'isn't in the package manager yet.' Each ticket uses different language for what is, underneath, the same basic system administration task: getting new software properly installed and updated.",
            "task": "Students match each ticket's description to the operating system it's describing and analyze how the same underlying system administration task (installing/updating software) looks different on each platform, writing one sentence per OS translating the ticket into the platform's actual next step.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "The Google IT Support Certificate is best described as:",
                 "choices": ["A. Hardware-only, like Core 1", "B. A broader software-focused certification covering OS, networking, and system administration", "C. Only about AV equipment", "D. A hardware repair certification"], "answer": "B"},
                {"type": "short_answer", "q": "Give one example of system administration you already do or have seen done at the Help Desk.", "sample_answer": "Answers vary; e.g. managing device enrollment, resetting a user's ChromeOS profile, or applying a policy through the admin console."},
            ],
        },
        "exit_ticket": {"prompt": "Name one system administration task that works differently on ChromeOS compared to Windows."},
        "slide_bullets": [
            "Google IT Support: broader, software-focused cert",
            "Covers OS, networking, system administration, security",
            "This week: OS and system administration modules",
            "Concepts repeat across platforms even when steps differ",
        ],
        "academic_vocab": {
            "word": "Analyze",
            "definition": "To break something down into its parts to understand how it works.",
            "syllables": "AN-uh-lyze",
            "morphology": "Greek ana- (up, throughout) + lyein (to loosen, undo)",
            "example": "Students analyzed how the same system administration task looks different on Windows, macOS, ChromeOS, and Linux.",
        },
    },
    {
        "day": 60,
        "unit": 4,
        "lesson_in_unit": 6,
        "title": "Ticket #9: The Question That Got Jordan",
        "objectives": [
            "I can identify a system administration concept from a story about a missed practice question.",
            "I can describe a strategy for rebuilding confidence after a bad practice-exam result.",
        ],
        "vocab": [
            {"word": "System Administration", "definition": "Managing user accounts, permissions, updates, and settings on computers and networks so they run correctly and securely.",
             "example": "Jordan's missed question was about a system administration concept: user permissions.",
             "syllables": "SIS-tuhm ad-min-uh-STRAY-shun",
             "morphology": "Greek systema (an organized whole, things standing together) + Latin administrare (ad- 'to' + ministrare 'to serve, manage')."},
        ],
        "warm_up": "Describe a time you did badly on a quiz or test and then bounced back. What helped you recover?",
        "mini_lesson": [
            {"heading": "Setting Up Today's Reading", "body": "Today's Ticket # installment is prose, not a comic panel, following Jordan through a rough moment during Google IT Support practice questions. Confidence dips during cert study are normal and expected - what matters is what you do next."},
            {"heading": "The System Administration Concept Behind It", "body": "The question that trips up Jordan involves user permission levels - the idea that not every account should have the same level of access, and that administrators control this deliberately for security reasons. This is a core system administration idea worth understanding deeply, not just memorizing."},
        ],
        "activity": {
            "title": "Read and Reflect",
            "instructions": "Students read the prose installment, then in pairs discuss: what permission concept tripped up Jordan, and has something similar happened to them during practice questions? Debrief as a class on strategies for bouncing back from a rough practice session.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "Two Accounts, One Mistake",
            "scenario": "A brand-new substitute teacher account was set up in a hurry the night before a field trip and was accidentally given full administrator rights instead of standard teacher rights. The next day, a student using that sub's login on a shared classroom Chromebook was able to install an unapproved browser extension that the school normally blocks on student accounts.",
            "task": "In 2-3 sentences, students explain what permission-level mistake caused this problem and what setting, if configured correctly from the start, should have prevented the student from installing the extension.",
        },
        "reading": {
            "type": "realistic_fiction",
            "title": "Ticket #9: The Question That Got Jordan",
            "body": "The practice question seemed simple enough on the screen: 'A teacher's account can install software, but a student's account cannot. This is an example of what system administration concept?' Jordan stared at the four answer choices for a long moment, picked one, and got it wrong. Then got the next one wrong too, for a related reason. Then a third.\n\nBy the fourth miss, Jordan had stopped reading the questions carefully and started just guessing, fast, to get through it.\n\nSam noticed from across the room. 'You're speed-running that practice set.'\n\n'I'm bad at this section,' Jordan said, not looking up. 'Permissions, user accounts, all of it. I don't get it.'\n\n'You fixed three permission issues on real tickets last month,' Sam said. 'What's different now?'\n\nJordan thought about it. 'On tickets, I just... fix the actual problem in front of me. This is asking me to explain the concept behind it, like, why it works that way, not just how to click the button.'\n\n'That's a real difference,' Sam said, pulling up a chair. 'Let's slow down. That question about the teacher and the student account - what's actually going on there?'\n\n'The teacher can install stuff and the student can't,' Jordan said.\n\n'Right. And why would a school set it up that way on purpose?'\n\nJordan paused. 'So students can't accidentally, like, install something bad, or mess up a shared device for the next class.'\n\n'That's it. That's the concept. It's called permission levels, or access control, depending on the wording. You already understood the reason. You just panicked when the question asked you to name it instead of just do it.'\n\nJordan exhaled. 'So I'm not bad at permissions. I'm bad at slowing down when a question sounds unfamiliar.'\n\n'Different problem, much easier fix,' Sam said. 'Next time you miss a few in a row, stop. Read the next one twice before answering. You already know more of this than the wrong answers suggest.'\n\nJordan went back to the practice set, slower this time. The next permission question took twice as long to read - and got answered correctly.",
            "questions": [
                "What system administration concept was actually behind the question Jordan kept missing?",
                "According to Sam, what was Jordan's real problem: not knowing the content, or something else? Explain.",
                "Why does a school set up teacher accounts and student accounts with different permission levels on purpose?",
                "Have you ever gotten multiple questions wrong in a row on a test and started rushing? What did that lead to?",
            ],
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "In the reading, why can a teacher's account install software while a student's account cannot?",
                 "choices": ["A. It's a random settings error", "B. Deliberate permission levels set by an administrator for security and stability", "C. Teacher accounts are simply older", "D. Student accounts are broken"], "answer": "B"},
                {"type": "multiple_choice", "q": "What was Jordan's actual mistake, according to Sam?",
                 "choices": ["A. Not understanding permissions at all", "B. Rushing and not reading unfamiliar-sounding questions carefully", "C. Never having fixed a permissions ticket before", "D. Refusing to take the practice set seriously"], "answer": "B"},
                {"type": "short_answer", "q": "Describe a strategy for recovering after missing several practice questions in a row.", "sample_answer": "Slow down, reread the next question carefully rather than rushing, and remember that missing a few questions doesn't mean you don't understand the underlying concept."},
            ],
        },
        "exit_ticket": {"prompt": "Explain, in your own words, what a permission level is and give one real example from your own Help Desk experience."},
        "slide_bullets": [
            "Ticket #9: Jordan misses permission questions, then rushes",
            "Real issue: rushing on unfamiliar wording, not lack of knowledge",
            "Permission levels = deliberate access control set by admins",
            "Fix: slow down after a miss, reread carefully",
        ],
        "academic_vocab": {
            "word": "Interpret",
            "definition": "To explain the meaning of something, especially when it isn't stated directly.",
            "syllables": "in-TUR-prit",
            "morphology": "Latin inter- (between) + pretari (to explain, appraise)",
            "example": "Sam helped Jordan interpret what the practice question about teacher and student accounts was really asking.",
        },
    },
    {
        "day": 61,
        "unit": 4,
        "lesson_in_unit": 7,
        "title": "System Administration: User Accounts & Permissions",
        "objectives": [
            "I can explain what permission levels are and why they exist.",
            "I can describe how account management connects to security.",
        ],
        "vocab": [
            {"word": "System Administration", "definition": "Managing user accounts, permissions, updates, and settings on computers and networks so they run correctly and securely.",
             "example": "Setting up different permission levels for teachers and students is a core system administration task.",
             "syllables": "SIS-tuhm ad-min-uh-STRAY-shun",
             "morphology": "Greek systema (an organized whole, things standing together) + Latin administrare (ad- 'to' + ministrare 'to serve, manage')."},
        ],
        "warm_up": "List every account type you can think of at your school (student, teacher, admin, guest, etc.) and guess what each one is and isn't allowed to do.",
        "mini_lesson": [
            {"heading": "Permission Levels, For Real This Time", "body": "Building on yesterday's reading: permission levels (also called access control) determine what a user account can see, install, or change. Standard users have limited permissions; administrator accounts have broad control. This protects both security (preventing unauthorized changes) and stability (preventing accidental damage to shared systems)."},
            {"heading": "Where Techs Fit In", "body": "Help Desk techs typically work with elevated-but-limited permissions - more access than a regular student account, but not full admin control over the whole district network. Knowing where your own permission level ends, and when to escalate to District IT, is itself a system administration skill."},
        ],
        "activity": {
            "title": "Permission Level Map",
            "instructions": "Have students draw a simple pyramid or ladder diagram showing permission levels at their school (student, teacher, Help Desk tech, District IT admin), noting one thing each level can and cannot do. Discuss where the Help Desk's own limits are.",
        },
        "application": {
            "type": "simulation",
            "title": "Setting the Permission Ladder",
            "scenario": "A simplified permissions table lists four account types (Guest, Student, Teacher, Help Desk Tech) against five capabilities (install software, browse other users' files, change network settings, reset another person's password, view their own grades or work only). As currently configured, Guest accounts can install software, Student accounts can browse other users' files, and Help Desk Tech accounts can change network settings district-wide, all of which contradict what today's lesson says permission levels are supposed to protect against.",
            "task": "Students find at least three misassigned permissions in the table, correct each one to match the security and stability principles from today's lesson, and justify each fix in one sentence.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Permission levels exist mainly to protect:",
                 "choices": ["A. Only the appearance of the desktop", "B. Security and system stability", "C. Nothing important", "D. Only printer access"], "answer": "B"},
                {"type": "short_answer", "q": "Describe the Help Desk's own permission level compared to a regular student account and to District IT.", "sample_answer": "The Help Desk has more access than a regular student account for troubleshooting purposes, but less than District IT, which is why some issues get escalated."},
            ],
        },
        "exit_ticket": {"prompt": "Name one task that requires more permission than a Help Desk tech has, and explain why it should be escalated instead."},
        "slide_bullets": [
            "Permission levels control what an account can see/change",
            "Protects security AND stability",
            "Help Desk techs: more access than students, less than District IT",
            "Knowing your limit is part of the job",
        ],
        "academic_vocab": {
            "word": "Justify",
            "definition": "To give solid reasons that support a decision or claim.",
            "syllables": "JUS-tuh-fy",
            "morphology": "Latin justus (right, lawful) + -ficare (to make)",
            "example": "Students had to justify why a Help Desk tech's permission level sits above a student's but below District IT's.",
        },
    },
    {
        "day": 62,
        "unit": 4,
        "lesson_in_unit": 8,
        "title": "Google IT Support: Troubleshooting Methodology",
        "objectives": [
            "I can describe a standard IT troubleshooting methodology.",
            "I can connect this methodology to the intake skills practiced all semester.",
        ],
        "vocab": [
            {"word": "System Administration", "definition": "Managing user accounts, permissions, updates, and settings on computers and networks so they run correctly and securely.",
             "example": "A consistent troubleshooting methodology makes system administration problems easier to solve under pressure.",
             "syllables": "SIS-tuhm ad-min-uh-STRAY-shun",
             "morphology": "Greek systema (an organized whole, things standing together) + Latin administrare (ad- 'to' + ministrare 'to serve, manage')."},
        ],
        "warm_up": "Write down the exact steps you personally take when you sit down to fix an unfamiliar tech problem.",
        "mini_lesson": [
            {"heading": "A Repeatable Method", "body": "Google IT Support teaches a troubleshooting methodology: identify the problem, establish a theory of probable cause, test the theory, establish a plan and implement it, verify full functionality, and document findings. This isn't new to you - it's the same instinct behind good intake, just formalized into named steps."},
            {"heading": "Why Naming the Steps Helps on the Exam", "body": "Exam questions often describe a scenario and ask 'what should you do next in the troubleshooting process?' Knowing the named steps in order helps you answer these quickly, even under time pressure, instead of just guessing based on gut feeling."},
        ],
        "activity": {
            "title": "Name the Step",
            "instructions": "Present 5 short real-ticket scenarios from the semester. In pairs, students identify which troubleshooting methodology step is happening in each scenario (identify, theory, test, plan/implement, verify, document).",
        },
        "application": {
            "type": "case_study",
            "title": "The Six Steps, Out of Order",
            "scenario": "A tech named Dana gets a ticket about a classroom printer that won't print. Dana quickly restarts the printer, it starts working again, and Dana moves on to the next ticket without checking whether the fix actually holds up under normal use or writing down what she found. A week later, the same printer jams again in the exact same spot, and this time it takes another tech twenty extra minutes to figure out that a worn roller, not a simple glitch, was the real cause all along - something Dana's restart never actually addressed.",
            "task": "Students identify which two troubleshooting methodology steps Dana skipped, explain the real-world consequence of skipping them, and rewrite a short plan for how Dana should have handled the original ticket using all six steps.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which comes first in the standard IT troubleshooting methodology?",
                 "choices": ["A. Document findings", "B. Identify the problem", "C. Verify full functionality", "D. Implement the plan"], "answer": "B"},
                {"type": "short_answer", "q": "Give a real ticket example from this semester and match it to at least two troubleshooting methodology steps.", "sample_answer": "Answers vary; should name a specific ticket and correctly sequence at least two of the six steps."},
            ],
        },
        "exit_ticket": {"prompt": "Name the troubleshooting methodology step you personally skip most often, and why that's risky."},
        "slide_bullets": [
            "Google IT troubleshooting methodology: 6 named steps",
            "Identify, theory, test, plan/implement, verify, document",
            "Same instinct as good intake, just formalized",
            "Exam questions often ask 'what's the next step?'",
        ],
        "academic_vocab": {
            "word": "Summarize",
            "definition": "To state the main points of something briefly, leaving out extra detail.",
            "syllables": "SUM-uh-ryze",
            "morphology": "Latin summa (the whole, sum total) + -ize (a suffix meaning 'to make or do')",
            "example": "Students summarized the six-step troubleshooting methodology in their own words before applying it to real tickets.",
        },
    },
    {
        "day": 63,
        "unit": 4,
        "lesson_in_unit": 9,
        "title": "Google IT Support Practice Set",
        "objectives": [
            "I can answer practice questions covering OS, system administration, and troubleshooting methodology.",
            "I can identify remaining gaps before AV Technologist Prep week.",
        ],
        "vocab": [
            {"word": "Practice Exam", "definition": "A timed, exam-style set of questions used to check readiness and identify weak spots before the real certification test.",
             "example": "Today's Google IT Support practice set works the same way the Core 1 one did in Week 13.",
             "syllables": "PRAK-tis eg-ZAM",
             "morphology": "Greek praktikos (fit for action, from prattein 'to do') + Latin examen (the tongue of a balance scale, a means of weighing accurately)."},
        ],
        "warm_up": "In one sentence, what's the single most useful thing you learned this week about system administration or troubleshooting?",
        "mini_lesson": [
            {"heading": "Consistency Across Threads", "body": "Notice that this week's practice set works the same way Week 13's Core 1 practice set did: focused questions, honest self-scoring, and a specific study plan afterward. Building this habit now makes the full timed practice exams in Week 16 much less stressful."},
            {"heading": "Connecting the Two Certs So Far", "body": "Core 1 and Google IT Support overlap more than they seem to at first: both test troubleshooting methodology, both touch operating systems, both expect you to reason through scenarios rather than just recall facts. Recognizing that overlap means less separate studying, not more."},
        ],
        "activity": {
            "title": "Google IT Support Practice Set",
            "instructions": "Administer a 15-question practice set covering OS review, system administration, and troubleshooting methodology. Have students categorize misses and set one specific study goal, just like the Week 13 practice set.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "The Cross-Domain Scorecard",
            "scenario": "A student's 15-question Google IT Support practice set scorecard shows 5 questions tagged Operating Systems (4 correct, 1 wrong), 5 tagged System Administration (2 correct, 3 wrong), and 5 tagged Troubleshooting Methodology (5 correct, 0 wrong).",
            "task": "Students total the correct and incorrect answers per domain from the scorecard, identify which domain is clearly the weakest, and write a specific one-week study plan (naming a resource and a method) that targets that exact domain before AV Technologist Prep week begins.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What do Core 1 and Google IT Support have in common, despite testing different content?",
                 "choices": ["A. Nothing, they're completely unrelated", "B. Both test troubleshooting methodology and reasoning through scenarios", "C. Both are hardware-only exams", "D. Both are AV certifications"], "answer": "B"},
                {"type": "short_answer", "q": "What is one specific study action you'll take before Week 16's full timed practice exams?", "sample_answer": "Answers vary; should reference a specific weak domain and a specific method or resource."},
            ],
        },
        "exit_ticket": {"prompt": "Which is currently stronger for you: Core 1 or Google IT Support? What's the evidence?"},
        "slide_bullets": [
            "Practice set: OS, system administration, troubleshooting methodology",
            "Same habit as Week 13's Core 1 practice set",
            "Core 1 and Google IT Support overlap more than expected",
            "Building toward Week 16's full timed exams",
        ],
        "academic_vocab": {
            "word": "Synthesize",
            "definition": "To combine separate pieces of information into one connected understanding.",
            "syllables": "SIN-thuh-syze",
            "morphology": "Greek syn- (together) + tithenai (to place, put)",
            "example": "The practice set asked students to synthesize what they'd learned across operating systems, system administration, and troubleshooting methodology.",
        },
    },
    {
        "day": 64,
        "unit": 4,
        "lesson_in_unit": 10,
        "title": "AV Technologist Prep: What Is Signal Flow?",
        "objectives": [
            "I can define signal flow and trace a simple AV signal path.",
            "I can connect Phase 3 AV troubleshooting to the AVIXA certification.",
        ],
        "vocab": [
            {"word": "Signal Flow", "definition": "The path a signal takes from its source (like a microphone or laptop) through processing equipment to its destination (like a speaker or projector).",
             "example": "When a projector shows no picture, the first troubleshooting step is tracing the signal flow from the laptop to the screen.",
             "syllables": "SIG-nul FLOH",
             "morphology": "Latin signum (a mark or sign) + Old English flowan (to flow, move steadily) — literally, the steady path a signal moves along."},
        ],
        "warm_up": "Think of the last time a projector or classroom speaker didn't work. What did the source look like, and what didn't happen at the destination?",
        "mini_lesson": [
            {"heading": "Signal Flow, Step by Step", "body": "Every AV signal moves from a source (laptop, microphone, document camera), possibly through processing (a switcher, an amplifier), to a destination (projector, speaker, screen). Tracing signal flow means checking each link in that chain, in order, to find where it breaks - not randomly guessing at the whole system."},
            {"heading": "AVIXA and the AV Technologist Path", "body": "The AVIXA AV Technologist Certificate is our third certification track, worth roughly 120 hours of study. It formalizes signal flow concepts you've already used informally during Phase 3 classroom tech troubleshooting - projectors, HDMI adapters, interactive whiteboards."},
        ],
        "activity": {
            "title": "Trace the Signal",
            "instructions": "Using the classroom's actual AV setup (or a diagram if unavailable), have students trace the signal flow from laptop to projected image, labeling each link in the chain. Discuss where a break at each link would show up as a symptom.",
        },
        "application": {
            "type": "simulation",
            "title": "Trace the Chain",
            "scenario": "A troubleshooting log for a 'no image' projector ticket shows the following test results, in the order they were checked: laptop screen confirmed on and mirroring correctly; HDMI cable confirmed firmly connected at both ends; AV switcher box checked next, showing no indicator lights at all, even though it's plugged into a power strip that is switched on.",
            "task": "Students use the troubleshooting log to identify exactly which link in the signal flow chain is broken, explain why the earlier links (laptop, cable) can be ruled out based on the data given, and name one specific next thing to check at the switcher itself.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Signal flow refers to:",
                 "choices": ["A. How loud a speaker system is", "B. The path a signal takes from source through processing to destination", "C. The number of cables in a system", "D. The brand of AV equipment used"], "answer": "B"},
                {"type": "short_answer", "q": "Describe the signal flow for a laptop presenting to a classroom projector, from source to destination.", "sample_answer": "Laptop (source) -> HDMI or adapter cable -> possibly a switcher -> projector (destination), which displays the image on the screen."},
            ],
        },
        "exit_ticket": {"prompt": "If a projector shows no image, name two specific points along the signal flow you'd check first, and why."},
        "slide_bullets": [
            "Signal flow: source -> processing -> destination",
            "AVIXA AV Technologist: ~120 hours, our third cert track",
            "Builds on Phase 3 classroom AV troubleshooting",
            "Trace the chain in order, don't guess randomly",
        ],
        "academic_vocab": {
            "word": "Infer",
            "definition": "To figure out something that isn't directly stated, using clues and evidence.",
            "syllables": "in-FUR",
            "morphology": "Latin in- (into) + ferre (to carry, bring)",
            "example": "By checking each link in the signal flow, Jordan could infer exactly where the break was happening.",
        },
    },
    {
        "day": 65,
        "unit": 4,
        "lesson_in_unit": 11,
        "title": "Audio Basics: Mics, Mixers, Speakers",
        "objectives": [
            "I can identify basic audio signal-flow components.",
            "I can troubleshoot a simple audio signal problem using signal flow logic.",
        ],
        "vocab": [
            {"word": "Signal Flow", "definition": "The path a signal takes from its source through processing equipment to its destination.",
             "example": "Audio signal flow usually runs from a microphone, through a mixer, to a speaker.",
             "syllables": "SIG-nul FLOH",
             "morphology": "Latin signum (a mark or sign) + Old English flowan (to flow, move steadily) — literally, the steady path a signal moves along."},
        ],
        "warm_up": "Have you ever heard feedback (a loud screech) from a microphone and speaker? What do you think causes that?",
        "mini_lesson": [
            {"heading": "Audio Signal Flow", "body": "A basic audio chain runs: microphone or audio source, into a mixer (which adjusts levels and combines sources), out to an amplifier, into a speaker. Understanding this chain helps you troubleshoot 'no sound' or 'too quiet' problems by checking each link instead of assuming the whole system is broken."},
            {"heading": "Common Audio Problems", "body": "No sound often means a break early in the chain (unplugged mic, muted channel). Feedback usually means a mic is picking up sound from a speaker that's too close or too loud, creating a loop. Knowing where in the signal flow a symptom appears helps you narrow down the cause fast."},
        ],
        "activity": {
            "title": "Audio Troubleshooting Scenarios",
            "instructions": "Present 4 short 'no sound' or 'feedback' scenarios. In pairs, students identify which link in the audio signal flow is the likely culprit for each, using the source-mixer-amplifier-speaker chain.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "No Sound, Two Suspects",
            "scenario": "During an assembly, the microphone appears to be working (its input light blinks when someone speaks into it), but no sound is coming from the gym speakers at all. A quick check shows the mixer's channel light for that microphone is lit and moving, but the amplifier's output level light stays completely dark no matter how loud anyone speaks.",
            "task": "Using the signal flow chain (mic to mixer to amplifier to speaker), students determine which specific link most likely caused the problem, explain their reasoning using the two clues given, and propose the first fix to try at that link.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "In a basic audio signal chain, what comes between the microphone and the speaker?",
                 "choices": ["A. Nothing, they connect directly", "B. A mixer and/or amplifier", "C. A router", "D. A CPU"], "answer": "B"},
                {"type": "short_answer", "q": "What commonly causes microphone feedback, and how does thinking about signal flow help explain it?", "sample_answer": "Feedback happens when a mic picks up sound from a nearby speaker and re-amplifies it in a loop; understanding the signal path (mic to speaker and back) explains why moving the mic or lowering volume fixes it."},
            ],
        },
        "exit_ticket": {"prompt": "A classroom mic has no sound at all. Name the first two links in the signal flow you'd check."},
        "slide_bullets": [
            "Audio chain: source -> mixer -> amplifier -> speaker",
            "No sound = check early links first",
            "Feedback = mic picking up nearby speaker sound",
            "Signal flow logic narrows down the cause fast",
        ],
        "academic_vocab": {
            "word": "Hypothesize",
            "definition": "To propose a reasonable explanation that can then be tested.",
            "syllables": "hy-POTH-uh-syze",
            "morphology": "Greek hypo- (under) + tithenai (to place, put) — literally, an idea 'placed under' a claim to support it",
            "example": "Before testing anything, students had to hypothesize what was causing the amplifier's silence, based on the mixer light still working.",
        },
    },
    {
        "day": 66,
        "unit": 4,
        "lesson_in_unit": 12,
        "title": "Ticket #10: The Assembly Countdown",
        "objectives": [
            "I can apply signal flow troubleshooting under real time pressure.",
            "I can describe how staying calm affects troubleshooting speed and accuracy.",
        ],
        "vocab": [
            {"word": "Signal Flow", "definition": "The path a signal takes from its source through processing equipment to its destination.",
             "example": "Sam and Jordan trace the signal flow link by link to find the break before the assembly starts.",
             "syllables": "SIG-nul FLOH",
             "morphology": "Latin signum (a mark or sign) + Old English flowan (to flow, move steadily) — literally, the steady path a signal moves along."},
        ],
        "warm_up": "Have you ever had to fix something fast, right before an audience or deadline? How did the time pressure affect how you worked?",
        "mini_lesson": [
            {"heading": "Setting Up Today's Reading", "body": "Today's Ticket # installment is a graphic novel panel script showing Jordan and Sam under real pressure: an AV signal flow problem minutes before a school assembly. Watch how they apply the exact troubleshooting method from this week, even while the clock is running."},
            {"heading": "Speed Without Skipping Steps", "body": "Under pressure, it's tempting to skip steps and just start swapping cables randomly. The reading shows a better approach: still tracing the signal flow in order, just faster and with better-divided labor between two people."},
        ],
        "activity": {
            "title": "Read and Trace",
            "instructions": "Students read the panel script, then diagram the actual signal flow chain from the story and mark where the break turned out to be. Discuss: what would have happened if Jordan and Sam had just started randomly swapping cables instead?",
        },
        "application": {
            "type": "simulation",
            "title": "One More Break in the Chain",
            "scenario": "Later that same night, a second classroom projector also shows a 'no signal' message right before an evening parent event, but this time the AV switcher's indicator lights are on and normal, ruling out the power problem from the story.",
            "task": "In 2-3 sentences, students state which link in the signal flow they'd check next, given that the switcher itself is already confirmed working, and explain why that's the logical next step in the chain.",
        },
        "reading": {
            "type": "graphic_novel",
            "title": "Ticket #10: The Assembly Countdown",
            "body": "PANEL 1: The gym, ten minutes before an all-school assembly. A projector screen shows a blue 'no signal' message. Teachers are starting to file in with students behind them.\nCAPTION: Ten minutes. No image. Two techs.\n\nPANEL 2: SAM OKONKWO and JORDAN REYES jog in with a rolling AV cart, radios crackling.\nSAM: 'Okay, no image, no time to panic. Talk to me. What's the source?'\nJORDAN: 'Laptop's on, I can see it's awake from here.'\n\nPANEL 3: Jordan checks the laptop screen directly.\nJORDAN: 'Laptop's fine, it's mirroring, I can see the desktop right on it.'\nSAM: 'Good. Source is fine. Next link.'\n\nPANEL 4: Sam traces the cable from the laptop toward the wall.\nSAM: 'Cable's plugged into the laptop. Follow it. Where's the other end?'\nJORDAN: 'Goes into this little switcher box under the table.'\n\nPANEL 5: Jordan crouches, checking the switcher box, which has several small lights, none lit.\nJORDAN: 'No lights on the switcher at all. Is that bad?'\nSAM: 'That's exactly the break. No power, no signal passes through.'\n\nPANEL 6: Sam follows the switcher's power cord to a power strip half-hidden behind a curtain, its switch in the off position.\nSAM: 'Power strip's off. Someone must've bumped it setting up chairs.'\n\nPANEL 7: Sam flips the power strip on. The switcher's lights blink on immediately.\nJORDAN: 'Lights are on!'\nSAM: 'Now check the screen.'\n\nPANEL 8: The projector screen flickers, then shows the laptop's desktop clearly, just as the principal walks up to the podium.\nCAPTION: Eight minutes. Image, restored.\n\nPANEL 9: Jordan exhales, hands slightly shaky.\nJORDAN: 'I almost just started unplugging random cables.'\nSAM: 'I know. That's the instinct. But we traced it: source, cable, switcher, power. One link at a time, even at eight minutes to zero.'\n\nPANEL 10: Sam packs up the cart while the assembly starts behind them.\nSAM: 'Fast doesn't mean skipping steps. Fast means knowing the steps cold enough that you can move through them quickly.'\nCAPTION: Ticket #10: closed, with ninety seconds to spare.",
            "questions": [
                "List every link in the signal flow chain Sam and Jordan checked, in order.",
                "Where was the actual break in the signal flow, and what caused it?",
                "What does Sam mean by 'fast doesn't mean skipping steps, fast means knowing the steps cold'?",
                "What might have happened if Jordan had given in to the instinct to just start unplugging random cables?",
            ],
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Where was the actual break in the signal flow in the story?",
                 "choices": ["A. The laptop itself", "B. A power strip that had been switched off, cutting power to the switcher", "C. The projector bulb", "D. The HDMI cable"], "answer": "B"},
                {"type": "multiple_choice", "q": "What troubleshooting approach did Sam insist on, even under time pressure?",
                 "choices": ["A. Randomly swapping cables", "B. Tracing the signal flow one link at a time, in order", "C. Waiting until after the assembly", "D. Replacing the whole projector"], "answer": "B"},
                {"type": "short_answer", "q": "Explain what Sam means by 'fast doesn't mean skipping steps, fast means knowing the steps cold enough to move through them quickly.'", "sample_answer": "Being fast under pressure comes from having the troubleshooting method so practiced that you can run through it quickly and correctly, not from skipping steps and guessing."},
            ],
        },
        "exit_ticket": {"prompt": "Name the four links in the signal flow chain from today's story, in order, from source to destination."},
        "slide_bullets": [
            "Ticket #10: signal flow trace under real time pressure",
            "Source -> cable -> switcher -> power -> destination",
            "Break was a power strip switched off, not the laptop or projector",
            "Fast troubleshooting = practiced steps, not skipped steps",
        ],
        "academic_vocab": {
            "word": "Collaborate",
            "definition": "To work together with someone else toward a shared goal.",
            "syllables": "kuh-LAB-uh-rayt",
            "morphology": "Latin com- (together) + laborare (to work)",
            "example": "Sam and Jordan had to collaborate quickly, each checking a different link in the signal flow, to beat the ten-minute countdown.",
        },
    },
    {
        "day": 67,
        "unit": 4,
        "lesson_in_unit": 13,
        "title": "AV Practice Set + Classroom Tech Recap",
        "objectives": [
            "I can answer practice questions covering signal flow and classroom AV basics.",
            "I can connect this week's AV content back to Phase 3 classroom tech skills.",
        ],
        "vocab": [
            {"word": "Practice Exam", "definition": "A timed, exam-style set of questions used to check readiness and identify weak spots before the real certification test.",
             "example": "This week's AV practice set closes out the third certification thread before the full timed exams begin.",
             "syllables": "PRAK-tis eg-ZAM",
             "morphology": "Greek praktikos (fit for action, from prattein 'to do') + Latin examen (the tongue of a balance scale, a means of weighing accurately)."},
        ],
        "warm_up": "In one sentence, what's the biggest difference between troubleshooting hardware (Core 1), software/accounts (Google IT), and AV signal flow (AVIXA)?",
        "mini_lesson": [
            {"heading": "Three Threads, One Semester", "body": "By now you've reviewed all three certification tracks: CompTIA A+ Core 1 (hardware), Google IT Support (software/systems), and AVIXA AV Technologist (signal flow). Each has its own blueprint, but all three share the same underlying troubleshooting instinct you've been building since Phase 1."},
            {"heading": "What's Next", "body": "Week 16 brings full timed practice exams mixing content from all three tracks, plus a live-ticket day. This week's shorter practice set is your last checkpoint before that bigger test - use it honestly."},
        ],
        "activity": {
            "title": "AV Practice Set",
            "instructions": "Administer a 15-question practice set covering signal flow and classroom AV troubleshooting. Afterward, have students write a one-paragraph reflection comparing their confidence across all three certification threads so far.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "Which Thread Needs the Push?",
            "scenario": "A student rates their confidence out of 10 in each certification thread: Core 1 confidence 8, recent practice score 85%; Google IT Support confidence 7, recent practice score 60%; AVIXA confidence 5, recent practice score 78%. At first glance the AVIXA score looks like the one needing the most work, since its confidence number is lowest.",
            "task": "Students compare each thread's confidence rating against its actual practice score to find the thread where confidence and real performance don't match, explain which mismatch is more concerning and why, and recommend one specific review action for that thread.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which certification thread focuses primarily on signal flow?",
                 "choices": ["A. CompTIA A+ Core 1", "B. Google IT Support", "C. AVIXA AV Technologist", "D. CareerSafe Employability Skills"], "answer": "C"},
                {"type": "short_answer", "q": "Compare your confidence across the three certification threads reviewed so far, and explain why.", "sample_answer": "Answers vary; should reference specific practice set results or hands-on experience for each thread."},
            ],
        },
        "exit_ticket": {"prompt": "Rank the three certification threads from strongest to weakest for you right now, in one sentence."},
        "slide_bullets": [
            "Three threads reviewed: Core 1, Google IT Support, AVIXA",
            "Each has its own blueprint, same troubleshooting instinct underneath",
            "This week's practice set: last checkpoint before Week 16",
            "Next: full timed practice exams mixing all three",
        ],
        "academic_vocab": {
            "word": "Assess",
            "definition": "To carefully judge the current state or quality of something.",
            "syllables": "uh-SES",
            "morphology": "Latin ad- (to) + sedere (to sit) — an assessor originally sat beside a judge to help evaluate a case",
            "example": "Students had to honestly assess their confidence across all three certification threads before ranking them.",
        },
    },
    {
        "day": 68,
        "unit": 4,
        "lesson_in_unit": 14,
        "title": "Timed Practice Exam #1: Full Mix",
        "objectives": [
            "I can complete a timed practice exam mixing all three certification threads.",
            "I can manage my time across a mixed-content timed assessment.",
        ],
        "vocab": [
            {"word": "Stress Test", "definition": "Deliberately pushing hardware or software to its limits to see how it performs under heavy load, used to catch problems before they happen in real use.",
             "example": "A timed practice exam is a bit like a stress test for your own knowledge - it shows where you hold up and where you don't, under pressure.",
             "syllables": "STRESS TEST",
             "morphology": "Latin stringere (to draw tight, put pressure on) + Latin testum (an earthen pot, used in early metal-assaying — the origin of 'testing' something's quality)."},
            {"word": "Practice Exam", "definition": "A timed, exam-style set of questions used to check readiness and identify weak spots before the real certification test.",
             "example": "Today's practice exam mixes questions from Core 1, Google IT Support, and AVIXA for the first time.",
             "syllables": "PRAK-tis eg-ZAM",
             "morphology": "Greek praktikos (fit for action, from prattein 'to do') + Latin examen (the tongue of a balance scale, a means of weighing accurately)."},
        ],
        "warm_up": "Before starting, write down one specific goal for today's timed practice exam - not just 'do well,' something specific and measurable.",
        "mini_lesson": [
            {"heading": "Why Mix the Content Now", "body": "The real certification exams are each single-subject, but mixing all three threads into one timed practice exam builds a skill none of the individual reviews taught: switching mental gears quickly between hardware, software, and AV thinking. That's a realistic Help Desk skill too - tickets don't arrive sorted by category."},
            {"heading": "Time Management Under Pressure", "body": "With a fixed time limit and mixed content, pacing matters. If a question is taking too long, mark it and move on rather than losing time you need for easier questions later. This is a real exam-day strategy, not just a practice-day trick."},
        ],
        "activity": {
            "title": "Timed Practice Exam #1",
            "instructions": "Administer a full timed practice exam (suggest 30-40 questions, strict time limit) mixing Core 1, Google IT Support, and AVIXA content. Do not review answers immediately - save deep review for Day 71.",
        },
        "application": {
            "type": "simulation",
            "title": "The Clock Is Running",
            "scenario": "A mini practice run has 10 questions and a strict 12-minute budget. Based on past timing data, six of the questions (multiple choice, straightforward recall) take about 45 seconds each, and four of the questions (longer scenario-based questions) take about 2 minutes each if answered carefully.",
            "task": "Students calculate the total time needed to answer all 10 questions at those estimated rates, compare it to the 12-minute budget, and decide an order of attack (which questions to answer first, and which to mark and return to if time allows) that gets the most questions answered correctly within the time limit, explaining their reasoning.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Mixing all three certification threads into one timed exam mainly builds:",
                 "choices": ["A. Nothing useful", "B. The skill of switching mental gears quickly between different types of problems, like real tickets do", "C. Only hardware knowledge", "D. Only AV knowledge"], "answer": "B"},
                {"type": "short_answer", "q": "Describe one time-management strategy for a timed exam with mixed content.", "sample_answer": "If a question is taking too long, mark it and move on, then come back if time remains, rather than losing time needed for easier questions."},
            ],
        },
        "exit_ticket": {"prompt": "How did your time management strategy work today? What will you do differently next time, if anything?"},
        "slide_bullets": [
            "Timed Practice Exam #1: Core 1 + Google IT Support + AVIXA mixed",
            "Builds real Help Desk skill: switching gears between problem types",
            "Time management: mark and move on if stuck",
            "Deep review comes later this week, not today",
        ],
        "academic_vocab": {
            "word": "Allocate",
            "definition": "To decide how to divide a limited resource, like time or money, among different needs.",
            "syllables": "AL-uh-kayt",
            "morphology": "Latin ad- (to) + locare (to place)",
            "example": "With a strict time limit, students had to allocate their minutes across the exam instead of dwelling on one hard question.",
        },
    },
    {
        "day": 69,
        "unit": 4,
        "lesson_in_unit": 15,
        "title": "Hardware Stress Test Lab",
        "objectives": [
            "I can run a basic hardware stress test on a device.",
            "I can explain why stress testing catches problems normal use might miss.",
        ],
        "vocab": [
            {"word": "Stress Test", "definition": "Deliberately pushing hardware or software to its limits to see how it performs under heavy load, used to catch problems before they happen in real use.",
             "example": "Running a stress test on a repaired Chromebook can reveal an overheating problem that normal light use wouldn't show.",
             "syllables": "STRESS TEST",
             "morphology": "Latin stringere (to draw tight, put pressure on) + Latin testum (an earthen pot, used in early metal-assaying — the origin of 'testing' something's quality)."},
        ],
        "warm_up": "Why might a repaired device work fine for five minutes but fail after an hour of heavy use?",
        "mini_lesson": [
            {"heading": "What a Stress Test Reveals", "body": "Light, everyday use doesn't always reveal a marginal repair - a slightly loose connection, a battery that struggles under load, a component running hot. Running a device hard for an extended period, a stress test, surfaces these problems before a student takes the device home and it fails on them."},
            {"heading": "Doing It Responsibly", "body": "Stress testing is deliberate and monitored, not just leaving a device running unattended. Techs watch temperature, listen for unusual fan noise, and check performance under load, then compare against a normal baseline."},
        ],
        "activity": {
            "title": "Stress Test a Repaired Device",
            "instructions": "Using a recently repaired practice Chromebook, have students run it under heavy load (multiple tabs, video playback, etc.) for a monitored period, tracking temperature and performance. Compare results against a known-good device as a baseline.",
        },
        "application": {
            "type": "real_world_problem",
            "title": "Passed at Five Minutes, Failed at Fifty",
            "scenario": "A repaired Chromebook checked out fine during a quick 5-minute test: normal temperature, no fan noise, smooth performance. A full stress-test log covering 50 minutes of heavy use tells a different story: temperature climbs steadily every 10 minutes (68°F, 82°F, 95°F, 108°F, 122°F), fan noise increases starting around the 30-minute mark, and the device shuts down unexpectedly at the 47-minute mark.",
            "task": "Students interpret the stress-test log to identify roughly when a real student, using the device for a normal homework session, would have first noticed a problem, and propose one specific next repair step based on the pattern of rising temperature in the data.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "A stress test is most useful for catching:",
                 "choices": ["A. Cosmetic scratches", "B. Marginal problems that don't show up during light, normal use", "C. Software license issues only", "D. Nothing a normal check wouldn't catch"], "answer": "B"},
                {"type": "short_answer", "q": "Describe what a tech should monitor during a hardware stress test.", "sample_answer": "Temperature, fan noise, and performance under heavy load, compared against a known-good baseline device."},
            ],
        },
        "exit_ticket": {"prompt": "Why should a repaired device be stress tested before it's returned to a student, instead of just checked briefly?"},
        "slide_bullets": [
            "Stress test: deliberate, monitored heavy use",
            "Reveals marginal problems light use misses",
            "Watch: temperature, fan noise, performance under load",
            "Compare against a known-good baseline",
        ],
        "academic_vocab": {
            "word": "Verify",
            "definition": "To check that something is true, accurate, or working as expected.",
            "syllables": "VER-uh-fy",
            "morphology": "Latin verus (true) + -ficare (to make)",
            "example": "A stress test helps a tech verify that a repaired device will actually hold up under real classroom use, not just a quick check.",
        },
    },
    {
        "day": 70,
        "unit": 4,
        "lesson_in_unit": 16,
        "title": "Ticket #11: Solo",
        "objectives": [
            "I can describe what it means to apply review material to a real, unscripted problem.",
            "I can reflect on my own growth from Apprentice-level uncertainty toward independent competence.",
        ],
        "vocab": [
            {"word": "Practice Exam", "definition": "A timed, exam-style set of questions used to check readiness and identify weak spots.",
             "example": "Practice exams matter, but today's live-ticket day tests something a practice exam alone can't: Jordan working a real problem solo.",
             "syllables": "PRAK-tis eg-ZAM",
             "morphology": "Greek praktikos (fit for action, from prattein 'to do') + Latin examen (the tongue of a balance scale, a means of weighing accurately)."},
        ],
        "warm_up": "Think of the very first ticket you ever handled this semester. How would you handle it differently now?",
        "mini_lesson": [
            {"heading": "Setting Up Today's Reading", "body": "Today's installment is a graphic novel panel script marking a milestone: Jordan handling a genuinely hard ticket completely solo for the first time, during the same week as cert review. Notice how much of this semester's earlier lessons - intake, safety, networking, all of it - show up here at once, without anyone reminding Jordan to use them."},
            {"heading": "Live-Ticket Days During Cert Week", "body": "Mixing live-ticket work into certification review week is intentional. It proves whether review material actually transfers to messy, real situations, not just clean multiple-choice questions. That transfer is the real goal of every practice exam this phase."},
        ],
        "activity": {
            "title": "Read and Connect",
            "instructions": "Students read the panel script, then list every semester skill (from any phase) they can spot Jordan using during the solo ticket. Discuss: which of those skills came from a phase far earlier in the semester?",
        },
        "application": {
            "type": "case_study",
            "title": "A Different Solo Ticket",
            "scenario": "In a different classroom the same week, another teacher reports that handouts won't print, and the symptoms look identical to Jordan's story at first: the Chromebook shows no error, and the room's printer doesn't appear in the printer list. This time, though, the network settings check out fine - the Chromebook is correctly connected to the staff network the whole time. The actual issue turns out to be that the print job's file size is far larger than the printer's queue can accept.",
            "task": "In 2-3 sentences, students explain why this ticket looked similar to Ticket #11 on the surface but had a different root cause, and identify what they would check first, knowing the network is not the problem this time.",
        },
        "reading": {
            "type": "graphic_novel",
            "title": "Ticket #11: Solo",
            "body": "PANEL 1: A teacher waves Jordan over during a free period. Sam is across the room, deep in his own repair, not looking up.\nTEACHER: 'My Chromebook won't connect to the printer in my room, and I have handouts due in fifteen minutes.'\n\nPANEL 2: Jordan glances toward Sam, who's clearly busy, then back at the teacher.\nCAPTION: No Sam this time. Just Jordan.\nJORDAN: 'Okay - can you show me exactly what happens when you try to print?'\n\nPANEL 3: The teacher clicks print; nothing happens, no error message either.\nTEACHER: 'It just... does nothing. No error, no paper, nothing.'\nJORDAN: 'Got it. Let's check if the printer shows up as an option at all.'\n\nPANEL 4: Jordan checks the printer list on the Chromebook - the room's printer isn't listed, only a different printer down the hall.\nJORDAN: 'Your room printer isn't even showing up on this list. That's different from a jam or an error.'\n\nPANEL 5: Jordan thinks through the signal flow of the situation: device, network, printer, in that order.\nCAPTION: Device looks fine. Question is the network path to the printer.\nJORDAN: 'Can I check what network this Chromebook is on?'\n\nPANEL 6: Jordan finds the device is connected to a guest network instead of the main staff network.\nJORDAN: 'Found it - you're on the guest Wi-Fi, not the staff network. The printer's only visible from the staff network.'\n\nPANEL 7: Jordan switches the network, and the room's printer immediately appears on the list.\nTEACHER: 'Oh - that's it? I didn't even know there were two networks.'\nJORDAN: 'Happens more than you'd think. Try printing now.'\n\nPANEL 8: The handouts print successfully with two minutes to spare.\nTEACHER: 'You just saved my whole period. Thank you.'\n\nPANEL 9: Sam walks over afterward, having finished his own repair.\nSAM: 'Heard you had a solo ticket.'\nJORDAN: 'Networking, actually. Wrong Wi-Fi network the whole time.'\nSAM: 'Nice catch. Didn't even need me.'\n\nPANEL 10: Jordan writes up the ticket note, calm, clear, no jargon.\nCAPTION: Ticket #11: closed. No jargon left in the note. No Sam needed either.",
            "questions": [
                "What semester skills from earlier phases does Jordan use during this solo ticket? List at least three.",
                "What was the actual root cause of the printer problem?",
                "How is Jordan's ticket note at the end different from the jargon-filled draft back in Phase 1?",
                "What does this installment suggest about Jordan's growth from Apprentice level toward Technician or beyond?",
            ],
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What was the actual cause of the printer problem in the story?",
                 "choices": ["A. A broken printer", "B. The Chromebook was connected to the wrong (guest) network", "C. The teacher's account was locked", "D. A hardware failure in the Chromebook"], "answer": "B"},
                {"type": "multiple_choice", "q": "What does this installment mainly demonstrate about Jordan?",
                 "choices": ["A. Jordan still needs Sam for every ticket", "B. Jordan can now independently apply semester-long skills to a real, unscripted problem", "C. Jordan avoided the ticket entirely", "D. Jordan escalated the ticket to District IT"], "answer": "B"},
                {"type": "short_answer", "q": "Why is a live-ticket day during cert review week valuable, even though it isn't a written practice exam?", "sample_answer": "It proves that review material and semester-long skills actually transfer to a real, unpredictable problem, which is the true goal behind all the practice exams."},
            ],
        },
        "exit_ticket": {"prompt": "Name one skill from an earlier phase of this course that you saw Jordan use today, and explain how it applied."},
        "slide_bullets": [
            "Ticket #11: Jordan's first fully solo hard ticket",
            "Root cause: wrong Wi-Fi network, not a hardware issue",
            "Uses intake, networking, and plain-language notes all at once",
            "Live-ticket days test real transfer, not just multiple choice",
        ],
        "academic_vocab": {
            "word": "Articulate",
            "definition": "To express an idea clearly and precisely, in words.",
            "syllables": "ar-TIK-yuh-layt",
            "morphology": "Latin articulus (a small joint or part) + -ate (a verb-forming suffix) — to break speech into clear, distinct parts",
            "example": "Jordan had to articulate a clear ticket note explaining the guest-network fix, without any leftover jargon.",
        },
    },
    {
        "day": 71,
        "unit": 4,
        "lesson_in_unit": 17,
        "title": "Timed Practice Exam #2: Targeted Review",
        "objectives": [
            "I can complete a second timed practice exam focused on my identified weak areas.",
            "I can compare my results to Day 68 and measure specific growth.",
        ],
        "vocab": [
            {"word": "Certification Blueprint", "definition": "The official outline of exactly what topics and in what proportion a certification exam will test.",
             "example": "Today's targeted practice exam weights questions toward the blueprint domains where you struggled most on Day 68.",
             "syllables": "sur-tuh-fuh-KAY-shun BLOO-print",
             "morphology": "Latin certus (sure, settled) + -ficare (to make) + 'blueprint,' a compound from the blue-toned copies once made of architectural plans."},
        ],
        "warm_up": "Look back at your Day 68 results (or notes). Name the single domain you most need to improve today.",
        "mini_lesson": [
            {"heading": "From Diagnosis to Targeted Practice", "body": "Day 68's exam was diagnostic - it showed where the gaps are. Today's exam is targeted - weighted more heavily toward whatever domains gave you the most trouble, whether that's Core 1 hardware, Google IT system administration, or AVIXA signal flow."},
            {"heading": "Measuring Real Growth", "body": "The goal isn't a perfect score today - it's measurable improvement in your weakest areas compared to Day 68. Bring both result sheets to compare directly after the exam."},
        ],
        "activity": {
            "title": "Timed Practice Exam #2",
            "instructions": "Administer a second timed practice exam, weighted toward each student's or the class's collective weak domains from Day 68. Afterward, have students compare Day 68 and Day 71 results side by side and write one sentence naming specific improvement.",
        },
        "application": {
            "type": "simulation",
            "title": "Weighting the Second Exam",
            "scenario": "A student's Day 68 diagnostic results, broken down by domain, show: Hardware 90% correct, Networking 55% correct, System Administration 70% correct, and Signal Flow 80% correct. The teacher wants to build this student a 20-question targeted practice exam for Day 71 that puts more questions on the weakest domain and fewer on the strongest, roughly in proportion to how much improvement is needed.",
            "task": "Students calculate a reasonable number of questions to pull from each of the four domains for a 20-question targeted exam, giving the most questions to the weakest domain (Networking) and the fewest to the strongest (Hardware), and justify their math in 1-2 sentences.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What is the main purpose of comparing Day 68 and Day 71 results?",
                 "choices": ["A. To assign a final grade only", "B. To measure specific, targeted improvement in previously weak domains", "C. To see who finished fastest", "D. There is no purpose in comparing them"], "answer": "B"},
                {"type": "short_answer", "q": "Name one specific domain where you improved between Day 68 and Day 71, and what you did differently to cause that.", "sample_answer": "Answers vary; should name a specific domain and a specific study action taken between the two exams."},
            ],
        },
        "exit_ticket": {"prompt": "What is the one domain you'd still want more review time on, heading into next week's capstone phase?"},
        "slide_bullets": [
            "Timed Practice Exam #2: targeted at Day 68 weak spots",
            "Goal: measurable improvement, not a perfect score",
            "Compare Day 68 vs Day 71 results directly",
            "Name specific remaining gaps honestly",
        ],
        "academic_vocab": {
            "word": "Substantiate",
            "definition": "To back up a claim with solid evidence or proof.",
            "syllables": "sub-STAN-shee-ayt",
            "morphology": "Latin sub- (under) + stare (to stand) — to give something firm standing or substance",
            "example": "Comparing Day 68 and Day 71 scores let students substantiate their claim of improvement with real numbers.",
        },
    },
    {
        "day": 72,
        "unit": 4,
        "lesson_in_unit": 18,
        "title": "Certification Progress Check-In + Phase 4 Wrap",
        "objectives": [
            "I can honestly assess my certification progress against each blueprint.",
            "I can set a specific plan for continuing certification study beyond this phase.",
        ],
        "vocab": [
            {"word": "Certification Blueprint", "definition": "The official outline of exactly what topics and in what proportion a certification exam will test.",
             "example": "Today you'll check your own progress against all three blueprints from this phase.",
             "syllables": "sur-tuh-fuh-KAY-shun BLOO-print",
             "morphology": "Latin certus (sure, settled) + -ficare (to make) + 'blueprint,' a compound from the blue-toned copies once made of architectural plans."},
        ],
        "warm_up": "In one sentence, what surprised you most about yourself during this certification-focused phase?",
        "mini_lesson": [
            {"heading": "Certification Progress Is Not All-or-Nothing", "body": "Remember from the course syllabus: Certification Progress is 15% of your grade, and it's based on how far you get, not on finishing every certification in one semester. The bigger certs (AVIXA, CompTIA, Google IT Support) genuinely take longer than one semester of study - that's expected, not a failure."},
            {"heading": "Looking Ahead to Phase 5", "body": "Phase 5 shifts focus to your capstone project and career launch - resume, portfolio, mock interviews. The certification study habits you built this phase (targeted review, honest self-assessment, timed practice) will keep serving you whether you continue studying independently, through an internship, or by retaking this course."},
        ],
        "activity": {
            "title": "Certification Progress Log",
            "instructions": "Have students fill out a progress log for each of the three certification threads (Core 1, Google IT Support, AVIXA) plus the two shorter certs completed earlier (CareerSafe Employability, ACER Chromebook Repair): modules completed, practice exam trend, and next planned study step. Collect for Certification Progress grading.",
        },
        "application": {
            "type": "case_study",
            "title": "The Progress Log Doesn't Lie",
            "scenario": "A student's finished progress log shows: Core 1 modules 80% complete with an improving practice-exam trend; Google IT Support modules 40% complete with a flat practice-exam trend; AVIXA modules 20% complete with no recent practice attempted at all; CareerSafe Employability and ACER Chromebook Repair both fully complete from earlier in the course.",
            "task": "Using the log, students write a two-sentence honest assessment of this student's overall certification progress and recommend one specific certification the student should prioritize studying first going into next semester or break.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "According to the course grading policy, Certification Progress credit is based on:",
                 "choices": ["A. Finishing every certification completely within the semester", "B. How far a student gets: modules finished and practice-exam trend", "C. Only the AVIXA certification", "D. Attendance alone"], "answer": "B"},
                {"type": "short_answer", "q": "What is your specific plan for continuing certification study after this phase ends?", "sample_answer": "Answers vary; should name a specific certification and a specific next step, such as continuing modules independently, through an internship, or in a future course."},
            ],
        },
        "exit_ticket": {"prompt": "Which certification are you proudest of your progress on this phase, and why?"},
        "slide_bullets": [
            "Certification Progress: 15% of grade, based on progress not perfection",
            "Bigger certs (AVIXA, CompTIA, Google IT) take longer than one semester",
            "Log progress across all five certifications from this course",
            "Next up: Phase 5 capstone and career launch",
        ],
        "academic_vocab": {
            "word": "Reconcile",
            "definition": "To bring two things that seem to conflict into agreement with each other.",
            "syllables": "REK-un-syle",
            "morphology": "Latin re- (again) + conciliare (to bring together, unite)",
            "example": "Students had to reconcile their own sense of progress with what their certification progress log actually showed.",
        },
    },
]
