"""
Shared lesson metadata: bell ringers and 50-minute timing plans.
Imported by both warrior_prep_pptx.py and warrior_prep_pdf.py.
"""

BELL_RINGERS = {
    "1.1": {
        "type": "Launch",
        "title": "Brain Warm-Up",
        "prompt": "Write your answer: In the last 24 hours, name ONE moment when you had to stop yourself from doing something you wanted to do in order to do something you needed to do. What made it hard?",
        "share": "Pair-share (1 min) → cold-call 2 students",
        "connection": "Launches Unit 1 by surfacing a real experience of inhibitory control — the exact EF skill we name and define today.",
    },
    "1.2": {
        "type": "Review",
        "title": "EF Skill Quick-Sort",
        "prompt": "Without looking at your notes — name THREE executive functioning skills from last class. Then: rank them from easiest to hardest to use. Be ready to explain your ranking.",
        "share": "Thumbs up when ready → cold-call 1 student per skill",
        "connection": "Retrieves lesson 1.1 vocabulary. Ranking requires students to apply, not just recall — sets up today's prioritization work.",
    },
    "1.3": {
        "type": "Anticipation",
        "title": "Myth or Fact?",
        "prompt": "Agree or Disagree — write your answer AND your reason:\n'I can study while watching a show and still remember what I studied just as well as if I'd studied in silence.'",
        "share": "Show of hands Agree/Disagree → brief debate (don't confirm yet — the reading will)",
        "connection": "Creates productive cognitive conflict before the lesson on multitasking and working memory.",
    },
    "1.4": {
        "type": "Review",
        "title": "Unit 1 Vocabulary Lightning Round",
        "prompt": "Without your workbook: write the definition of EACH word in your own words.\n1. Executive functioning  2. Inhibitory control  3. Working memory  4. Cognitive flexibility",
        "share": "Partner check — compare definitions and agree on one shared version",
        "connection": "Final vocabulary consolidation before the SMART goal lesson — students will use all four terms in their goal-setting work.",
    },
    "2.1": {
        "type": "Launch",
        "title": "Career Assumption Check",
        "prompt": "Respond quickly — don't overthink:\nName one career you think you might be interested in someday. NOW: where does that career fit in school? What courses at Two Rivers connect to it?",
        "share": "Table share (1 min) → 3 volunteers share out",
        "connection": "Surfaces prior knowledge and reveals what students already understand (or misunderstand) about the connection between school and careers — frames Unit 2.",
    },
    "2.2": {
        "type": "Review",
        "title": "Career Fields Memory Map",
        "prompt": "In 2 minutes: from memory, list as many of the six Minnesota career fields as you can. Under each one, name at least ONE Two Rivers course or program that fits.",
        "share": "Compare with a partner — fill in anything you missed",
        "connection": "Retrieves lesson 2.1 content. Sets up today's focus on engineering/health pathways and the CAPS programs.",
    },
    "2.3": {
        "type": "Anticipation",
        "title": "What Does a Communicator Do?",
        "prompt": "Quick write: What job do you picture when you hear 'Arts, Communications, and Information Systems'? Do you think that field pays well? Do you think it's in demand? Explain your reasoning.",
        "share": "Pair-share → 2 volunteers",
        "connection": "Challenges assumptions about arts/communication careers before the lesson expands what students think is possible in those fields.",
    },
    "2.4": {
        "type": "Review",
        "title": "Two Rivers Pathway Recap",
        "prompt": "Draw a quick web/mind map from memory: put 'Two Rivers HS' in the center. Branch out to every pathway, program, or field we've studied so far. Add at least one course or career under each.",
        "share": "Compare maps with a partner — what's on theirs that's not on yours?",
        "connection": "Synthesizes all of Unit 2 before the final lesson. Gaps in the map show where students need the reading today.",
    },
    "3.1": {
        "type": "Launch",
        "title": "Reading Habits Honest Check",
        "prompt": "Be honest — no one is grading this:\nWhen you read something for school that you don't find interesting, what do you actually do? Check all that apply.\n[ ] Read carefully  [ ] Skim it  [ ] Read the first and last line of each paragraph  [ ] Ask someone what it says  [ ] Give up",
        "share": "Quick poll — hands for each option (normalize honesty, no shame)",
        "connection": "Surfaces reading habits without judgment — creates buy-in for today's lesson on active reading strategies.",
    },
    "3.2": {
        "type": "Review",
        "title": "Annotation Symbol Quick-Apply",
        "prompt": "Look at this sentence. Annotate it using your symbols from last class:\n'The students who scored highest on the final exam were the ones who had annotated their textbooks most heavily — not the ones who had read the most pages.'\nExplain what you marked and why.",
        "share": "Show your annotations to a partner — did you use the same symbols? Did you mark the same parts?",
        "connection": "Applies lesson 3.1 annotation skills immediately. The sentence content also previews today's lesson on writing stamina.",
    },
    "3.3": {
        "type": "Anticipation",
        "title": "How Do YOU Study?",
        "prompt": "Before you look at any notes — describe your exact study method for a big test:\nStep 1: ___________________________________________\nStep 2: ___________________________________________\nStep 3: ___________________________________________\nDo you think it works? How would you know?",
        "share": "Partner share — compare methods. Are they similar?",
        "connection": "Activates prior knowledge about study habits before today's lesson challenges students to evaluate those habits against research.",
    },
    "3.4": {
        "type": "Review",
        "title": "Study Strategy Ranking",
        "prompt": "From last class: put these strategies in order from MOST effective (1) to LEAST effective (5) according to the research:\n___ Re-reading\n___ Highlighting\n___ Retrieval practice\n___ Spaced repetition\n___ Interleaving",
        "share": "Compare rankings with a partner → class consensus",
        "connection": "Retrieves and ranks lesson 3.3 strategies. Sets up today's focus on building independent study advocacy.",
    },
    "4.1": {
        "type": "Launch",
        "title": "What Do You Actually Know About Graduation?",
        "prompt": "Without looking anything up — answer as specifically as you can:\n1. How many total credits do you need to graduate from Two Rivers? ___\n2. Name one course that is REQUIRED for every student: ___________________\n3. What is the difference between required courses and electives?",
        "share": "Table share → answers revealed after everyone commits",
        "connection": "Reveals what students know (and don't) about graduation before we map it out — creates urgency for careful planning.",
    },
    "4.2": {
        "type": "Review",
        "title": "Graduation Requirement Recall",
        "prompt": "From last class — fill in from memory:\nRequired English credits (9-12): ___   Required math: ___   Required science: ___\nOpen elective credits available: ___\nWarrior Seminar is worth ___ credits and is taken in grade ___",
        "share": "Check with your Academic Planning Guide — how close were you?",
        "connection": "Retrieves the graduation structure before students begin building their actual mock schedule today.",
    },
    "4.3": {
        "type": "Anticipation",
        "title": "Activity Assumption Check",
        "prompt": "Agree, Disagree, or It Depends — write a reason for each:\n1. 'Students who do extracurriculars have lower GPAs because they have less study time.'\nA / D / ID:  Reason: ________________________________\n2. 'It's better to try one activity deeply than three activities lightly.'\nA / D / ID:  Reason: ________________________________\n3. 'You should decide your activities before 9th grade starts.'\nA / D / ID:  Reason: ________________________________",
        "share": "Pair debate (1 min) — who changed their mind after hearing a partner?",
        "connection": "Surfaces assumptions about involvement before the reading and lesson challenge or confirm them.",
    },
    "4.4": {
        "type": "Review",
        "title": "Rapid-Fire: My 9th Grade Plan So Far",
        "prompt": "Quick-write in 2 minutes — answer all three:\n1. Name TWO courses you've decided to take in 9th grade:\n   ___________________________  ___________________________\n2. Name ONE activity you circled in the activities checklist: ___________________________\n3. One word that describes how you feel about starting 9th grade: ___________________________",
        "share": "Popcorn share — one word feelings around the room",
        "connection": "Reconnects to students' personal plans from Lessons 4.1-4.3. The 'one word' share surfaces anxiety early — today's time-map lesson directly addresses it.",
    },
    "5.1": {
        "type": "Launch",
        "title": "Grade vs. GPA — What's the Difference?",
        "prompt": "Without any help — explain the difference between a grade and a GPA:\n______________________________________________________\nIf a student gets a B in every class for one semester, what is their GPA? My best guess: ___\nExplain your reasoning:",
        "share": "Show of hands for different GPA guesses — don't confirm yet",
        "connection": "Surfaces misconceptions about GPA before the lesson and calculator activity.",
    },
    "5.2": {
        "type": "Review",
        "title": "GPA Impact Scenario",
        "prompt": "A student gets straight B's (3.0) in semester 1. In semester 2, they get one A and the rest B's. By how much does their GPA change? Show your work:\n\nThen: what ONE habit change would have the biggest effect on a student's GPA?",
        "share": "Calculate with a partner → share the habit",
        "connection": "Applies lesson 5.1 GPA math before today's lesson on the social-academic skills that protect GPA.",
    },
    "5.3": {
        "type": "Anticipation",
        "title": "If Registration Were TODAY",
        "prompt": "Without looking at anything — write the 7 courses you would register for if it were due today:\nP1: __________________  P2: __________________  P3: __________________\nP4: __________________  P5: __________________  P6: __________________  P7: __________________\nHow confident do you feel about these choices? (circle)  1 — 2 — 3 — 4 — 5",
        "share": "Compare with a partner — what's different? What did you forget?",
        "connection": "Creates urgency and reveals gaps before today's final schedule review and rationale lesson.",
    },
    "5.4": {
        "type": "Review",
        "title": "What I Still Want to Know",
        "prompt": "Think about everything we've covered in Warrior Prep this semester.\nWrite the ONE question about high school that you still haven't gotten a clear answer to. Make it specific and story-inviting — not a yes/no question:\n\nMy panel question:\n______________________________________________________\n______________________________________________________",
        "share": "Each student reads their question — class thumbs up if it's one they also want answered",
        "connection": "Directly generates today's panel question. The vote helps students see which questions are widely shared.",
    },
}

LESSON_TIMING = {
    "1.1": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 10, "activity": 10, "exit": 5},
    "1.2": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 8,  "activity": 12, "exit": 5},
    "1.3": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 10, "activity": 10, "exit": 5},
    "1.4": {"bell": 5, "title": 3, "read": 10, "qs": 6, "content": 8,  "activity": 13, "exit": 5},
    "2.1": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 8,  "activity": 12, "exit": 5},
    "2.2": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 10, "activity": 10, "exit": 5},
    "2.3": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 10, "activity": 10, "exit": 5},
    "2.4": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 8,  "activity": 12, "exit": 5},
    "3.1": {"bell": 5, "title": 3, "read": 11, "qs": 7, "content": 9,  "activity": 10, "exit": 5},
    "3.2": {"bell": 5, "title": 3, "read": 10, "qs": 6, "content": 8,  "activity": 13, "exit": 5},
    "3.3": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 10, "activity": 10, "exit": 5},
    "3.4": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 9,  "activity": 11, "exit": 5},
    "4.1": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 8,  "activity": 12, "exit": 5},
    "4.2": {"bell": 5, "title": 3, "read": 9,  "qs": 6, "content": 7,  "activity": 15, "exit": 5},
    "4.3": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 8,  "activity": 12, "exit": 5},
    "4.4": {"bell": 5, "title": 3, "read": 9,  "qs": 6, "content": 8,  "activity": 14, "exit": 5},
    "5.1": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 8,  "activity": 12, "exit": 5},
    "5.2": {"bell": 5, "title": 3, "read": 10, "qs": 7, "content": 10, "activity": 10, "exit": 5},
    "5.3": {"bell": 5, "title": 3, "read": 9,  "qs": 6, "content": 7,  "activity": 15, "exit": 5},
    "5.4": {"bell": 5, "title": 3, "read": 8,  "qs": 5, "content": 4,  "activity": 25, "exit": 5},
}
