"""
Warrior Prep — Curated YouTube video links per lesson.
Each entry has: title, channel, duration_est, description (what to watch for),
and url (YouTube search URL — always resolves, even if a video ID changes).

Teachers click the link during class. The search URL opens YouTube with
the best match for that topic already surfaced.
"""

YOUTUBE = {
    # ── Unit 1: Executive Functioning ────────────────────────────────────
    "1.1": {
        "title": "Building the Brain's Air Traffic Control System",
        "channel": "Harvard Center on the Developing Child",
        "duration": "2 min",
        "watch_for": "Notice how they describe the prefrontal cortex and what 'executive function' actually controls.",
        "url": "https://www.youtube.com/results?search_query=Building+the+Brain%27s+Air+Traffic+Control+System+Harvard",
        "alt_title": "Executive Function 101",
        "alt_channel": "Crash Course Study Skills",
        "alt_url": "https://www.youtube.com/results?search_query=crash+course+study+skills+executive+function",
    },
    "1.2": {
        "title": "The Eisenhower Matrix — How to Manage Your Tasks",
        "channel": "Sprouts",
        "duration": "4 min",
        "watch_for": "Pay attention to how they categorize tasks — which quadrant surprises you most?",
        "url": "https://www.youtube.com/results?search_query=Eisenhower+Matrix+explained+Sprouts",
        "alt_title": "How to Plan Your Week Effectively",
        "alt_channel": "Thomas Frank",
        "alt_url": "https://www.youtube.com/results?search_query=Thomas+Frank+how+to+plan+your+week+effectively",
    },
    "1.3": {
        "title": "Multitasking Is a Myth — Your Brain on Distraction",
        "channel": "National Geographic",
        "duration": "3 min",
        "watch_for": "Watch for the experiment showing what happens to brain activity during task-switching.",
        "url": "https://www.youtube.com/results?search_query=multitasking+myth+brain+neuroscience+national+geographic",
        "alt_title": "Deep Work — Do Hard Things",
        "alt_channel": "Cal Newport / TED",
        "alt_url": "https://www.youtube.com/results?search_query=cal+newport+deep+work+TEDx+focus",
    },
    "1.4": {
        "title": "Grit: The Power of Passion and Perseverance",
        "channel": "TED (Angela Duckworth)",
        "duration": "6 min",
        "watch_for": "What does Duckworth say is MORE important than talent? Do you agree?",
        "url": "https://www.youtube.com/results?search_query=Angela+Duckworth+grit+power+passion+perseverance+TED",
        "alt_title": "The Marshmallow Test — Self-Control",
        "alt_channel": "SciShow Psych",
        "alt_url": "https://www.youtube.com/results?search_query=marshmallow+test+self+control+science+explained",
    },

    # ── Unit 2: Career Pathways ───────────────────────────────────────────
    "2.1": {
        "title": "Minnesota Career Pathways — What's Your Direction?",
        "channel": "Minnesota Department of Education",
        "duration": "4 min",
        "watch_for": "Which of the six career fields do you hear described in a way you hadn't considered?",
        "url": "https://www.youtube.com/results?search_query=Minnesota+career+fields+clusters+pathways+MDE+students",
        "alt_title": "How to Choose a Career (That You'll Actually Love)",
        "alt_channel": "Big Think",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+choose+a+career+you+love+big+think",
    },
    "2.2": {
        "title": "A Day in the Life — Skilled Trades & Healthcare Careers",
        "channel": "CareerOneStop (U.S. Department of Labor)",
        "duration": "5 min",
        "watch_for": "What surprised you about what these workers actually do day-to-day?",
        "url": "https://www.youtube.com/results?search_query=CareerOneStop+skilled+trades+healthcare+day+in+the+life",
        "alt_title": "Why Trades Are the Best Kept Secret in America",
        "alt_channel": "Mike Rowe / TED",
        "alt_url": "https://www.youtube.com/results?search_query=Mike+Rowe+skilled+trades+TED+talk",
    },
    "2.3": {
        "title": "Careers in Tech, Arts, and Business — What Do They Pay?",
        "channel": "CareerOneStop (U.S. Department of Labor)",
        "duration": "4 min",
        "watch_for": "Pick one career from this video. Look up its median salary and write it down.",
        "url": "https://www.youtube.com/results?search_query=CareerOneStop+careers+arts+business+technology+salary",
        "alt_title": "Computer Science Is Changing Everything",
        "alt_channel": "Code.org",
        "alt_url": "https://www.youtube.com/results?search_query=code.org+computer+science+changing+everything",
    },
    "2.4": {
        "title": "Careers in Agriculture and Natural Resources",
        "channel": "CareerOneStop (U.S. Department of Labor)",
        "duration": "4 min",
        "watch_for": "What is one job in this field you'd never heard of before?",
        "url": "https://www.youtube.com/results?search_query=CareerOneStop+agriculture+natural+resources+careers",
        "alt_title": "Holland Code — What Career Fits Your Personality?",
        "alt_channel": "Career Center / TED-Ed",
        "alt_url": "https://www.youtube.com/results?search_query=Holland+code+RIASEC+career+personality+TED+Ed",
    },

    # ── Unit 3: Academic Preparation ─────────────────────────────────────
    "3.1": {
        "title": "How to Read Faster — Active Reading Strategies",
        "channel": "Thomas Frank",
        "duration": "8 min",
        "watch_for": "What is the one annotation habit he says makes the biggest difference?",
        "url": "https://www.youtube.com/results?search_query=Thomas+Frank+active+reading+strategies+annotation",
        "alt_title": "Your Brain on Reading — Neuroplasticity",
        "alt_channel": "SciShow",
        "alt_url": "https://www.youtube.com/results?search_query=brain+neuroplasticity+reading+learning+scishow",
    },
    "3.2": {
        "title": "How to Write a Great First Draft (Without Getting Stuck)",
        "channel": "Thomas Frank",
        "duration": "7 min",
        "watch_for": "What does he say is the #1 mistake writers make? Is that a mistake you make?",
        "url": "https://www.youtube.com/results?search_query=Thomas+Frank+how+to+write+first+draft+without+getting+stuck",
        "alt_title": "The Writing Process — Crash Course",
        "alt_channel": "Crash Course English",
        "alt_url": "https://www.youtube.com/results?search_query=crash+course+english+writing+process+drafting",
    },
    "3.3": {
        "title": "How to Study Effectively — The Science of Learning",
        "channel": "Sprouts",
        "duration": "6 min",
        "watch_for": "Which of the three strategies (retrieval, spacing, interleaving) do you already use?",
        "url": "https://www.youtube.com/results?search_query=how+to+study+effectively+retrieval+spacing+interleaving+Sprouts",
        "alt_title": "The Feynman Technique — Learn Anything Faster",
        "alt_channel": "Thomas Frank",
        "alt_url": "https://www.youtube.com/results?search_query=Feynman+technique+learn+anything+faster+Thomas+Frank",
    },
    "3.4": {
        "title": "How to Ask for Help (Without It Being Awkward)",
        "channel": "The Art of Improvement",
        "duration": "5 min",
        "watch_for": "What makes a 'good ask' different from a 'bad ask'? Take notes on his examples.",
        "url": "https://www.youtube.com/results?search_query=how+to+ask+for+help+effectively+self+advocacy+students",
        "alt_title": "Backward Planning — How to Never Miss a Deadline",
        "alt_channel": "Mike and Matty",
        "alt_url": "https://www.youtube.com/results?search_query=backward+planning+project+management+students+deadline",
    },

    # ── Unit 4: 9th Grade Year Plan ──────────────────────────────────────
    "4.1": {
        "title": "High School 101 — What You Need to Know Before 9th Grade",
        "channel": "College Board",
        "duration": "5 min",
        "watch_for": "Write down TWO things they mention that you hadn't thought about yet.",
        "url": "https://www.youtube.com/results?search_query=high+school+101+what+you+need+to+know+before+9th+grade",
        "alt_title": "How GPA Works — Explained for Students",
        "alt_channel": "WhatsUpDude",
        "alt_url": "https://www.youtube.com/results?search_query=how+GPA+works+weighted+unweighted+explained+high+school",
    },
    "4.2": {
        "title": "How to Build a High School Schedule You Won't Regret",
        "channel": "School Counseling Videos",
        "duration": "6 min",
        "watch_for": "What advice do they give about balancing challenging courses and free time?",
        "url": "https://www.youtube.com/results?search_query=how+to+build+high+school+schedule+course+selection+counselor",
        "alt_title": "Warrior Seminar — What Is It?",
        "alt_channel": "ISD 197 / Two Rivers",
        "alt_url": "https://www.youtube.com/results?search_query=ISD+197+Two+Rivers+High+School+Warrior+Seminar",
    },
    "4.3": {
        "title": "Why Join a Club or Sport in High School? The Research Says...",
        "channel": "College Prep Academy",
        "duration": "5 min",
        "watch_for": "What is the research finding that surprises students the most?",
        "url": "https://www.youtube.com/results?search_query=why+join+extracurricular+activities+high+school+research+benefits",
        "alt_title": "Student Athletes — How Do They Manage Time?",
        "alt_channel": "TED-Ed",
        "alt_url": "https://www.youtube.com/results?search_query=student+athlete+time+management+high+school+TED+Ed",
    },
    "4.4": {
        "title": "Sleep Is Your Superpower",
        "channel": "TED (Matt Walker)",
        "duration": "5 min",
        "watch_for": "What does Walker say happens to your memory when you sleep fewer than 7 hours?",
        "url": "https://www.youtube.com/results?search_query=Matthew+Walker+sleep+is+your+superpower+TED",
        "alt_title": "How to Manage Your Time — The Eisenhower Matrix (Review)",
        "alt_channel": "Sprouts",
        "alt_url": "https://www.youtube.com/results?search_query=time+management+high+school+student+daily+schedule+tips",
    },

    # ── Unit 5: Transition to High School ────────────────────────────────
    "5.1": {
        "title": "What Is a GPA? Weighted vs. Unweighted Explained",
        "channel": "Signet Education",
        "duration": "4 min",
        "watch_for": "After watching, can you explain the difference to a parent tonight?",
        "url": "https://www.youtube.com/results?search_query=weighted+vs+unweighted+GPA+explained+high+school+transcript",
        "alt_title": "How to Use Your School's Grade Portal",
        "alt_channel": "Common Sense Education",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+use+infinite+campus+student+portal+grades",
    },
    "5.2": {
        "title": "The 9th Grade Cliff — Why Freshman Year Matters Most",
        "channel": "AVID / Alliance for Excellent Education",
        "duration": "5 min",
        "watch_for": "What is the 'ninth grade cliff' and what are the warning signs?",
        "url": "https://www.youtube.com/results?search_query=ninth+grade+cliff+freshman+year+dropout+prevention+BARR",
        "alt_title": "What Is BARR? Building Assets, Reducing Risks",
        "alt_channel": "BARR Center",
        "alt_url": "https://www.youtube.com/results?search_query=BARR+Center+Building+Assets+Reducing+Risks+9th+grade",
    },
    "5.3": {
        "title": "How to Choose High School Classes — Tips from a Counselor",
        "channel": "College Prep Academy",
        "duration": "7 min",
        "watch_for": "What does the counselor say about alternates? Does it change how you're thinking about your choices?",
        "url": "https://www.youtube.com/results?search_query=how+to+choose+high+school+classes+course+registration+counselor+tips",
        "alt_title": "AP vs. Regular Classes — What's the Difference?",
        "alt_channel": "SupertutorTV",
        "alt_url": "https://www.youtube.com/results?search_query=AP+vs+regular+classes+high+school+which+should+you+take",
    },
    "5.4": {
        "title": "How to Ask Better Questions — The Art of Curiosity",
        "channel": "TED-Ed",
        "duration": "5 min",
        "watch_for": "What is the one question technique they say gets the most useful answers?",
        "url": "https://www.youtube.com/results?search_query=TED+Ed+how+to+ask+better+questions+curiosity+learning",
        "alt_title": "Active Listening — The Skill Nobody Teaches",
        "alt_channel": "Improvement Pill",
        "alt_url": "https://www.youtube.com/results?search_query=active+listening+skill+tips+improvement+pill",
    },
}
