UNIT_1_META = {
    "number": 1,
    "name": "Financial Psychology & Goal Setting",
    "essential_question": "What impacts my financial thinking?",
    "overview": "This unit looks at the mental and social forces that shape spending and saving decisions before any math is involved: personal bias, FOMO, peer pressure, and advertising. Students then build the counterbalancing tools, SMART goals and a spending plan, that let their own judgment drive financial decisions instead of autopilot reactions. The unit sets the psychological foundation the rest of the course builds on.",
    "vocabulary_bank": [
        {"word": "Financial Goals", "definition": "Specific, intentional outcomes you want your money to help you reach, sorted by timeframe (short-, medium-, or long-term), as opposed to a vague wish.",
         "syllables": "fi-NAN-shul GOHLZ",
         "morphology": "Latin financia (payment) + -ial (adjective-forming suffix) gives 'financial'; 'goal' traces to Middle English gol (a boundary or limit to be reached)."},
        {"word": "Financial Thinking", "definition": "The pattern of beliefs, habits, and automatic reactions a person brings to money decisions, shaped by family, culture, media, and personal experience.",
         "syllables": "fi-NAN-shul THING-king",
         "morphology": "Latin financia (payment) + -ial forms 'financial'; 'thinking' comes from Old English thencan (to think) + -ing (suffix forming a noun of process)."},
        {"word": "Personal Bias", "definition": "An automatic mental shortcut that leans a money decision one way without full analysis of the facts.",
         "syllables": "PER-suh-nul BY-us",
         "morphology": "Latin persona (individual character, originally 'mask') + -al (adjective suffix) forms 'personal'; 'bias' comes from Old French biais (a slant or oblique line)."},
        {"word": "FOMO", "definition": "Fear of Missing Out; the anxious feeling that everyone else is having an experience or owning something you are not, often fueled by social media.",
         "syllables": "FOH-moh (said as one word)",
         "morphology": "Acronym: F = Fear, O = Of, M = Missing, O = Out."},
        {"word": "Peer Pressure", "definition": "A direct or indirect push from people around you to spend, save, or think about money a certain way.",
         "syllables": "PEER PRESH-er",
         "morphology": "'Peer' comes from Latin par (equal); 'pressure' comes from Latin pressura (the act of pressing), from premere (to press)."},
        {"word": "S.M.A.R.T. Goals", "definition": "A goal-setting framework requiring a goal to be Specific, Measurable, Achievable, Relevant, and Time-bound.",
         "syllables": "S-M-A-R-T (each letter said aloud) GOHLZ",
         "morphology": "Acronym: S = Specific, M = Measurable, A = Achievable, R = Relevant, T = Time-bound."},
        {"word": "Advertising Influence", "definition": "The effect that marketing, sponsored content, and promotional messaging has on a person's wants and decisions, often without them noticing.",
         "syllables": "AD-ver-ty-zing IN-floo-ents",
         "morphology": "'Advertising' comes from Latin advertere (to turn toward), ad- (toward) + vertere (to turn); 'influence' comes from Latin influere (to flow into), in- (into) + fluere (to flow)."},
        {"word": "Source Information/Credibility", "definition": "The practice of judging whether information about money or a product actually deserves trust, based on who created it and what they gain.",
         "syllables": "SORSS in-for-MAY-shun / kred-uh-BIL-uh-tee",
         "morphology": "'Source' comes from Latin surgere (to rise up); 'credibility' comes from Latin credere (to believe) + -ibilis (able to be) + -ity (noun-forming suffix)."},
        {"word": "Impulse Buying", "definition": "Making a purchase with little or no planning, usually driven by an in-the-moment feeling rather than a spending plan or goal.",
         "syllables": "IM-puls BY-ing",
         "morphology": "'Impulse' comes from Latin impellere (to drive or push against), im- (against) + pellere (to drive); 'buying' comes from Old English bycgan (to buy) + -ing."},
        {"word": "Spending Plan", "definition": "A plan that lines up income against outgoing expenses by category (needs, wants, savings) so spending is decided on purpose rather than discovered after the fact.",
         "syllables": "SPEN-ding PLAN",
         "morphology": "'Spending' comes from Old English spendan (to spend), borrowed from Latin expendere (to weigh out, pay out); 'plan' comes from Latin planus (flat, level ground)."},
    ],
    "unit_assessment": {
        "title": "Unit 1 Assessment: Financial Psychology & Goal Setting",
        "questions": [
            {"type": "multiple_choice", "q": "Which of the following is the best example of a S.M.A.R.T. goal?",
             "choices": ["A. I want to be better with money.",
                         "B. I will save $40 a month for five months to reach $200 for a laptop by winter break.",
                         "C. Saving money is important to me.",
                         "D. I should probably start saving at some point."],
             "answer": "B"},
            {"type": "multiple_choice", "q": "Personal bias in a money decision is best described as:",
             "choices": ["A. A fully researched, rational decision",
                         "B. An automatic mental shortcut that leans a decision without full analysis",
                         "C. A decision that is always wrong",
                         "D. A formal written financial plan"],
             "answer": "B"},
            {"type": "multiple_choice", "q": "FOMO most directly refers to:",
             "choices": ["A. A type of spending plan",
                         "B. The anxious feeling of missing out on an experience or item others seem to have",
                         "C. A government financial aid form",
                         "D. A category on a pay stub"],
             "answer": "B"},
            {"type": "multiple_choice", "q": "Which scenario best shows INDIRECT peer pressure, as opposed to direct peer pressure?",
             "choices": ["A. A friend directly asks to borrow ten dollars",
                         "B. A student feels they need the same shoes as their friend group even though no one has said anything",
                         "C. A store runs a countdown sale",
                         "D. A student writes a S.M.A.R.T. goal"],
             "answer": "B"},
            {"type": "multiple_choice", "q": "An ad that features someone who looks like a relatable peer, rather than a distant celebrity, is using which technique described in the Unit 1 reading?",
             "choices": ["A. Source credibility",
                         "B. Social proof",
                         "C. A spending plan",
                         "D. A S.M.A.R.T. goal"],
             "answer": "B"},
            {"type": "multiple_choice", "q": "Before trusting a financial claim from an online source, the unit suggests asking all of the following EXCEPT:",
             "choices": ["A. Who wrote this?",
                         "B. What do they gain if I believe it?",
                         "C. Is there evidence anywhere else with no stake in my answer?",
                         "D. Does it sound confident and use expert language?"],
             "answer": "D"},
            {"type": "short_answer", "q": "Explain the difference between a need and a want, and explain why a spending plan is more useful when it is connected to a specific financial goal.",
             "sample_answer": "A need is required to function, like transportation to a job, while a want is enjoyable but not required, like eating out. A spending plan connected to a goal gives leftover money after needs and reasonable wants a clear purpose, turning the plan into the mechanism that actually reaches the goal instead of just a list of numbers."},
            {"type": "short_answer", "q": "Describe a realistic scenario in which personal bias, FOMO, peer pressure, and advertising influence combine to produce an impulse buy. Name each force as it appears.",
             "sample_answer": "Example: a student sees a friend's social media post about new shoes (FOMO), feels like everyone in their friend group already has them (peer pressure), remembers a countdown sale ad that made the deal feel urgent (advertising influence), and tells themselves they deserve it after a rough week (personal bias, specifically reward bias), leading to an impulse buy with no pause to check a spending plan."},
            {"type": "short_answer", "q": "What is financial thinking, and name two specific things that shape a person's financial thinking according to this unit.",
             "sample_answer": "Financial thinking is the pattern of beliefs, habits, and automatic reactions a person brings to money decisions. It is shaped by things like family money habits, culture and community norms, past personal experiences with money, and comparison to peers or influencers on social media."},
        ],
    },
    "days": [1, 10],
}

UNIT_1_LESSONS = [
    {
        "day": 1,
        "unit": 1,
        "lesson_in_unit": 1,
        "title": "What Shapes the Way We Think About Money?",
        "objectives": [
            "I can explain what financial thinking means and identify factors that shape it.",
            "I can describe why financial goals matter and give examples of short-, medium-, and long-term goals.",
        ],
        "vocab": [
            {"word": "Financial Thinking", "definition": "The pattern of beliefs, habits, and automatic reactions a person brings to money decisions, shaped by family, culture, media, and personal experience.",
             "example": "Growing up watching a parent stress over every receipt is part of what shapes someone's financial thinking.",
             "syllables": "fi-NAN-shul THING-king",
             "morphology": "Latin financia (payment) + -ial forms 'financial'; 'thinking' comes from Old English thencan (to think) + -ing (suffix forming a noun of process)."},
            {"word": "Financial Goals", "definition": "Specific, intentional outcomes you want your money to help you reach, as opposed to a vague wish.",
             "example": "Saving $600 for a car down payment by June is a financial goal; wanting to have more money someday is not.",
             "syllables": "fi-NAN-shul GOHLZ",
             "morphology": "Latin financia (payment) + -ial (adjective-forming suffix) gives 'financial'; 'goal' traces to Middle English gol (a boundary or limit to be reached)."},
        ],
        "warm_up": "On a sticky note, write down one thing (a person, an experience, an ad, a habit) that has shaped how you think about spending or saving money. Be ready to share with a partner.",
        "mini_lesson": [
            {"heading": "Why This Course Starts With Psychology, Not Math",
             "body": "Most personal finance classes start with math: budgets, interest rates, spreadsheets. This one starts somewhere else, with how you think. Research on why people struggle with money keeps landing on the same finding: most money problems aren't caused by not knowing enough math. They're caused by decisions made under stress, habit, pressure, or emotion. You can know exactly how compound interest works and still make a purchase five minutes later that has nothing to do with math. Before this course gets into spending plans, credit, and taxes, you're going to spend two weeks looking at the thinking patterns that drive every one of those decisions."},
            {"heading": "What Is Financial Thinking?",
             "body": "Financial thinking is the pattern of beliefs, habits, and automatic reactions you bring to any decision involving money. It's shaped by what you watched your family do growing up, what your friend group treats as normal, what ads and social media tell you is worth having, and what's happened to you personally, like a time you got burned by a bad purchase or felt proud of something you saved for. Nobody starts from zero. You already have financial thinking, whether or not you've ever named it. This unit is about noticing it, not judging it, so you can decide which parts are actually serving you."},
            {"heading": "Financial Goals: The Destination",
             "body": "A financial goal is a specific outcome you want your money to help you reach, not just a vague wish. 'I want more money' is a wish. 'I want to save $600 for a car down payment by June' is a goal. Financial goals usually fall into three time frames: short-term (something you want within a few months, like concert tickets), medium-term (one to three years, like a car or a laptop for college), and long-term (three or more years out, like paying for a certification program or a degree). Naming the timeframe matters because it changes how you save for it and how much risk makes sense."},
        ],
        "activity": {
            "title": "Banzai \"What's Next for Me?\" Reflection",
            "instructions": "Have students log in to the Banzai \"What's Next for Me?\" reflection tool (or use the paper version if devices aren't available) and complete the goal-identification section, naming one short-term and one long-term financial goal. Give them eight to ten minutes to work individually, then pair students up to share one goal and one reason it matters to them. Close by cold-calling two or three pairs to share out with the whole class.",
        },
        "reading": None,
        "application": {
            "type": "real_world_problem",
            "title": "The Two Hundred Dollar Question",
            "scenario": "Marcus just got $200 in birthday money from his grandparents. He already has $40 saved toward a laptop he wants for his tech certificate program next year, which costs $250 total, and he's hoping to have it by the start of the school year, five months from now. This morning he also saw an ad for a limited-edition controller, $85, and two friends in his group chat already ordered one. Marcus feels a pull to buy it right now, before he even thinks about the laptop money. He has a part-time job that lets him save about $15 a week if he's disciplined about it. He hasn't decided anything yet, he's just sitting with his birthday money and the controller ad open in another tab.",
            "task": "Have students calculate whether Marcus can still reach his $250 laptop goal within five months if he puts $150 of his birthday money toward it now and keeps saving $15 a week, versus what happens to the timeline if he spends $85 on the controller first. Then have them classify the laptop goal by timeframe (short-, medium-, or long-term) and name one specific factor from today's warm-up categories (family habit, ad, social pressure, past experience) that seems to be shaping Marcus's pull toward the controller.",
        },
        "academic_vocab": {
            "word": "Categorize",
            "definition": "To sort things into groups based on shared characteristics.",
            "syllables": "CAT-uh-guh-rize",
            "morphology": "Greek kategoria (accusation, statement) + English -ize (verb-forming suffix meaning 'to make or do')",
            "example": "Today you'll categorize your own financial goals as short-term, medium-term, or long-term based on how far away they are.",
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which of the following is the best example of a financial goal, rather than a wish?",
                 "choices": ["A. I hope I have money someday.",
                             "B. I want to save $500 for a laptop by December.",
                             "C. I wish I were better with money.",
                             "D. Money would make things easier."],
                 "answer": "B"},
                {"type": "multiple_choice", "q": "Saving $40 a month for eight months to buy a gaming console is best described as a ___ goal.",
                 "choices": ["A. short-term", "B. medium-term", "C. long-term", "D. not a real goal"],
                 "answer": "A"},
                {"type": "short_answer", "q": "Explain why \"I want to be good with money\" is not yet a financial goal, and rewrite it as one that is.",
                 "sample_answer": "It's not specific or measurable, so there's no way to know if you've reached it. A real version might be: I want to save $300 in my checking account by the end of the semester."},
                {"type": "multiple_choice", "q": "Which of the following most shapes a person's financial thinking, according to today's lesson?",
                 "choices": ["A. Only their math grades", "B. Family habits, culture, media, and personal experience",
                             "C. Their zodiac sign", "D. The current stock market"],
                 "answer": "B"},
            ],
        },
        "exit_ticket": {
            "prompt": "Name one long-term financial goal you have, and name one factor from today's warm-up (family habit, ad, social pressure, past experience) that might make it harder to reach.",
        },
        "slide_bullets": [
            "Today's Big Question: What impacts my financial thinking?",
            "Most money mistakes come from thinking patterns, not missing math skills",
            "Financial thinking = the beliefs and habits you bring to money decisions",
            "Financial goal = a specific outcome, not a vague wish",
            "Three timeframes: short-term, medium-term, long-term",
            "Activity: Banzai \"What's Next for Me?\" reflection",
            "Exit ticket: name one long-term goal + one factor that could get in its way",
        ],
    },
    {
        "day": 2,
        "unit": 1,
        "lesson_in_unit": 2,
        "title": "Whose Voice Is In Your Head When You Spend?",
        "objectives": [
            "I can define personal bias and explain how it affects money decisions.",
            "I can identify examples of bias in my own financial thinking.",
        ],
        "vocab": [
            {"word": "Personal Bias", "definition": "An automatic mental shortcut that leans a money decision one way without full analysis of the facts.",
             "example": "Buying a jacket because three friends already have one, without checking if you actually need it, is personal bias at work.",
             "syllables": "PER-suh-nul BY-us",
             "morphology": "Latin persona (individual character, originally 'mask') + -al (adjective suffix) forms 'personal'; 'bias' comes from Old French biais (a slant or oblique line)."},
        ],
        "warm_up": "Would you rather find $20 or avoid losing $20? Write your answer and why. There's no wrong answer, we're studying the reaction, not judging it.",
        "mini_lesson": [
            {"heading": "What Is Personal Bias?",
             "body": "A bias is a leaning toward one way of seeing or deciding something, often without realizing it's happening. Personal bias in money decisions means your brain has a built-in shortcut that affects how you spend, save, or think about money, separate from the actual facts of the situation. Bias isn't the same as being wrong on purpose. It's automatic. You can be a smart, careful person and still have money biases running in the background, because biases are less about intelligence and more about mental shortcuts your brain uses to make fast decisions in a world with too much information to fully weigh every time."},
            {"heading": "Where Bias Comes From",
             "body": "Personal bias about money usually traces back to a few sources. Family habits: if you grew up watching a parent stress about every purchase, or never discuss money at all, you likely absorbed an attitude before you ever earned a paycheck. Culture and community: different communities treat saving, debt, and spending on family differently, and none of that is automatically right or wrong. Past experience: one bad experience, like a purchase you regretted, can create a bias that lingers for years. Social comparison: seeing what peers or influencers have creates a constant, often invisible, reference point for what 'normal' spending looks like."},
            {"heading": "Common Money Biases Teens Have",
             "body": "A few biases show up often at your age. Optimism bias sounds like 'I'll figure out the money later' before a purchase, without an actual plan. Comparison bias sounds like 'everyone else already has this,' whether or not that's actually true. Reward bias sounds like 'I've had a rough week, I deserve this,' turning a purchase into an emotional fix. Present bias means favoring a smaller reward right now over a bigger reward later, like spending ten dollars today over saving toward something worth much more next year. None of these make someone bad with money. They just mean the brain is doing what brains do: taking shortcuts."},
        ],
        "activity": {
            "title": "Bias Spotting Gallery Walk",
            "instructions": "Post four or five scenario cards around the room, each describing a money decision (buying concert tickets on a credit card because it'll work out, skipping a savings app because a friend called it boring, buying a jacket because three people at school have the same one). In small groups, have students rotate to each card and write down which bias from today's lesson is most likely at play and why. Regroup as a class to compare answers and discuss any disagreements.",
        },
        "reading": None,
        "application": {
            "type": "case_study",
            "title": "Jordan's Sneaker Decision",
            "scenario": "Jordan just finished a brutal week: two exams, a closing shift that ran long, and an argument with a sibling. Scrolling through their phone before bed, Jordan sees that three people in their friend group have posted the same pair of limited-release sneakers, $140, over the last two days. Jordan doesn't need new shoes; their current pair has maybe a few months of wear left in them. But Jordan keeps thinking, 'I've had such a rough week, I deserve something good,' and also, 'everyone already has these, I'm going to be the only one who doesn't.' Jordan has $160 in their account, all of it earmarked for a car insurance payment due in ten days. There's no discussion with anyone yet, just Jordan, the shoes on screen, and a thumb hovering over the buy button at 11:40 p.m.",
            "task": "Have students identify which specific bias (or biases) from today's lesson are showing up in Jordan's thinking, quoting the exact line of internal reasoning that reveals each one, then write two sentences of advice Jordan's future self might give before that thumb taps buy.",
        },
        "academic_vocab": {
            "word": "Analyze",
            "definition": "To break something down into its parts in order to understand it more fully.",
            "syllables": "AN-uh-lyze",
            "morphology": "Greek roots: ana- (up, throughout) + lyein (to loosen)",
            "example": "Today you'll analyze your own past spending decisions to figure out which biases were really driving them.",
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "A student buys a new phone case because two friends already have it, even though their old one works fine. Which bias is most at play?",
                 "choices": ["A. Optimism bias", "B. Comparison bias", "C. Present bias", "D. No bias, this is a rational decision"],
                 "answer": "B"},
                {"type": "multiple_choice", "q": "Personal bias in financial decisions is best defined as:",
                 "choices": ["A. A decision made with full information", "B. An automatic mental shortcut that leans a decision without full analysis",
                             "C. A decision that is always financially wrong", "D. A formal financial plan"],
                 "answer": "B"},
                {"type": "short_answer", "q": "Describe one source of financial bias in your own life (family, culture, past experience, or comparison to peers) and one example of how it has shown up in a real decision you made.",
                 "sample_answer": "Answers vary; should name a specific source and connect it to a specific past spending or saving decision."},
                {"type": "multiple_choice", "q": "Which statement about bias is most accurate?",
                 "choices": ["A. Only people who are bad with money have bias", "B. Bias means someone is intentionally being irrational",
                             "C. Bias is an automatic shortcut that even careful, smart people have", "D. Bias only affects large purchases"],
                 "answer": "C"},
            ],
        },
        "exit_ticket": {
            "prompt": "Describe one money bias from today's lesson (optimism, comparison, reward, or present bias) that you recognize in yourself, using a real or realistic example.",
        },
        "slide_bullets": [
            "Today's focus: Personal Bias",
            "A bias is an automatic mental shortcut, not a moral failing",
            "Sources of bias: family habits, culture, past experience, social comparison",
            "Four common teen money biases: optimism, comparison, reward, present",
            "Smart, careful people still have bias, it's how brains work",
            "Activity: Bias Spotting Gallery Walk",
            "Exit ticket: name a bias you recognize in yourself",
        ],
    },
    {
        "day": 3,
        "unit": 1,
        "lesson_in_unit": 3,
        "title": "Reading Day: The Shoes",
        "objectives": [
            "I can identify examples of financial bias and FOMO in a realistic scenario.",
            "I can explain how defensiveness can be a signal that bias or FOMO is at play.",
        ],
        "vocab": [
            {"word": "FOMO", "definition": "Fear of Missing Out; the anxious feeling that everyone else is having an experience or owning something you are not, often fueled by social media.",
             "example": "Maya bought the shoes minutes after seeing a friend's post about the same pair, a classic sign of FOMO.",
             "syllables": "FOH-moh (said as one word)",
             "morphology": "Acronym: F = Fear, O = Of, M = Missing, O = Out."},
        ],
        "warm_up": "Think of a time you bought something because \"everyone\" had one or was doing it. How did you feel right before you bought it? How did you feel a week later?",
        "mini_lesson": [
            {"heading": "What Is FOMO?",
             "body": "FOMO stands for Fear of Missing Out: the anxious feeling that everyone else is having an experience, owning something, or moving forward in a way you aren't. FOMO is often triggered by social media, where you see a curated highlight reel of other people's purchases and experiences without seeing their full financial picture, like debt, buyer's remorse, or a birthday gift that paid for it. FOMO turns a want into something that feels urgent and emotional, which makes it harder to pause and check whether a purchase actually fits your goals or your spending plan."},
            {"heading": "Reading the Warning Signs of FOMO",
             "body": "FOMO usually shows up with a few warning signs: a fast decision made within minutes of seeing something online, a feeling of dread or urgency rather than excitement about the purchase, and defensiveness if someone questions the decision. That last one matters. Getting defensive fast when someone asks a reasonable question about a purchase is often a sign that some part of you already suspects the decision wasn't fully thought through. Today's reading follows a character noticing exactly that in herself."},
        ],
        "activity": {
            "title": "Reading Circle: The Shoes",
            "instructions": "Read \"The Shoes\" as a class, either aloud with students following along or silently first, then aloud for key lines. In groups of three, have students discuss the comprehension questions that follow the reading, then return to a whole-class discussion connecting Maya's reaction to yesterday's bias lesson.",
        },
        "reading": {
            "type": "realistic_fiction",
            "title": "The Shoes",
            "body": "Maya Chen had exactly fourteen minutes before her shift at Grounded Coffee, which was just enough time to duck into Sole Provider and buy the shoes she'd been staring at online for a week.\n\nShe was still holding the box when Priya got home.\n\n\"Please tell me those aren't the ones from your wishlist,\" Priya said, dropping her backpack by the door.\n\n\"They were forty percent off.\" Maya set the box on the counter like that settled it.\n\n\"For a hundred and ten dollars.\"\n\n\"Which is forty percent off a hundred and eighty-five.\" Maya heard how fast the number came out and didn't love it.\n\nPriya pulled a chair out and sat, which Maya recognized as her sister's we're-doing-this-now posture. \"Did you need them, or did you see Jenna post hers and panic a little?\"\n\n\"I don't panic about shoes.\" Maya crossed her arms. \"I saved for these. It's not like I put it on a credit card.\"\n\n\"I didn't say you didn't save. I asked why today. You've been talking about the tech certificate program for months and you still haven't opened that FAFSA worksheet Mr. Alvarez gave us.\"\n\n\"That's not related.\"\n\n\"It's a hundred and ten dollars related.\" Priya's voice wasn't sharp, just steady, which somehow made it worse. \"I bought a bag two years ago because everyone in my dorm had one. Wore it four times. I'm not saying don't ever buy something you want. I'm saying notice when 'I want this' turns into 'I need this right now or I'll die.'\"\n\nMaya opened her mouth to argue and then didn't, because she was picturing Jenna's post from that morning, the shoes, the little gold check-mark sticker, and how her stomach had dropped like she was already behind on something she hadn't known was a race.\n\n\"I wasn't going to die,\" she said instead, quieter.\n\n\"No,\" Priya agreed. \"You were going to have great shoes and a FAFSA worksheet still sitting in your bag.\"\n\nMaya looked at the box. The shoes were fine. She still liked them. But she couldn't tell anymore how much of buying them today, right now, forty minutes after seeing Jenna's post, had actually been her decision.\n\n\"I'm not returning them,\" she said.\n\n\"Didn't ask you to.\" Priya stood up and squeezed her shoulder on the way to the kitchen. \"Just open the worksheet tonight. Both things can be true.\"\n\nMaya sat down next to the shoe box and, for the first time all day, actually felt a little annoyed at herself instead of at her sister.",
            "questions": [
                "What detail in the reading suggests Maya's purchase may have been influenced by FOMO?",
                "Why does Priya bring up her own old bag purchase? What is she trying to teach Maya?",
                "How does Maya initially respond when Priya questions the purchase, and what does that reaction suggest about bias?",
                "What does the ending suggest Maya is starting to realize about her own decision?",
                "Priya says both things can be true: liking the shoes and having avoided the FAFSA worksheet. What does she mean by that?",
            ],
        },
        "application": {
            "type": "simulation",
            "title": "The Fifteen-Minute Sale",
            "scenario": "A flash-sale banner pops up on a student's phone: \"2 items left, sale ends in 15 minutes.\" The item is a $65 hoodie the student has looked at twice before but never bought. Two of their followers already posted photos wearing it this week.",
            "task": "In pairs, have students name at least two FOMO warning signs from today's mini-lesson (fast decision, dread/urgency instead of excitement, defensiveness) present in this fifteen-minute-sale setup, then decide together whether the pull to buy right now is real need or FOMO, and justify their answer in one sentence each.",
        },
        "academic_vocab": {
            "word": "Infer",
            "definition": "To figure out something not directly stated, using evidence and reasoning.",
            "syllables": "in-FUR",
            "morphology": "Latin in- (into) + ferre (to carry, to bring)",
            "example": "Even though the text never says the word 'FOMO,' you can infer that Maya is feeling it from how fast she bought the shoes after seeing Jenna's post.",
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What detail in the reading suggests Maya's purchase may have been driven by FOMO?",
                 "choices": ["A. She had saved money in advance", "B. She bought the shoes shortly after seeing a friend's post about the same item",
                             "C. Priya bought a similar bag once", "D. The shoes were on sale"],
                 "answer": "B"},
                {"type": "multiple_choice", "q": "How does Maya initially respond when Priya questions the purchase?",
                 "choices": ["A. She thanks Priya for the feedback", "B. She gets defensive and lists reasons the purchase was justified",
                             "C. She agrees immediately", "D. She returns the shoes right away"],
                 "answer": "B"},
                {"type": "short_answer", "q": "Explain why getting defensive quickly, like Maya does, can actually be a clue that bias or FOMO is involved in a decision.",
                 "sample_answer": "Quick defensiveness can be a sign that part of the person already suspects the decision wasn't fully thought through, so they rush to justify it before really examining it."},
                {"type": "multiple_choice", "q": "FOMO is best defined as:",
                 "choices": ["A. A financial goal", "B. The anxious feeling of missing out on what others are experiencing or buying",
                             "C. A type of spending plan", "D. A form of advertising"],
                 "answer": "B"},
            ],
        },
        "exit_ticket": {
            "prompt": "Describe a moment (from the reading or your own life) where FOMO, rather than an actual need, drove a spending decision.",
        },
        "slide_bullets": [
            "Today's focus: FOMO (Fear of Missing Out)",
            "FOMO turns a want into something that feels urgent and emotional",
            "Warning signs: fast decisions, dread instead of excitement, defensiveness",
            "Reading: \"The Shoes\", installment 1 of \"The Fund\"",
            "Meet Maya Chen and Priya Chen",
            "Discussion: what was really driving Maya's purchase?",
            "Exit ticket: a time FOMO drove a decision, not real need",
        ],
    },
    {
        "day": 4,
        "unit": 1,
        "lesson_in_unit": 4,
        "title": "Peer Pressure and the Price Tag",
        "objectives": [
            "I can define peer pressure in a financial context and distinguish it from FOMO.",
            "I can practice a strategy for responding to financial peer pressure.",
        ],
        "vocab": [
            {"word": "Peer Pressure", "definition": "A direct or indirect push from people around you to spend, save, or think about money a certain way.",
             "example": "Feeling like you have to chip in for an expensive group gift just because everyone else already agreed to is peer pressure.",
             "syllables": "PEER PRESH-er",
             "morphology": "'Peer' comes from Latin par (equal); 'pressure' comes from Latin pressura (the act of pressing), from premere (to press)."},
        ],
        "warm_up": "Think of a time a friend directly asked you to spend money you hadn't planned to spend (splitting a bill, chipping in for something). What did you do, and how did it feel in the moment?",
        "mini_lesson": [
            {"heading": "What Is Peer Pressure, Financially?",
             "body": "Peer pressure is the direct or indirect push from people around you to think, act, or spend a certain way. Financially, it can be direct, like a friend saying \"come on, just split the bigger Uber, it's not that much,\" or indirect, like feeling like you have to keep pace with what a friend group spends on food, clothes, or gifts without anyone saying a word out loud. Indirect peer pressure is often harder to notice than direct pressure because no one is technically asking you to do anything. The expectation is just in the air."},
            {"heading": "Peer Pressure vs. FOMO",
             "body": "Peer pressure and FOMO are related but not identical. FOMO is mostly internal: an anxious feeling that you're missing out, even if no one around you is pushing you toward anything. Peer pressure involves other people, directly or indirectly, nudging your decision. In real life they often show up together, like feeling FOMO about a group trip while a friend is also directly asking you to commit before you've checked your budget. Naming which one is happening helps you pick the right tool: a pause for FOMO, a scripted response for peer pressure."},
            {"heading": "Having a Script Ready",
             "body": "One of the most effective tools against peer pressure is deciding your response before you're in the moment, not during it. A calm, prepared line, like \"I'm going to sit this one out, but have fun,\" is much easier to say than one you're inventing on the spot while everyone's looking at you. Athletes call this having a plan before the pressure hits. The same idea works for money: decide your line in advance, and it stops being a hard decision every single time it comes up."},
        ],
        "activity": {
            "title": "Say This, Not That",
            "instructions": "In pairs, give students two or three peer-pressure scenario cards (splitting an expensive group order, chipping in for a gift beyond their budget, being asked to buy concert tickets they can't afford). Have each pair write a short, realistic response script for one scenario, then perform it briefly for another pair. Debrief as a class on which scripts felt natural versus stiff.",
        },
        "reading": None,
        "application": {
            "type": "realistic_fiction",
            "title": "The Group Chat",
            "scenario": "A'Liyah's phone buzzes six times in a row. The group chat for her cousin's graduation party has landed on a plan: everyone chips in $35 for a shared gift, a nice speaker, plus another $15 each for a group photo package from the venue. A'Liyah does the math fast: fifty dollars she hadn't planned on spending this week, on top of gas money she already owes her mom. Two people have already sent the thumbs-up emoji. A third writes, \"assuming everyone's in, lol,\" and A'Liyah can feel the shape of the moment closing in before she's even decided anything. No one has asked her directly yet. It's just sitting there, three thumbs-up and a countdown of unspoken assumption, waiting for her reply.",
            "task": "Have students write the text message A'Liyah could actually send back, using the lesson's script strategy, that responds honestly to the indirect group pressure without ghosting the chat, and have them label which parts of the scenario are peer pressure versus which parts (if any) are FOMO.",
        },
        "academic_vocab": {
            "word": "Articulate",
            "definition": "To express an idea clearly and effectively in words.",
            "syllables": "ar-TIK-yuh-layt",
            "morphology": "Latin articulus (small joint, connecting part) + -ate (verb-forming suffix)",
            "example": "A good peer-pressure script lets you articulate your decision calmly instead of scrambling for words in the moment.",
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which of the following is an example of indirect peer pressure?",
                 "choices": ["A. A friend directly asking you to lend them money",
                             "B. Feeling like you need the same shoes as your friend group even though no one asked you to buy them",
                             "C. A store advertisement", "D. Setting a savings goal"],
                 "answer": "B"},
                {"type": "multiple_choice", "q": "What is one advantage of preparing a \"script\" in advance for peer pressure situations?",
                 "choices": ["A. It guarantees you'll never spend money again",
                             "B. It removes the need to make a hard decision in the pressured moment because you've already decided",
                             "C. It makes the friend feel bad", "D. It has no real effect"],
                 "answer": "B"},
                {"type": "short_answer", "q": "Explain the difference between FOMO and peer pressure, using an example of each.",
                 "sample_answer": "FOMO is an internal, anxious feeling of missing out even without anyone pushing you; peer pressure involves another person, directly or indirectly, nudging the decision. Example: FOMO is scrolling and feeling anxious about a trip you weren't invited to; peer pressure is a friend directly asking you to chip in for something."},
                {"type": "multiple_choice", "q": "Peer pressure related to money can be:",
                 "choices": ["A. Only direct", "B. Only indirect", "C. Either direct or indirect", "D. Not related to money"],
                 "answer": "C"},
            ],
        },
        "exit_ticket": {
            "prompt": "Write one \"script\" sentence you could actually use the next time you feel peer pressure to spend money you hadn't planned to spend.",
        },
        "slide_bullets": [
            "Today's focus: Peer Pressure",
            "Direct peer pressure: someone asks you outright",
            "Indirect peer pressure: an unspoken group expectation",
            "Peer pressure vs. FOMO: outside push vs. inside anxiety",
            "Strategy: decide your script before the moment hits",
            "Activity: Say This, Not That script writing",
            "Exit ticket: write your own script line",
        ],
    },
    {
        "day": 5,
        "unit": 1,
        "lesson_in_unit": 5,
        "title": "Setting Goals That Actually Work: S.M.A.R.T. Goals",
        "objectives": [
            "I can define each part of the S.M.A.R.T. goals framework.",
            "I can revise a vague financial goal into a full S.M.A.R.T. goal.",
        ],
        "vocab": [
            {"word": "S.M.A.R.T. Goals", "definition": "A goal-setting framework requiring a goal to be Specific, Measurable, Achievable, Relevant, and Time-bound.",
             "example": "\"Save $30 a month for six months to reach $180 for a laptop by winter break\" is a S.M.A.R.T. goal.",
             "syllables": "S-M-A-R-T (each letter said aloud) GOHLZ",
             "morphology": "Acronym: S = Specific, M = Measurable, A = Achievable, R = Relevant, T = Time-bound."},
        ],
        "warm_up": "Write down a money goal you have right now, in one sentence, however vague or specific it is.",
        "mini_lesson": [
            {"heading": "From Vague Wish to Real Goal",
             "body": "So far this unit has focused mostly on the forces that pull your money decisions off course: bias, FOMO, peer pressure. Today shifts to a tool that helps you stay on course: the S.M.A.R.T. goal framework. Most people's financial goals start out vague, \"save more,\" \"stop spending so much,\" and vague goals are almost impossible to actually reach because there's no clear finish line and no way to check progress along the way. S.M.A.R.T. goals fix that by forcing a goal to answer five specific questions."},
            {"heading": "The Five Parts of a S.M.A.R.T. Goal",
             "body": "S.M.A.R.T. stands for Specific, Measurable, Achievable, Relevant, and Time-bound. Specific means naming exactly what you want, not a general direction. Measurable means attaching a number so you can track progress. Achievable means it's realistic given your actual income and time. Relevant means it connects to something that actually matters to you, not just something you think you should want. Time-bound means it has a deadline, because a goal without a deadline tends to quietly disappear."},
            {"heading": "A Worked Example",
             "body": "Here's the shift in action. Vague goal: \"I want to save money for college.\" S.M.A.R.T. version: \"I will save $50 a month from my part-time job into a separate savings account, reaching $600 by the end of this school year, to help cover a technical certification deposit.\" Notice every part of S.M.A.R.T. shows up: a number, a timeline, a real reason, and something realistic given a part-time paycheck."},
        ],
        "activity": {
            "title": "S.M.A.R.T. Goals Worksheet",
            "instructions": "Have students take the vague money goal they wrote during today's warm-up and complete the S.M.A.R.T. Goals worksheet from the Banzai High School Personal Finance Workbook, filling in each of the five categories. Once finished, partner students up to trade worksheets and give each other feedback on whether the goal is truly measurable and time-bound, not just specific. Collect worksheets as a formative check.",
        },
        "reading": None,
        "application": {
            "type": "simulation",
            "title": "Six Months to a Certification Voucher",
            "scenario": "A local coding bootcamp is offering a $300 discounted enrollment voucher, but it has to be paid in full six months from today to lock in the price. A student interested in the bootcamp currently has $0 saved toward it and earns $60 a week from a part-time job, most of which already goes toward gas and phone bill. They think they could realistically set aside $25 a week without straining their budget, but they haven't done the math on whether that actually gets them to $300 in time, and they haven't written down why the certificate matters to them or what happens if they fall short.",
            "task": "Have students calculate whether saving $25 a week gets the student to $300 within the six-month window (showing the math), then have them write the goal as a full S.M.A.R.T. statement, filling in all five parts, and flag whether the original $25-a-week plan needs to be adjusted to actually be Achievable and Time-bound.",
        },
        "academic_vocab": {
            "word": "Differentiate",
            "definition": "To identify and explain the distinct differences between two or more things.",
            "syllables": "dif-uh-REN-shee-ayt",
            "morphology": "Latin dis- (apart) + ferre (to carry) + -ate (verb-forming suffix)",
            "example": "Being able to differentiate a Specific goal from a merely Measurable one helps you catch which part of your S.M.A.R.T. goal is still missing.",
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What does the \"M\" in S.M.A.R.T. goals stand for?",
                 "choices": ["A. Motivational", "B. Measurable", "C. Manageable", "D. Money-based"],
                 "answer": "B"},
                {"type": "multiple_choice", "q": "Which of these is the best example of a S.M.A.R.T. goal?",
                 "choices": ["A. I want to be better with money.",
                             "B. I will save $30 a month for six months to reach $180 for a laptop by winter break.",
                             "C. I should probably save something eventually.",
                             "D. Money is important to me."],
                 "answer": "B"},
                {"type": "short_answer", "q": "Take the goal \"I want to save money\" and rewrite it as a full S.M.A.R.T. goal, including all five parts.",
                 "sample_answer": "Answers vary but must include a specific amount, a way to measure it, a realistic plan, a personal reason it matters, and a clear deadline."},
                {"type": "multiple_choice", "q": "Why does a S.M.A.R.T. goal need to be time-bound?",
                 "choices": ["A. Because deadlines make goals sound more official",
                             "B. Because a goal without a deadline is easy to put off indefinitely",
                             "C. Because it's required by law", "D. Because it has nothing to do with actually reaching the goal"],
                 "answer": "B"},
            ],
        },
        "exit_ticket": {
            "prompt": "Share your completed S.M.A.R.T. goal from today's worksheet: what is your specific number, and what is your deadline?",
        },
        "slide_bullets": [
            "Today's focus: S.M.A.R.T. Goals",
            "Vague goals are almost impossible to actually track",
            "S.M.A.R.T. = Specific, Measurable, Achievable, Relevant, Time-bound",
            "Every part matters: a number, a deadline, a real reason",
            "Activity: S.M.A.R.T. Goals worksheet (Banzai workbook)",
            "Peer feedback: is your goal really measurable and time-bound?",
            "Exit ticket: share your number and your deadline",
        ],
    },
    {
        "day": 6,
        "unit": 1,
        "lesson_in_unit": 6,
        "title": "Reading Day: How Advertising Targets Teen Spending",
        "objectives": [
            "I can identify advertising techniques designed to influence teen spending.",
            "I can evaluate the credibility of a source of financial or product information.",
        ],
        "vocab": [
            {"word": "Advertising Influence", "definition": "The effect that marketing, sponsored content, and promotional messaging has on a person's wants and decisions, often without them noticing.",
             "example": "A countdown timer on a sale page is designed to use advertising influence to rush your decision.",
             "syllables": "AD-ver-ty-zing IN-floo-ents",
             "morphology": "'Advertising' comes from Latin advertere (to turn toward), ad- (toward) + vertere (to turn); 'influence' comes from Latin influere (to flow into), in- (into) + fluere (to flow)."},
            {"word": "Source Information/Credibility", "definition": "The practice of judging whether information about money or a product actually deserves trust, based on who created it and what they gain.",
             "example": "Checking whether a glowing product review comes from a paid partnership is an exercise in source credibility.",
             "syllables": "SORSS in-for-MAY-shun / kred-uh-BIL-uh-tee",
             "morphology": "'Source' comes from Latin surgere (to rise up); 'credibility' comes from Latin credere (to believe) + -ibilis (able to be) + -ity (noun-forming suffix)."},
        ],
        "warm_up": "Think of an ad that made you want to buy something you hadn't planned on buying. What specifically did the ad do to make you want it?",
        "mini_lesson": [
            {"heading": "What Is Advertising Influence?",
             "body": "Advertising influence is the effect that marketing, sponsored content, and promotional messaging has on your wants and decisions, often without you noticing it's happening. Good advertising doesn't feel like advertising; it feels like discovering something on your own. Companies research exactly which colors, words, and messengers make teenagers more likely to buy, and they test those choices constantly. Recognizing advertising influence doesn't mean every ad is manipulative or that wanting something you saw in an ad is wrong. It means knowing when an emotional reaction is being deliberately engineered instead of naturally occurring."},
            {"heading": "Evaluating Source Information and Credibility",
             "body": "Source information and credibility means being able to judge whether information about money, or about a product, actually deserves your trust. A credible source is transparent about who created it and what, if anything, they gain from you believing it. A company blog telling you why you need their product is a different kind of source than an independent consumer guide comparing several options. Before trusting a financial claim or a glowing review, it helps to ask three questions: Who wrote this? What do they get if I believe it? Can I find the same claim somewhere with no stake in my answer?"},
        ],
        "activity": {
            "title": "Spot the Technique",
            "instructions": "After reading \"How Advertising Targets Teen Spending\" as a class, show students two or three real or realistic ad examples (a countdown sale banner, an influencer post, an \"as seen on\" product page). In small groups, have them identify which technique from the reading (social proof, urgency/scarcity, influencer blur) each example uses and rate how credible the underlying source information actually is.",
        },
        "reading": {
            "type": "informational",
            "title": "How Advertising Targets Teen Spending",
            "body": "Companies spend billions of dollars a year figuring out exactly how to get teenagers to buy things, and it isn't random. Teen spending habits are still forming, which makes this age group a major target for advertisers who want to build brand loyalty early.\n\nOne common technique is social proof: showing an ad that makes it look like \"everyone\" already owns or uses a product. Ads and sponsored posts often feature people who look like relatable peers, not distant celebrities, because research shows teens trust recommendations that feel personal rather than obviously staged.\n\nAnother is urgency and scarcity: \"limited drop,\" \"only 3 left,\" \"sale ends tonight.\" These phrases are designed to shrink your decision-making window on purpose. When you feel rushed, you're less likely to check your spending plan and more likely to decide based on emotion.\n\nInfluencer marketing blurs the line between a genuine recommendation and a paid advertisement. Many creators are contractually required to disclose sponsored content, but the disclosure is often a small tag that's easy to scroll past, while the emotional pitch, someone you already trust talking directly to camera, does the real work.\n\nNot every source of financial or product information is equally trustworthy. A company's blog post about why you need their product is not the same as an unbiased consumer guide, even if both use confident, expert-sounding language. Before trusting a claim, it helps to ask: Who wrote this? What do they gain if I believe it? Is there evidence outside of this one source?\n\nRecognizing these techniques doesn't mean you'll never buy something advertisers want you to buy. It means the choice becomes yours instead of the ad's.\n\n(Adapted from a consumer financial literacy guide on advertising and youth spending.)",
            "questions": [
                "Name two specific advertising techniques described in the reading and explain how each works.",
                "Why do advertisers often use people who look like relatable peers rather than distant celebrities?",
                "What three questions does the reading suggest asking before trusting a financial claim?",
                "Why might a small, easy-to-scroll-past disclosure tag not be enough to protect consumers?",
                "In your own words, what is the difference between an ad influencing you and an ad informing you?",
            ],
        },
        "application": {
            "type": "case_study",
            "title": "The Sponsored Post",
            "scenario": "An influencer with 40,000 followers posts a video titled \"How I Manifested My Savings Account\" promoting a $60 online \"money mindset\" course. The video features testimonials from three followers, a countdown graphic saying enrollment closes in 48 hours, and a tiny gray \"#ad\" tag in the corner of the screen for the first two seconds. The influencer never explains what's actually inside the course, only that it \"changed her relationship with money.\" A student watching the video feels genuinely moved and is considering signing up using money set aside for other things.",
            "task": "Using the reading's three credibility questions (who wrote this, what do they gain, is there outside evidence), have students write a short paragraph evaluating whether this post is a credible source of financial information, citing at least two specific details from the scenario as evidence.",
        },
        "academic_vocab": {
            "word": "Evaluate",
            "definition": "To judge the value, credibility, or quality of something based on evidence.",
            "syllables": "ee-VAL-yoo-ayt",
            "morphology": "Latin ex- (out) + valere (to be strong, to be worth) + -ate (verb-forming suffix)",
            "example": "Before trusting a sponsored post, evaluate the source using the three credibility questions from today's reading.",
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which technique relies on making a decision feel urgent to reduce careful thinking?",
                 "choices": ["A. Source credibility", "B. Urgency and scarcity", "C. S.M.A.R.T. goals", "D. Personal bias"],
                 "answer": "B"},
                {"type": "multiple_choice", "q": "Which question is LEAST useful for evaluating whether a financial source is credible?",
                 "choices": ["A. Who wrote this?", "B. What do they gain if I believe it?",
                             "C. Is there evidence outside this one source?", "D. Does it use confident-sounding language?"],
                 "answer": "D"},
                {"type": "short_answer", "q": "Explain why an influencer's product recommendation might not be a fully credible source of information, even if the influencer seems trustworthy.",
                 "sample_answer": "Influencers are often paid to promote products, which is a stake in the outcome; even a genuinely trustworthy-seeming person can have a financial incentive that shapes what they say, so their recommendation isn't the same as unbiased, independent information."},
                {"type": "multiple_choice", "q": "Advertising influence is best described as:",
                 "choices": ["A. Only illegal marketing",
                             "B. The effect that marketing and promotional content has on wants and decisions, often without notice",
                             "C. A type of financial goal", "D. A government regulation"],
                 "answer": "B"},
            ],
        },
        "exit_ticket": {
            "prompt": "Describe one advertising technique from today's reading and one question you can ask yourself next time you feel pulled to buy something you saw advertised.",
        },
        "slide_bullets": [
            "Today's focus: Advertising Influence and Source Credibility",
            "Reading: \"How Advertising Targets Teen Spending\"",
            "Technique 1: social proof (relatable peers, not celebrities)",
            "Technique 2: urgency and scarcity (shrinks your decision window)",
            "Influencer marketing blurs recommendation and advertisement",
            "Ask: who wrote this, what do they gain, is there outside evidence?",
            "Activity: Spot the Technique",
        ],
    },
    {
        "day": 7,
        "unit": 1,
        "lesson_in_unit": 7,
        "title": "The Impulse Buy Autopsy",
        "objectives": [
            "I can define impulse buying and identify its personal triggers.",
            "I can apply a pause strategy to slow down a spending decision.",
        ],
        "vocab": [
            {"word": "Impulse Buying", "definition": "Making a purchase with little or no planning, usually driven by an in-the-moment feeling rather than a spending plan or goal.",
             "example": "Grabbing a $40 item at checkout you hadn't thought about five minutes earlier is impulse buying.",
             "syllables": "IM-puls BY-ing",
             "morphology": "'Impulse' comes from Latin impellere (to drive or push against), im- (against) + pellere (to drive); 'buying' comes from Old English bycgan (to buy) + -ing."},
        ],
        "warm_up": "Describe a recent purchase, small or large, that you made without really planning it. What happened right before you decided to buy it?",
        "mini_lesson": [
            {"heading": "What Is Impulse Buying?",
             "body": "Impulse buying is making a purchase with little or no planning, usually driven by an in-the-moment feeling rather than a decision that fits into a spending plan or goal. It's not automatically bad. An occasional small impulse buy, like a coffee treat, isn't what derails someone's finances. The problem is when impulse buying becomes the default way decisions get made, especially on larger purchases, because it skips the step where you check whether something actually fits your goals."},
            {"heading": "Why This Unit Built Up to This Word",
             "body": "Impulse buying rarely happens in isolation. It's usually the visible result of everything this unit has already covered working together: a personal bias telling you \"you deserve this,\" FOMO from seeing someone else's purchase, peer pressure from a friend nudging you, or an ad engineered to create urgency. Understanding impulse buying means understanding it as an output, not a standalone problem. That's why it's the seventh word in this unit instead of the first."},
            {"heading": "The Pause Strategy",
             "body": "One of the most effective tools against impulse buying is a built-in pause, sometimes called the 24-hour rule: if a purchase isn't an emergency, wait a set amount of time, even just overnight, before buying it. The pause doesn't ban the purchase. It just moves the decision from an emotional moment to a calmer one, giving your actual goals and spending plan a chance to weigh in instead of only your immediate feeling."},
        ],
        "activity": {
            "title": "Impulse Buy Autopsy",
            "instructions": "Have students think of a real or realistic recent impulse purchase and complete an \"autopsy\" worksheet with three columns: the trigger (what happened right before), the feeling (what emotion was present), and the outcome (how they felt about it afterward, a day or a week later). In the final section, have them rewrite the decision using the pause strategy and note whether they think the outcome would have changed.",
        },
        "reading": None,
        "application": {
            "type": "real_world_problem",
            "title": "The Checkout Line Math",
            "scenario": "A student walks into a store planning to buy exactly one thing: a $12 birthday card for a friend. While waiting in the checkout line, they add a $6 phone charm from the impulse rack, then a $9 energy drink four-pack because it's \"basically the same price as one at the vending machine anyway.\" Their planned budget for this errand was $15, cash they'd set aside from their last paycheck specifically for the card and nothing else.",
            "task": "Have students calculate the total actual spending versus the planned $15 budget, find the dollar amount of overspend, and then apply the 24-hour rule to decide which of the two impulse add-ons (if either) is worth buying today versus waiting on, explaining their reasoning.",
        },
        "academic_vocab": {
            "word": "Critique",
            "definition": "To carefully assess something's strengths and weaknesses, pointing out specifically what worked and what didn't.",
            "syllables": "kri-TEEK",
            "morphology": "Greek kritikos (able to discern or judge), from krinein (to separate, decide, judge)",
            "example": "In today's autopsy activity, you'll critique one of your own past purchases to see exactly where the decision went off track.",
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Impulse buying is best defined as:",
                 "choices": ["A. Any purchase made with cash",
                             "B. A purchase made with little or no planning, driven by an in-the-moment feeling",
                             "C. A purchase that is always a mistake", "D. A purchase included in a spending plan"],
                 "answer": "B"},
                {"type": "multiple_choice", "q": "According to today's lesson, impulse buying is often the result of:",
                 "choices": ["A. A single unrelated cause",
                             "B. A combination of bias, FOMO, peer pressure, or advertising influence working together",
                             "C. Careful long-term planning", "D. A S.M.A.R.T. goal"],
                 "answer": "B"},
                {"type": "short_answer", "q": "Explain how the 24-hour rule works and why even a short pause can change a purchase decision.",
                 "sample_answer": "The 24-hour rule means waiting a set period, like overnight, before making a non-emergency purchase. The pause moves the decision away from the emotional moment it started in, giving time for goals and a spending plan to factor into the choice instead of only the immediate feeling."},
                {"type": "multiple_choice", "q": "Which is an example of using the pause strategy?",
                 "choices": ["A. Buying concert tickets the second they go on sale",
                             "B. Deciding to wait until tomorrow to decide on a nonessential purchase",
                             "C. Asking a friend if they have the same item", "D. Ignoring your spending plan"],
                 "answer": "B"},
            ],
        },
        "exit_ticket": {
            "prompt": "Describe one specific trigger (a feeling, situation, or influence) that tends to lead you toward impulse buying.",
        },
        "slide_bullets": [
            "Today's focus: Impulse Buying",
            "Impulse buying = little/no planning, driven by in-the-moment feeling",
            "It's the output of bias, FOMO, peer pressure, and advertising combined",
            "Not all impulse buys are disasters, the pattern is what matters",
            "Strategy: the 24-hour pause rule",
            "Activity: Impulse Buy Autopsy worksheet",
            "Exit ticket: name your personal impulse-buy trigger",
        ],
    },
    {
        "day": 8,
        "unit": 1,
        "lesson_in_unit": 8,
        "title": "Reading Day: What's a Major, Anyway?",
        "objectives": [
            "I can connect the unit's ideas about noticing outside influence to thinking about future career interests.",
            "I can explain why both personal interest and realistic income matter when considering a future path.",
        ],
        "vocab": [
            {"word": "Financial Goals", "definition": "Specific, intentional outcomes you want your money to help you reach, as opposed to a vague wish.",
             "example": "Thinking ahead about whether a future career can realistically support your financial goals is part of planning, not just picking something that sounds fun.",
             "syllables": "fi-NAN-shul GOHLZ",
             "morphology": "Latin financia (payment) + -ial (adjective-forming suffix) gives 'financial'; 'goal' traces to Middle English gol (a boundary or limit to be reached)."},
        ],
        "warm_up": "If money were no object at all, what would you want to spend your time doing? Now, does your answer change if you imagine paying your own rent next year?",
        "mini_lesson": [
            {"heading": "Why This Reading Bridges Two Topics",
             "body": "Today's reading looks ahead to a question this course will spend the next unit on: how do you choose a career or college major? For today, the focus stays on the psychology piece, not the details of majors or salaries. The same forces you've studied all unit, bias, outside pressure, FOMO, show up just as much in choosing a future path as they do in choosing what to buy. Deshawn, in today's reading, is dealing with pressure from a family member's opinion and his own uncertainty about what he even likes."},
            {"heading": "Interests and Income Both Matter",
             "body": "Two things matter when thinking about any future path: what genuinely interests you, and what it can realistically support financially. Neither one alone is enough. Picking only based on interest without ever considering income can create real financial stress later. Picking only based on projected income, ignoring what you actually enjoy, tends to lead to burnout. This unit has been about noticing which voice is talking, your own or someone else's, in a decision. That skill applies just as much to choosing a path as it does to a purchase."},
        ],
        "activity": {
            "title": "Interest vs. Income Quick-Sort",
            "instructions": "Give students a list of eight to ten career or field names. Individually, have them mark each one with a plus, minus, or neutral for personal interest, then separately for likely income level, without researching yet. In pairs, discuss which fields scored high on both, which scored high on only one, and connect back to the reading's idea that both interest and income deserve a voice in the decision, but neither should be the only voice.",
        },
        "reading": {
            "type": "realistic_fiction",
            "title": "What's a Major, Anyway?",
            "body": "Deshawn was sitting on the stairs outside Maya's apartment when she got back from her shift, hoodie up, scrolling through something on his phone like it had personally offended him.\n\n\"You look like the FAFSA worksheet,\" Maya said, sitting down next to him. She'd finally opened hers, for the record. Priya had asked twice.\n\n\"Worse.\" Deshawn turned the phone toward her. It was a college website, a wall of major names. \"Mr. Alvarez wants us to write down three majors we're 'considering.' I don't even know what a major actually is. Like, is it my whole life now? Do I have to know already?\"\n\n\"It's not your whole life. It's what you focus most of your classes on for four years. You still take other stuff too.\" Maya took the phone and scrolled. \"What are you even looking at right now?\"\n\n\"Nothing. Everything. Business, because my uncle says that's where the money is. Then I saw kinesiology and now I'm reading about that because it sounded cool, but I don't even know what job comes after it.\"\n\n\"Okay, that's actually the right question. Not what sounds cool, not what my uncle said, what do you actually like doing, and does it lead somewhere that pays enough to live on?\" Maya handed the phone back. \"Both parts matter. My sister always says don't pick something just because you love it if it can't pay rent, and don't pick something just for money if you'll hate every day of it.\"\n\n\"So how do I know which one I like enough?\"\n\n\"You don't, yet. That's kind of the point of this whole unit before we even get to picking one.\" Maya thought about the shoes still sitting in her closet, mostly worn now, and how weird it still felt that she almost couldn't tell why she'd bought them. \"Same thing with money, honestly. First you figure out what's actually you talking, versus what's your uncle, or an ad, or panic talking. Then you can pick something real.\"\n\nDeshawn was quiet for a second. \"That's annoyingly deep for a Tuesday.\"\n\n\"I contain multitudes.\" Maya stood up and offered him a hand off the stairs. \"Start with what you're actually interested in. We'll get to income next. It's not one or the other, it's both, in order.\"\n\n\"Both, in order,\" Deshawn repeated, like he was trying to remember it for later. \"Fine. I liked the kinesiology thing. Don't tell my uncle.\"\n\n\"Your secret's safe. For now.\"",
            "questions": [
                "What does Deshawn admit he doesn't understand at the start of the reading?",
                "What does Maya mean when she says both interests and income 'matter' and 'in order'?",
                "How does this reading connect back to the FOMO/bias themes from earlier in the unit (Maya's comment about the shoes)?",
                "Why do you think Maya tells Deshawn his secret is safe about not telling his uncle?",
                "What do you think Maya means by figuring out what's actually you talking, versus what's your uncle, or an ad, or panic talking?",
            ],
        },
        "application": {
            "type": "case_study",
            "title": "Two Offers, One Decision",
            "scenario": "Tomas, a coworker of Priya's, has narrowed his college options down to two paths. The first is a two-year welding certificate program: he finds the work genuinely satisfying, hands-on and immediate, and the field pays well right out of school, but his uncle keeps calling it a \"backup plan\" and pushing him toward a four-year business degree instead, one Tomas finds mostly boring when he pictures the actual coursework. The second is that business degree, which Tomas admits he's only considering because his uncle brings it up at every family dinner and it would \"make sense to everyone.\" Tomas hasn't told his uncle yet that he's leaning welding.",
            "task": "Have students analyze the scenario using the reading's framework (personal interest AND realistic income, in that order) to write a two-to-three sentence recommendation for Tomas, explicitly naming which parts of his hesitation come from his own judgment versus outside pressure.",
        },
        "academic_vocab": {
            "word": "Prioritize",
            "definition": "To decide which of several things matters most and put them in order of importance.",
            "syllables": "pry-OR-uh-tize",
            "morphology": "Latin prior (former, first, earlier) + -ize (verb-forming suffix meaning 'to make')",
            "example": "Deshawn has to prioritize his own genuine interest before he even gets to weighing income, instead of the other way around.",
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "What is Deshawn confused about at the start of the reading?",
                 "choices": ["A. How to fill out a spending plan",
                             "B. What a college major actually is and whether he has to know already",
                             "C. How much his shoes cost", "D. His work schedule"],
                 "answer": "B"},
                {"type": "multiple_choice", "q": "According to Maya, what two things should factor into choosing a future path?",
                 "choices": ["A. Only what an uncle recommends", "B. Only projected income",
                             "C. Both personal interest and realistic income", "D. Only what sounds interesting online"],
                 "answer": "C"},
                {"type": "short_answer", "q": "Explain how the skill of noticing whose voice is influencing a decision (from earlier in the unit) applies to Deshawn's situation with choosing a major.",
                 "sample_answer": "Just as Maya learned to notice whether a purchase was really her decision or FOMO and pressure talking, Deshawn needs to notice whether a major choice is really his own interest and judgment or just his uncle's opinion, and separate that from the actual decision."},
                {"type": "multiple_choice", "q": "This reading mainly previews which upcoming course topic?",
                 "choices": ["A. Filling out taxes", "B. Choosing careers and college majors",
                             "C. Renting an apartment", "D. Building credit"],
                 "answer": "B"},
            ],
        },
        "exit_ticket": {
            "prompt": "Name one thing you're personally interested in, and one question you'd want answered about whether it could realistically support you financially.",
        },
        "slide_bullets": [
            "Reading Day: \"What's a Major, Anyway?\", installment 2 of \"The Fund\"",
            "Bridges Unit 1 psychology into Unit 2 careers and majors",
            "Deshawn's question: what even is a major?",
            "Maya's rule: interests AND income, in order, not just one",
            "Same skill as bias/FOMO unit: whose voice is really talking?",
            "Activity: Interest vs. Income Quick-Sort",
            "Coming next unit: careers, majors, and earning income",
        ],
    },
    {
        "day": 9,
        "unit": 1,
        "lesson_in_unit": 9,
        "title": "Building Your First Spending Plan",
        "objectives": [
            "I can define a spending plan and distinguish needs from wants.",
            "I can build a simple spending plan that connects to a personal financial goal.",
        ],
        "vocab": [
            {"word": "Spending Plan", "definition": "A plan that lines up income against outgoing expenses by category (needs, wants, savings) so spending is decided on purpose rather than discovered after the fact.",
             "example": "Sorting a paycheck into rent money, phone bill, savings, and fun money before spending any of it is building a spending plan.",
             "syllables": "SPEN-ding PLAN",
             "morphology": "'Spending' comes from Old English spendan (to spend), borrowed from Latin expendere (to weigh out, pay out); 'plan' comes from Latin planus (flat, level ground)."},
        ],
        "warm_up": "List everything you spent money on in the last seven days, from memory, without checking your bank app or receipts.",
        "mini_lesson": [
            {"heading": "What Is a Spending Plan?",
             "body": "A spending plan is a simple plan that lines up the money coming in against the money going out, sorted by category, so you can see where it's going before it's already gone. Some people call this a budget, but \"spending plan\" is a more accurate name: it's not about restriction for its own sake, it's about deciding in advance, on purpose, rather than finding out after the fact where your money went. A spending plan doesn't have to be complicated. Even a simple list of income, needs, wants, and savings is a real spending plan."},
            {"heading": "Needs vs. Wants",
             "body": "Needs are expenses required to function: things like transportation to work, phone service if it's required for a job, or food. Wants are things that are enjoyable or nice to have but not required, like a streaming subscription, eating out, or new clothes beyond what's necessary. The line between the two isn't always obvious and can depend on someone's actual situation. A car might be a want for one student and a genuine need for another student whose job requires driving. A spending plan works best when a person is honest about which category something really belongs in."},
            {"heading": "Connecting the Plan to Your Goals",
             "body": "A spending plan only works if it connects to something. Without a goal behind it, a spending plan is just a list of numbers. With a S.M.A.R.T. goal behind it, like the one from earlier this week, a spending plan becomes the actual mechanism that gets you there: it shows exactly how much room is left over after needs and reasonable wants to put toward that goal every month."},
        ],
        "activity": {
            "title": "Build a Spending Plan",
            "instructions": "Using the Banzai High School Personal Finance Workbook's spending plan template, give students a sample teen income scenario (a set part-time paycheck amount). Have them sort a list of sample expenses into needs, wants, and savings, then calculate what's left over. Ask students to compare that leftover amount to the S.M.A.R.T. goal they wrote earlier in the unit and discuss whether their plan actually gets them there on schedule.",
        },
        "reading": None,
        "application": {
            "type": "simulation",
            "title": "One Paycheck, Four Categories",
            "scenario": "A student earns a $420 biweekly paycheck from a part-time retail job. Over the past two weeks, their actual spending looked like this: $60 on gas, $45 on their phone bill, $85 on eating out with friends, $30 on a streaming subscription split with siblings, $25 on a new hoodie, and $20 on miscellaneous snacks and small purchases. Nothing was set aside first for savings; whatever was left at the end just sat in the account.",
            "task": "Have students sort each of the six expenses into needs, wants, or savings, total each category, calculate what was actually left over after needs, and then determine how much of that leftover amount could have gone toward a $50-a-month S.M.A.R.T. goal if wants had been trimmed by 25 percent.",
        },
        "academic_vocab": {
            "word": "Allocate",
            "definition": "To distribute a limited resource, like money or time, for a specific purpose.",
            "syllables": "AL-uh-kayt",
            "morphology": "Latin ad- (to, toward) + locare (to place), from locus (place)",
            "example": "A spending plan works by helping you allocate each paycheck across needs, wants, and savings before you spend a dollar of it.",
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "A spending plan is best described as:",
                 "choices": ["A. A punishment for overspending",
                             "B. A plan that lines up income against outgoing expenses by category so spending is decided on purpose",
                             "C. A type of credit card", "D. A government form"],
                 "answer": "B"},
                {"type": "multiple_choice", "q": "Which of these is most likely to be a \"need\" rather than a \"want\" for most students?",
                 "choices": ["A. A streaming subscription", "B. Transportation required to get to a job",
                             "C. New name-brand shoes", "D. Eating out with friends"],
                 "answer": "B"},
                {"type": "short_answer", "q": "Explain why a spending plan without a goal attached to it is, in the lesson's words, \"just a list of numbers.\"",
                 "sample_answer": "A spending plan shows where money goes, but without a specific goal behind it, there's no clear purpose guiding decisions about wants versus savings; a goal gives the leftover money in the plan a job to do."},
                {"type": "multiple_choice", "q": "Whether something counts as a need or a want:",
                 "choices": ["A. Is always the same for every person",
                             "B. Can depend on a person's actual situation, like whether a car is required for their job",
                             "C. Never matters", "D. Is decided only by advertisers"],
                 "answer": "B"},
            ],
        },
        "exit_ticket": {
            "prompt": "List one need and one want from your own life, and note which one currently gets more of your money.",
        },
        "slide_bullets": [
            "Today's focus: Spending Plan",
            "A spending plan lines up income vs. outgoing expenses, on purpose",
            "Needs = required to function; wants = enjoyable but not required",
            "The need/want line can depend on your actual situation",
            "A spending plan without a goal is just a list of numbers",
            "Activity: Build a Spending Plan (Banzai workbook)",
            "Exit ticket: name a need and a want from your own life",
        ],
    },
    {
        "day": 10,
        "unit": 1,
        "lesson_in_unit": 10,
        "title": "Unit 1 Review & Assessment: What Impacts My Financial Thinking?",
        "objectives": [
            "I can define and apply all ten Unit 1 vocabulary terms in realistic scenarios.",
            "I can explain how bias, FOMO, peer pressure, and advertising interact to influence spending, and how S.M.A.R.T. goals and a spending plan counter that influence.",
        ],
        "vocab": [
            {"word": "Financial Thinking", "definition": "The whole unit's umbrella idea: the mental process, biases, and outside pressures behind every money decision you make.",
             "example": "Today's review pulls together every Unit 1 term under one big idea: financial thinking.",
             "syllables": "fi-NAN-shul THING-king",
             "morphology": "Latin financia (payment) + -ial forms 'financial'; 'thinking' comes from Old English thencan (to think) + -ing (suffix forming a noun of process)."},
        ],
        "warm_up": "Of all ten words we've learned this unit, which one do you think will matter most for your own life this year? Write one sentence explaining why.",
        "mini_lesson": [
            {"heading": "The Forces That Pull",
             "body": "Ten words, one unit, one big idea: a lot of forces are quietly pulling at your spending decisions before you even notice a decision is being made. Personal bias supplies automatic mental shortcuts. FOMO adds anxious urgency borrowed from other people's highlight reels. Peer pressure adds a direct or indirect nudge from people around you. Advertising influence engineers all of that on purpose, using techniques designed specifically to work on people your age. Impulse buying is what it looks like when all of that wins in the moment, without a pause."},
            {"heading": "The Tools That Ground You",
             "body": "This unit also gave you tools to push back. Financial thinking is the habit of noticing your own patterns instead of running on autopilot. Financial goals and S.M.A.R.T. goals turn vague wishes into specific, time-bound targets you can actually track. A spending plan connects your everyday choices to those goals on purpose, sorting needs from wants. Source information and credibility helps you judge what's actually true versus what's designed to sell you something. None of these tools eliminate bias or pressure completely. They just make sure your own voice gets a vote in the decision, alongside everything else pulling at it."},
        ],
        "activity": {
            "title": "Unit 1 Vocabulary Relay",
            "instructions": "Split the class into small teams. Read a scenario aloud (for example: a student sees a countdown sale timer, feels panicked, and buys a jacket their friend group already has) and have teams race to write down every Unit 1 vocabulary term that applies to that single scenario, explaining briefly how each one shows up. Award points for correct terms with a valid explanation, then transition into the Unit 1 Assessment.",
        },
        "reading": None,
        "application": {
            "type": "real_world_problem",
            "title": "The Full Scenario",
            "scenario": "Three days before a concert, a student sees a countdown banner: \"Only 6 tickets left, price goes up in 2 hours.\" Two friends have already bought theirs and are texting \"you're still coming right??\" The tickets are $95, money the student had been putting toward a S.M.A.R.T. goal of saving $400 for a car down payment by August, currently at $210 saved. The student feels a knot in their stomach at the thought of being the only one not there, and part of them thinks, \"I've been so responsible lately, I deserve this.\"",
            "task": "Have students identify every Unit 1 vocabulary term present in this single scenario (at minimum: FOMO, peer pressure, advertising influence, personal bias, and the S.M.A.R.T. goal at risk), explain in one sentence each how it shows up, and then propose which specific tool from the unit (spending plan, the goal itself, source credibility, a script) the student should lean on to make the decision on purpose rather than on impulse.",
        },
        "academic_vocab": {
            "word": "Synthesize",
            "definition": "To combine separate pieces of information into a single, coherent understanding.",
            "syllables": "SIN-thuh-size",
            "morphology": "Greek syn- (together) + tithenai (to place, to put)",
            "example": "Today's review asks you to synthesize all ten Unit 1 vocabulary terms into one explanation of what shapes financial thinking.",
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which term describes an automatic mental shortcut that leans a money decision without full analysis?",
                 "choices": ["A. Spending plan", "B. Personal bias", "C. S.M.A.R.T. goal", "D. Source credibility"],
                 "answer": "B"},
                {"type": "multiple_choice", "q": "Which pair of terms are BOTH tools for countering impulsive spending decisions, rather than forces that create them?",
                 "choices": ["A. FOMO and peer pressure", "B. Advertising influence and impulse buying",
                             "C. S.M.A.R.T. goals and a spending plan", "D. Personal bias and FOMO"],
                 "answer": "C"},
                {"type": "short_answer", "q": "Choose one force from this unit (bias, FOMO, peer pressure, or advertising influence) and one tool (financial goals, S.M.A.R.T. goals, spending plan, or source credibility) and explain how the tool could help counter that specific force.",
                 "sample_answer": "Answers vary; for example, a spending plan can counter FOMO because checking the plan before buying something forces a pause and a check against actual goals instead of an in-the-moment feeling."},
                {"type": "multiple_choice", "q": "This unit's essential question was \"What impacts my financial thinking?\" Based on the whole unit, the best short answer is:",
                 "choices": ["A. Only math ability",
                             "B. A mix of personal bias, social pressure, and advertising, balanced against tools like goals and planning",
                             "C. Nothing; financial thinking is fixed at birth", "D. Only family income"],
                 "answer": "B"},
            ],
        },
        "exit_ticket": {
            "prompt": "Of all ten words from this unit, pick the one you think will matter most in your own life this year, and explain why in two to three sentences.",
        },
        "slide_bullets": [
            "Unit 1 Review: What impacts my financial thinking?",
            "Forces that pull: bias, FOMO, peer pressure, advertising influence, impulse buying",
            "Tools that ground: financial thinking, financial goals, S.M.A.R.T. goals, spending plan, source credibility",
            "None of these tools erase bias, they just give your voice a vote",
            "Activity: Unit 1 Vocabulary Relay",
            "Unit 1 Assessment follows this review",
            "Next unit preview: careers, majors, and earning income",
        ],
    },
]
