UNIT_5_META = {
    "number": 5,
    "name": "Financial Aid",
    "essential_question": "What types of financial aid are available and which are best for me?",
    "overview": "This unit breaks down how students actually pay for college once they've been accepted: the FAFSA, the CSS Profile, and the mix of grants, scholarships, work-study, and loans that make up a financial aid package. Students learn to read the forms and the resulting award letters with a clear eye, separating free money from borrowed money before committing to a school.",
    "vocabulary_bank": [
        {"word": "FAFSA", "definition": "The Free Application for Federal Student Aid; the form nearly every college-bound student fills out to qualify for federal and state financial aid, plus most college-based aid.",
         "syllables": "FAF-suh (said as a word)", "morphology": "Acronym: F (Free) + A (Application for) + F (Federal) + S (Student) + A (Aid)."},
        {"word": "CSS Profile", "definition": "A more detailed financial aid form run by the College Board, required by some (mostly private) colleges in addition to the FAFSA, used to award their own institutional aid money.",
         "syllables": "C-S-S (spelled out) PROH-fyl", "morphology": "CSS = College Scholarship Service, the College Board division that originally created the form; 'Profile' from Latin pro- (forward) + filum (thread) — literally a sketch or outline, here of a family's finances."},
        {"word": "Scholarships (Merit, Need-Based)", "definition": "Money for college that does not have to be repaid; merit scholarships are awarded for achievement (grades, test scores, talent), need-based scholarships are awarded based on a family's financial situation.",
         "syllables": "SKAHL-er-ships (MER-it; NEED-based)", "morphology": "'Scholarship' from Greek skhole (leisure, school) + Old English -scipe (state of); 'merit' from Latin meritum (earned, deserved); 'need-based' = need + base + -ed."},
        {"word": "Grants", "definition": "Money for college that does not have to be repaid, awarded based on financial need, usually funded by the federal government, a state, or a college itself.",
         "syllables": "GRANTS (one syllable)", "morphology": "From Old French granter, tracing to Latin credentem (believing, entrusting) — literally 'something entrusted to you.'"},
        {"word": "Work-Study", "definition": "A federally funded program that provides part-time campus jobs to help students earn money toward college costs while enrolled.",
         "syllables": "WURK-STUH-dee", "morphology": "Compound word: 'work' (labor, job) + 'study' from Latin studium (zeal, application) — used here to mean 'while enrolled as a student.'"},
        {"word": "Parent/Student Contribution", "definition": "The portions of the total amount a family is expected to pay for college that come from parent resources versus the student's own income and assets.",
         "syllables": "PEHR-unt / STOO-dent kahn-truh-BYOO-shun", "morphology": "'Contribution' from Latin com- (together) + tribuere (to give, allot) — literally 'a giving together.'"},
        {"word": "Expected Family Contribution (EFC)/Student Aid Index (SAI)", "definition": "A number generated from FAFSA information that colleges use to estimate how much financial need a student has; it is an index for comparing aid eligibility, not a literal bill.",
         "syllables": "ek-SPEK-ted FAM-uh-lee kahn-truh-BYOO-shun / STOO-dent AYD IN-deks", "morphology": "EFC spelled letter by letter (E-F-C) = Expected Family Contribution; SAI spelled letter by letter (S-A-I) = Student Aid Index; 'expected' from Latin ex- (out) + spectare (to look/watch) — literally 'looked forward to.'"},
    ],
    "unit_assessment": {
        "title": "Unit 5 Assessment: Financial Aid",
        "questions": [
            {"type": "multiple_choice", "q": "Which form determines eligibility for federal grants, federal work-study, and federal student loans?",
             "choices": ["A. CSS Profile", "B. FAFSA", "C. Common App", "D. W-4"], "answer": "B"},
            {"type": "multiple_choice", "q": "A scholarship awarded because a student has a 3.9 GPA and is a nationally ranked debater is best described as:",
             "choices": ["A. Need-based", "B. Work-study", "C. Merit-based", "D. A grant"], "answer": "C"},
            {"type": "multiple_choice", "q": "Which statement about the CSS Profile is accurate?",
             "choices": ["A. It replaces the FAFSA at every college", "B. It is used mostly by private colleges to award their own institutional aid and often asks more detailed questions than the FAFSA", "C. It is only for students applying for work-study", "D. It has no cost and asks fewer questions than the FAFSA"], "answer": "B"},
            {"type": "multiple_choice", "q": "The Expected Family Contribution / Student Aid Index (EFC/SAI) is best described as:",
             "choices": ["A. The exact bill a family will receive from the college", "B. An index used to estimate financial need and compare aid eligibility across students", "C. The amount of a student's federal loan", "D. A score used only for merit scholarships"], "answer": "B"},
            {"type": "multiple_choice", "q": "Which of these is an example of a grant?",
             "choices": ["A. A federal Pell Grant awarded based on financial need", "B. A private student loan", "C. A campus library job funded by work-study", "D. A scholarship for the top debate student"], "answer": "A"},
            {"type": "short_answer", "q": "Explain the difference between a merit-based scholarship and a need-based scholarship, and give an example of a student who might qualify for each.",
             "sample_answer": "A merit-based scholarship is awarded for achievement, like grades or a talent, regardless of income; a student with a high GPA might qualify. A need-based scholarship is awarded based on a family's financial situation; a student from a lower-income household might qualify even without top grades."},
            {"type": "short_answer", "q": "Why does the FAFSA ask for parent financial information even though the student is the one attending college?",
             "sample_answer": "Because most students are financially dependent on their parents, colleges and the federal government use household income and assets to estimate how much of the cost the family can realistically cover, which determines how much aid the student is offered."},
            {"type": "short_answer", "q": "Describe what work-study is and how it is different from a regular off-campus part-time job.",
             "sample_answer": "Work-study is a federally funded program that provides part-time jobs on or connected to campus specifically for students who qualified for it through their financial aid application; unlike a regular job, the funding is tied to financial aid eligibility and the hours/earnings often factor into the student's aid package."},
        ],
    },
    "days": [44, 48],
}

UNIT_5_LESSONS = [
    {
        "day": 44,
        "unit": 5,
        "lesson_in_unit": 1,
        "title": "What Is Financial Aid? Grants, Scholarships, and the Big Picture",
        "objectives": [
            "I can distinguish between the major categories of financial aid: grants, scholarships, work-study, and loans.",
            "I can explain the difference between merit-based and need-based scholarships.",
            "I can explain why the FAFSA is the starting point for almost every type of financial aid.",
        ],
        "vocab": [
            {"word": "FAFSA", "definition": "The Free Application for Federal Student Aid; the form nearly every college-bound student fills out to qualify for federal and state financial aid, plus most college-based aid.",
             "example": "Even students whose families make a high income are told to fill out the FAFSA, because some aid and loans are not based on income at all.",
             "syllables": "FAF-suh (said as a word)", "morphology": "Acronym: F (Free) + A (Application for) + F (Federal) + S (Student) + A (Aid)."},
            {"word": "Scholarships (Merit, Need-Based)", "definition": "Money for college that does not have to be repaid; merit scholarships reward achievement, need-based scholarships are awarded based on a family's financial situation.",
             "example": "The same student can win a merit scholarship from her school and a need-based scholarship from a community foundation in the same year.",
             "syllables": "SKAHL-er-ships (MER-it; NEED-based)", "morphology": "'Scholarship' from Greek skhole (leisure, school) + Old English -scipe (state of); 'merit' from Latin meritum (earned, deserved); 'need-based' = need + base + -ed."},
        ],
        "warm_up": "If you could get money for college that you never have to pay back, versus money you have to pay back later with interest, which would you go after first? Why don't more students go after the free money first?",
        "mini_lesson": [
            {"heading": "Financial Aid Is an Umbrella Term", "body": "Financial aid is not one thing, it is four things stacked together: grants and scholarships (free money you never repay), work-study (money you earn through a part-time job), and loans (borrowed money you repay with interest). Most students end up with a package that mixes several of these. The goal of this unit is to understand each piece well enough to tell, later, which parts of any offer are actually free and which parts are debt."},
            {"heading": "Where It All Starts: The FAFSA", "body": "The FAFSA, Free Application for Federal Student Aid, is the form that unlocks nearly everything else. It asks about household income, taxes, and assets, then colleges use that information to build an aid offer. Almost every four-year college, community college, and technical program in the country requires it before they will send a financial aid package, even to students who end up qualifying for very little need-based money."},
            {"heading": "Merit vs. Need: Two Different Questions", "body": "Merit scholarships ask, what have you achieved? Grades, test scores, a sport, an art portfolio, a specific talent. Need-based scholarships ask a different question entirely: what can your family afford? A student can qualify for both at once, and colleges often combine several small awards into one larger package rather than one single scholarship."},
        ],
        "activity": {
            "title": "Banzai \"Cost of College\" Module",
            "instructions": "Have students log into the Banzai \"Cost of College\" module and run the simulation comparing sticker price at two or three schools they are personally considering. Ask them to note which cost categories (tuition, room and board, fees) surprised them most, and where they think financial aid could realistically close the gap. Debrief as a whole class, comparing a few students' numbers on the board.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which of these is an example of free money that does not need to be repaid?",
                 "choices": ["A. A federal student loan", "B. A need-based scholarship", "C. A private bank loan", "D. A credit card cash advance"], "answer": "B"},
                {"type": "multiple_choice", "q": "A scholarship awarded because a student scored a 34 on the ACT is best described as:",
                 "choices": ["A. Need-based", "B. Work-study", "C. Merit-based", "D. A loan"], "answer": "C"},
                {"type": "multiple_choice", "q": "What is the primary purpose of the FAFSA?",
                 "choices": ["A. To apply for a specific merit scholarship only", "B. To determine eligibility for federal, state, and most college-based financial aid", "C. To replace the college application itself", "D. To apply for a part-time job off campus"], "answer": "B"},
                {"type": "short_answer", "q": "Can a student qualify for both a merit scholarship and a need-based scholarship at the same time? Explain.",
                 "sample_answer": "Yes. Merit is based on achievement and need is based on financial situation, so a high-achieving student from a lower-income family could easily qualify for both, and colleges often combine several awards into one package."},
            ],
        },
        "exit_ticket": {
            "prompt": "In one sentence, explain the difference between a merit-based scholarship and a need-based scholarship.",
        },
        "slide_bullets": [
            "Financial aid = grants + scholarships + work-study + loans",
            "Grants and scholarships: free money, never repaid",
            "Work-study: money you earn through a campus job",
            "Loans: borrowed money, repaid with interest",
            "FAFSA unlocks federal, state, and most college aid",
            "Merit = achievement based, Need = financial situation based",
            "Today: Banzai \"Cost of College\" module",
        ],
        "application": {
            "type": "real_world_problem",
            "title": "Six Weeks, Limited Hours",
            "scenario": "It's the first week of senior year, and a school counselor tells a group of students they realistically have about six hours a week to spend on financial aid work between now and winter break, on top of homework, sports, and jobs. In front of them are four possible uses of that time: filling out the FAFSA (required for almost all aid, takes a few hours total), applying to three local merit scholarships with short essays (a few hours each, competitive but based on grades they already have), applying to two need-based community scholarships requiring a family financial summary (moderate time, no essay), and researching which of their target colleges require the CSS Profile (quick, but only matters if it turns out one does). Every student in the room has the same six hours a week, but different families, grades, and target schools, so the same order of operations will not work for all of them.",
            "task": "Using only the four categories described, write a week-by-week order in which you would tackle them and explain your reasoning for what goes first, second, third, and fourth, assuming you are a student planning to apply to at least one private college.",
        },
        "academic_vocab": {
            "word": "Differentiate",
            "definition": "To recognize or show the difference between two or more things that might otherwise seem similar.",
            "syllables": "dif-uh-REN-shee-ate",
            "morphology": "Latin dis- (apart) + ferre (to carry) + -ate (verb-forming suffix) — literally 'to carry apart.'",
            "example": "Being able to differentiate between a merit scholarship and a need-based scholarship helps you know which parts of your application to focus on strengthening.",
        },
    },
    {
        "day": 45,
        "unit": 5,
        "lesson_in_unit": 2,
        "title": "Filling Out the FAFSA: What It Actually Asks For",
        "objectives": [
            "I can identify the categories of information the FAFSA collects from students and parents.",
            "I can explain what the Expected Family Contribution / Student Aid Index (EFC/SAI) represents.",
            "I can distinguish between the parent contribution and the student contribution within a family's overall aid picture.",
        ],
        "vocab": [
            {"word": "Expected Family Contribution (EFC)/Student Aid Index (SAI)", "definition": "A number generated from FAFSA information that colleges use to estimate how much financial need a student has; it is an index for comparing aid eligibility, not a literal bill a family receives.",
             "example": "Two families with similar incomes can end up with different SAI numbers depending on household size, other kids in college, and savings.",
             "syllables": "ek-SPEK-ted FAM-uh-lee kahn-truh-BYOO-shun / STOO-dent AYD IN-deks", "morphology": "EFC spelled letter by letter (E-F-C) = Expected Family Contribution; SAI spelled letter by letter (S-A-I) = Student Aid Index; 'expected' from Latin ex- (out) + spectare (to look/watch) — literally 'looked forward to.'"},
            {"word": "Parent/Student Contribution", "definition": "The portions of the amount a family is expected to contribute toward college costs that come from parent resources versus the student's own income and assets.",
             "example": "A student's summer job income and savings account count toward the student contribution, separate from what her parents are expected to contribute.",
             "syllables": "PEHR-unt / STOO-dent kahn-truh-BYOO-shun", "morphology": "'Contribution' from Latin com- (together) + tribuere (to give, allot) — literally 'a giving together.'"},
        ],
        "warm_up": "Guess: what percentage of the FAFSA questions do you think are about the student, versus about the student's parents? Write your guess before we look at the real form.",
        "mini_lesson": [
            {"heading": "Inside the FAFSA Form", "body": "The FAFSA collects household size, the number of family members in college, tax return information, income, and basic assets like checking and savings balances, for both the student and, in most cases, at least one parent. It does not ask about home equity in a primary residence or retirement account balances the way some other forms do. The goal is a full but limited financial snapshot of the household."},
            {"heading": "From FAFSA to a Number: EFC/SAI", "body": "All of that information gets run through a federal formula that produces one number: the Expected Family Contribution, recently renamed the Student Aid Index. This is not a bill. It is an index colleges use to compare students against each other and decide how much need-based aid to offer. A lower SAI generally means more eligibility for need-based aid; it does not mean a family will literally pay that exact amount."},
            {"heading": "Two Contributions, One Household", "body": "Within that overall picture, formulas separate out a parent contribution and a student contribution. Student income and assets, like a part-time job's savings, are typically counted at a higher rate than parent assets, which is why a student with a large personal savings account can sometimes see their aid eligibility drop. Understanding this helps families make smarter decisions about where money sits before senior year."},
        ],
        "activity": {
            "title": "Mock FAFSA Family Profile + Banzai \"Paying for College\"",
            "instructions": "Give student pairs a mock family financial profile card (income, household size, one student savings balance) and have them predict whether the family's SAI would go up or down if one detail changed, such as a second sibling starting college or the student's savings account growing. Then have them check their prediction using the aid estimator tool inside the Banzai \"Paying for College\" module with the same mock numbers.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "The Expected Family Contribution / Student Aid Index (EFC/SAI) is best described as:",
                 "choices": ["A. The exact amount a family will be billed by the college", "B. An index colleges use to estimate financial need and compare eligibility", "C. A type of loan", "D. A scholarship only for high-achieving students"], "answer": "B"},
                {"type": "multiple_choice", "q": "Which of these does the FAFSA typically NOT ask about?",
                 "choices": ["A. Household income", "B. Number of family members in college", "C. Home equity in a primary residence", "D. Checking and savings account balances"], "answer": "C"},
                {"type": "multiple_choice", "q": "Student assets and income, compared to parent assets, are generally:",
                 "choices": ["A. Ignored completely by the formula", "B. Counted at a higher rate toward the expected contribution", "C. Only counted if the student is over 25", "D. Counted the exact same way as parent assets"], "answer": "B"},
                {"type": "short_answer", "q": "Why might two families with similar incomes end up with different SAI numbers?",
                 "sample_answer": "Because the formula also factors in household size, how many family members are in college at the same time, and savings or assets, so two families with the same income but different circumstances can land on different SAI numbers."},
            ],
        },
        "exit_ticket": {
            "prompt": "Explain in your own words why the SAI is described as an index rather than a bill.",
        },
        "slide_bullets": [
            "FAFSA asks about income, taxes, household size, and basic assets",
            "Output: one number, the EFC / SAI",
            "SAI = an index for comparing need, not a literal bill",
            "Parent contribution vs. student contribution: both count",
            "Student savings/income often counted at a higher rate",
            "Today: mock family profile + Banzai \"Paying for College\" estimator",
        ],
        "application": {
            "type": "simulation",
            "title": "Two Households, Same Income",
            "scenario": "Household A reports $70,000 in income, one child in college, and $2,000 in the student's own savings account. Household B also reports $70,000 in income, but has two children in college at the same time and $10,000 sitting in the student's own savings account from a part-time job and graduation gifts. Both households have the same parent assets otherwise. Students use a simplified version of the SAI logic from today's mini-lesson: more family members in college at once generally lowers the parent-side contribution, since the same income is being stretched across more students, while student savings and income are counted toward the SAI at a noticeably higher rate than parent savings.",
            "task": "Predict which household will likely end up with a lower SAI, explain which two factors are driving the difference, and propose one legal change Household B's student could make before senior year that might affect their number.",
        },
        "academic_vocab": {
            "word": "Interpret",
            "definition": "To explain the meaning of something, especially something that isn't stated in plain, simple terms.",
            "syllables": "in-TUR-prit",
            "morphology": "Latin inter- (between) + pretium (price, value) — originally one who explains value or meaning between two parties.",
            "example": "Learning to interpret the SAI correctly means understanding it as an index for comparison, not as the literal dollar amount a family will be billed.",
        },
    },
    {
        "day": 46,
        "unit": 5,
        "lesson_in_unit": 3,
        "title": "The Fund: Maya and the FAFSA Kitchen Table",
        "objectives": [
            "I can explain why the FAFSA requires parent financial information, not just student information.",
            "I can describe the emotional and logistical challenges families sometimes face completing the FAFSA.",
            "I can name the CSS Profile as an additional form some colleges require beyond the FAFSA.",
        ],
        "vocab": [
            {"word": "CSS Profile", "definition": "A more detailed financial aid form run by the College Board, required by some, mostly private, colleges in addition to the FAFSA, used to award their own institutional aid money.",
             "example": "Priya had to complete the CSS Profile for her college, which asked about things the FAFSA never mentioned, like home equity.",
             "syllables": "C-S-S (spelled out) PROH-fyl", "morphology": "CSS = College Scholarship Service, the College Board division that originally created the form; 'Profile' from Latin pro- (forward) + filum (thread) — literally a sketch or outline, here of a family's finances."},
        ],
        "warm_up": "Have you ever had to share something private, like grades or family money stuff, with an adult outside your family and felt weird about it? What made it feel okay, or not okay?",
        "mini_lesson": [
            {"heading": "Why Parents Are Part of the Form", "body": "The FAFSA asks for parent financial information because most students applying to college are still considered financially dependent on their parents, at least by federal rules, regardless of how independent they feel. Colleges and the government use household income and assets, not just the student's own numbers, to estimate how much of the cost a family can realistically cover. That is also exactly why filling it out can feel invasive: it is genuinely asking a family to hand over private financial details."},
            {"heading": "A Second Form for Some Schools: The CSS Profile", "body": "The FAFSA is not always the only form. Some colleges, mostly private ones, also require the CSS Profile before they will finalize an institutional aid offer. It asks more detailed questions than the FAFSA, including things like home equity and retirement savings, because that aid comes out of the college's own budget rather than federal funds. Not every student needs it, only students applying to schools that specifically require it."},
        ],
        "activity": {
            "title": "FAFSA Document Checklist Scavenger Hunt",
            "instructions": "In pairs, have students use the general FAFSA information-category list, without using any real personal data, to build a checklist of documents a typical family would need to gather: tax returns, W-2s, bank statements, and records of untaxed income. Ask pairs to discuss, like Maya's family did in today's reading, why colleges want this much detail rather than simply asking a family to state their income in one sentence.",
        },
        "reading": {
            "type": "realistic_fiction",
            "title": "The Fund: Kitchen Table",
            "body": "Deshawn's waitlist letdown from two weeks ago was still fresh when Maya sat down at her own kitchen table with a folder marked FAFSA in blue Sharpie. Mr. Alvarez's whole speech about waitlists being a process, not a verdict, had helped Deshawn get through it. Maya wondered if anything would make this next part feel less like a verdict on her own family.\n\n\"Mom, I need your W-2,\" Maya said, laptop open to the FAFSA login screen. \"And last year's tax return. And how much is in the savings account.\"\n\nHer mom looked up from the sink. \"Why does the government need to know what's in our savings account?\"\n\n\"Because it's need-based aid. They can't give more money to people who need it more if they don't know who actually needs it more.\"\n\n\"So a stranger in Washington gets to know our whole financial life.\"\n\n\"It's not a stranger, it's a formula.\" Maya knew that wasn't really an answer, but it was the only one she had.\n\nHer mom sat down anyway, reading glasses pushed up into her hair, and started digging through the folder of tax documents on the counter. \"Your sister didn't have this many questions.\"\n\n\"Priya did the CSS Profile too, remember? That one asked for even more, home equity, how much is in your retirement account, all of it.\" Maya scrolled to the household size question. \"This is just the FAFSA. It's supposed to be the easier one.\"\n\n\"Easier.\" Her mom read the income section over Maya's shoulder and went quiet for a second. \"It still feels like handing someone your whole life on a form.\"\n\n\"I get it.\" Maya did get it, actually, watching her mom's shoulders tense at every new field made the whole thing feel less like paperwork and more like being examined. \"But Deshawn's family hasn't even started theirs. His mom works two jobs and doesn't do her own taxes until the last week of April. He's going to be way more stressed than us.\"\n\n\"Then help him when we're done.\" Her mom clicked into the next field before Maya could argue, the untaxed income question, and read it twice before answering.\n\nThey didn't finish that night. But by the time Maya closed the laptop, the folder marked FAFSA had a checkmark in Sharpie next to \"parent info,\" and her mom had stopped asking why and started asking what came next.",
            "questions": [
                "Why does the FAFSA need Maya's mom's financial information, not just Maya's own information?",
                "What does Maya mean when she tells her mom the FAFSA is \"a formula,\" not \"a stranger\"? Do you think that's a fair way to describe it?",
                "How does Priya's CSS Profile experience get brought up in this scene, and what does it suggest about why some forms ask for more detail than the FAFSA?",
                "Why might Deshawn's family have a harder time with the FAFSA timeline than Maya's family does?",
                "Have you, or would you, feel the same friction Maya's mom feels about sharing financial details for aid? Why or why not?",
            ],
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "In the reading, why does Maya say the FAFSA needs her mom's financial information?",
                 "choices": ["A. Because her mom is required to co-sign every loan", "B. Because the FAFSA is need-based aid, and eligibility depends on household finances", "C. Because Maya is not old enough to fill it out alone", "D. Because the CSS Profile requires it, not the FAFSA"], "answer": "B"},
                {"type": "multiple_choice", "q": "Which form does the reading say Priya, Maya's sister, also had to complete, which asked for even more detail?",
                 "choices": ["A. The Common App", "B. The CSS Profile", "C. A W-4", "D. A FAFSA4caster preview"], "answer": "B"},
                {"type": "short_answer", "q": "Based on the reading and the mini-lesson, explain in your own words why filling out the FAFSA can feel invasive even though it serves a clear purpose.",
                 "sample_answer": "It asks a family to share private details like income, taxes, and savings with the government, which can feel exposing even though that information is what lets colleges figure out how much need-based aid a family actually qualifies for."},
            ],
        },
        "exit_ticket": {
            "prompt": "Name one piece of information the FAFSA asks for and explain, in one sentence, why colleges need it.",
        },
        "slide_bullets": [
            "Today: reading, \"The Fund: Kitchen Table\"",
            "FAFSA requires parent info because most students are dependents",
            "Sharing financial details can feel invasive, even with a clear purpose",
            "CSS Profile: a second, more detailed form some colleges require",
            "Discuss: why colleges ask for this much detail",
        ],
        "application": {
            "type": "case_study",
            "title": "Whose Numbers Count?",
            "scenario": "Jordan's parents divorced three years ago. Jordan lives with their mom most of the year but spends every other weekend and most of the summer with their dad, who has a significantly higher income. When it's time to fill out the FAFSA, Jordan assumes both parents' incomes need to be reported, since both are legally still Jordan's parents. Jordan's mom says only the parent Jordan lived with more over the past year counts for the FAFSA, but mentions that if Jordan applies anywhere that requires the CSS Profile, the rules might be different and could ask about the other parent's finances too.",
            "task": "Explain whether Jordan's mom is describing the FAFSA rule accurately, and identify what additional information Jordan would need to find out about a specific college's CSS Profile requirements before assuming the same rule applies there.",
        },
        "academic_vocab": {
            "word": "Perspective",
            "definition": "A particular way of viewing or understanding a situation, often shaped by someone's own experience.",
            "syllables": "per-SPEK-tiv",
            "morphology": "Latin per- (through) + specere (to look) — literally 'a looking through.'",
            "example": "Maya's mom's perspective on the FAFSA, that it feels like handing a stranger her whole financial life, is different from Maya's more practical perspective on the same form.",
        },
    },
    {
        "day": 47,
        "unit": 5,
        "lesson_in_unit": 4,
        "title": "Two Forms, One Goal: FAFSA vs. CSS Profile",
        "objectives": [
            "I can explain why some colleges require the CSS Profile in addition to the FAFSA.",
            "I can identify which types of institutions typically require the CSS Profile.",
            "I can define grants and explain how they differ from scholarships and loans.",
        ],
        "vocab": [
            {"word": "Grants", "definition": "Money for college that does not have to be repaid, awarded based on financial need, usually funded by the federal government, a state, or a college itself.",
             "example": "The federal Pell Grant is awarded based on financial need and never has to be paid back.",
             "syllables": "GRANTS (one syllable)", "morphology": "From Old French granter, tracing to Latin credentem (believing, entrusting) — literally 'something entrusted to you.'"},
        ],
        "warm_up": "Before today's reading, guess: do you think every college in the country uses the same financial aid form, or do some colleges use extra forms? Why might that be?",
        "mini_lesson": [
            {"heading": "The FAFSA, Reviewed", "body": "Every college that participates in federal aid programs, which is nearly all of them, uses the FAFSA to determine eligibility for federal grants, federal work-study, federal loans, and most state aid programs. It is the baseline form every college-bound student should complete, regardless of what school they end up choosing or how much money their family makes."},
            {"heading": "The CSS Profile, Explained", "body": "The CSS Profile is run by the College Board and used by roughly 200 mostly private colleges to award their own institutional aid, money that comes from the college's own budget rather than the federal government. Because it is the college's own money, it asks deeper questions than the FAFSA: home equity, retirement savings, sometimes even a noncustodial parent's finances in divorced households. It often comes with a processing fee, though fee waivers exist."},
            {"heading": "Grants: A Third Kind of Free Money", "body": "Grants are similar to need-based scholarships in that they never have to be repaid, but they typically come from a government source, like the federal Pell Grant, or directly from a college, rather than from a private organization or individual donor. Both the FAFSA and, for some schools, the CSS Profile can determine eligibility for different grants."},
        ],
        "activity": {
            "title": "Which Form Do I Need? + Banzai \"Paying for College\"",
            "instructions": "Give student pairs a stack of college name cards mixing public universities, private colleges known for requiring the CSS Profile, and community colleges, and have them sort each into \"FAFSA only\" or \"FAFSA plus CSS Profile\" based on what they can find on that college's own financial aid page. Then have students check two or three schools they are personally considering inside the Banzai \"Paying for College\" module to confirm which forms those schools actually require.",
        },
        "reading": {
            "type": "informational",
            "title": "FAFSA vs. CSS Profile: Why Two Forms Exist and Who Needs Which One",
            "body": "Every year, millions of students fill out the FAFSA, the Free Application for Federal Student Aid, to qualify for federal grants, work-study, and loans. But some students find out partway through senior year that the FAFSA is only step one. A second form, the CSS Profile, is required by certain colleges before they will finalize an aid offer. Understanding why both exist can save families a lot of stress in the fall.\n\nThe FAFSA is the federal government's form. Every college in the country that participates in federal aid programs uses it, and it determines eligibility for the Pell Grant, federal work-study, federal student loans, and most state grant programs. It asks about income, taxes, household size, and basic assets like checking and savings balances.\n\nThe CSS Profile, run by the College Board, the same organization behind the SAT, is used by roughly 200 mostly private colleges and universities to award their own institutional aid, money that comes from the college's own budget, not the federal government. Because that money is the college's to give away, the CSS Profile asks deeper questions: home equity, retirement account balances, and sometimes financial details about a noncustodial parent in divorced or separated households. It also usually comes with a processing fee, though fee waivers are available for lower-income families.\n\nThe rule of thumb: every student planning to attend college should complete the FAFSA. Only students applying to schools that specifically require the CSS Profile, almost always selective private colleges, need to complete both. Checking each college's financial aid website early in the application process is the only reliable way to know which form applies.\n\n(Adapted from a Federal Student Aid consumer guide)",
            "questions": [
                "Which form does every college-bound student need to complete, regardless of where they apply?",
                "What kind of colleges typically require the CSS Profile in addition to the FAFSA?",
                "Why does the CSS Profile ask more detailed questions than the FAFSA?",
                "What is one piece of financial information the CSS Profile might ask about that the FAFSA does not?",
                "Based on this reading, how would you find out whether a specific college you're interested in requires the CSS Profile?",
            ],
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "According to the reading, which organization runs the CSS Profile?",
                 "choices": ["A. The federal Department of Education", "B. The College Board", "C. Individual state governments", "D. Each college independently"], "answer": "B"},
                {"type": "multiple_choice", "q": "Which of these is something the CSS Profile might ask about that the FAFSA typically does not?",
                 "choices": ["A. Household income", "B. Home equity", "C. Household size", "D. Whether the student filed taxes"], "answer": "B"},
                {"type": "multiple_choice", "q": "A grant is best described as:",
                 "choices": ["A. Borrowed money that must be repaid with interest", "B. Money earned through a part-time campus job", "C. Free money awarded based on financial need, often from a government or college source", "D. A form used only by private colleges"], "answer": "C"},
                {"type": "short_answer", "q": "A student is applying to two public state universities and one selective private college. Which financial aid forms will they most likely need to complete, and why?",
                 "sample_answer": "They will need to complete the FAFSA for all three schools since it's required almost everywhere, and they will likely also need the CSS Profile for the private college if that college uses it to award its own institutional aid."},
            ],
        },
        "exit_ticket": {
            "prompt": "Explain in one or two sentences how you would find out whether a college you're interested in requires the CSS Profile in addition to the FAFSA.",
        },
        "slide_bullets": [
            "FAFSA: used by nearly every college, determines federal/state aid",
            "CSS Profile: used by ~200 mostly private colleges for their own aid",
            "CSS Profile asks deeper questions: home equity, retirement savings",
            "Grants: free money, need-based, from government or college sources",
            "Rule of thumb: everyone does FAFSA, only some also do CSS Profile",
            "Today: reading + college sorting activity + Banzai check",
        ],
        "application": {
            "type": "real_world_problem",
            "title": "Closing the Gap With Grants",
            "scenario": "A public university's total cost of attendance is $24,500 for the year. A student's FAFSA results qualify them for a federal Pell Grant of $6,895 and a state grant of $3,200, both of which are gift aid that never has to be repaid. The student's family, based on their SAI, is expected to contribute $9,000 from their own resources for the year.",
            "task": "Calculate how much of the $24,500 cost is still uncovered after the grants and the family contribution are applied, and explain whether that remaining gap would most likely need to be filled by scholarships, work-study, loans, or some mix, based on what you know so far about each type of aid.",
        },
        "academic_vocab": {
            "word": "Categorize",
            "definition": "To sort things into groups based on shared characteristics.",
            "syllables": "KAT-uh-gor-yze",
            "morphology": "Greek kata- (down, against) + agoreuein (to declare publicly, speak in the assembly) — the root of 'category,' a class or division something is sorted into.",
            "example": "Today's activity asks you to categorize colleges as 'FAFSA only' or 'FAFSA plus CSS Profile' based on what each school's aid office actually requires.",
        },
    },
    {
        "day": 48,
        "unit": 5,
        "lesson_in_unit": 5,
        "title": "Work-Study, Award Letters, and Building Your Aid Package",
        "objectives": [
            "I can explain how work-study jobs function and how they differ from a regular part-time job.",
            "I can describe how grants, scholarships, work-study, and loans combine into a full financial aid package.",
            "I can evaluate a sample financial aid award letter to identify which parts are free money versus money to repay.",
        ],
        "vocab": [
            {"word": "Work-Study", "definition": "A federally funded program that provides part-time campus jobs to help students earn money toward college costs while enrolled.",
             "example": "Instead of applying to a coffee shop near campus, a student awarded work-study might take a part-time job in the college library that counts toward her financial aid package.",
             "syllables": "WURK-STUH-dee", "morphology": "Compound word: 'work' (labor, job) + 'study' from Latin studium (zeal, application) — used here to mean 'while enrolled as a student.'"},
        ],
        "warm_up": "If a financial aid award letter said you were getting $20,000 in total aid, what's the very first question you'd want answered before getting excited about that number?",
        "mini_lesson": [
            {"heading": "What Work-Study Actually Is", "body": "Work-study is a federal program, funded partly by the government and partly by the college, that creates part-time jobs specifically reserved for students who were awarded it through their financial aid application. It is not automatic; a student has to qualify and then actually find and apply for an available work-study position on campus. The pay counts as income the student earns during the school year, which helps cover costs like books or personal expenses, but it is not a lump sum handed over at the start of the term."},
            {"heading": "Building the Full Aid Package", "body": "A college combines all the pieces, grants, scholarships, work-study, and loans, into one document called an award letter or financial aid offer. The total cost of attendance minus all the aid offered equals what a family is actually expected to pay out of pocket. Two schools with the same sticker price can end up costing very different amounts once their award letters are compared side by side."},
            {"heading": "Reading an Award Letter Like a Pro", "body": "The most important skill is separating gift aid, grants and scholarships that never get repaid, from self-help aid, work-study and loans that require either work or repayment. A package that looks large on paper but is mostly loans is a very different deal than one with the same total number made up mostly of grants. A red flag worth watching for is a package that leans heavily on loans to close a large gap."},
        ],
        "activity": {
            "title": "Banzai \"Paying for College\" Award Letter Breakdown",
            "instructions": "Have students complete the Banzai \"Paying for College\" module simulation, entering a sample award letter to see the automatic breakdown between grants, scholarships, work-study, and loans. Ask each student to calculate what percentage of their sample package is free money versus borrowed money, and to flag anything that looks like a red flag, such as loans making up more than half the offer.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which of these best describes work-study?",
                 "choices": ["A. A grant paid in one lump sum", "B. A federally funded part-time job program for students who qualify through their aid application", "C. A type of scholarship for high test scores", "D. A loan with no interest"], "answer": "B"},
                {"type": "multiple_choice", "q": "In an award letter, gift aid refers to:",
                 "choices": ["A. Money like grants and scholarships that never has to be repaid", "B. Loans with low interest rates", "C. Work-study earnings only", "D. The total cost of attendance"], "answer": "A"},
                {"type": "multiple_choice", "q": "A red flag when reading an award letter is a package that:",
                 "choices": ["A. Is made up mostly of grants and scholarships", "B. Includes a small work-study offer", "C. Relies heavily on loans to close most of the cost gap", "D. Lists the total cost of attendance clearly"], "answer": "C"},
                {"type": "short_answer", "q": "Two schools offer the same total dollar amount of aid, but one package is mostly grants and the other is mostly loans. Which package is the better deal, and why?",
                 "sample_answer": "The package that is mostly grants is the better deal because that money never has to be repaid, while the loan-heavy package means the student will owe most of that amount back later, with interest."},
            ],
        },
        "exit_ticket": {
            "prompt": "Looking back at the whole unit, name one piece of financial aid you would prioritize applying for first and explain why.",
        },
        "slide_bullets": [
            "Work-study: part-time campus job, only for students awarded it",
            "Award letter = grants + scholarships + work-study + loans, all in one",
            "Cost of attendance minus aid = out-of-pocket cost",
            "Gift aid (never repaid) vs. self-help aid (work or repay)",
            "Red flag: an offer leaning heavily on loans",
            "Today: Banzai \"Paying for College\" award letter simulation",
            "Unit 5 wrap-up: FAFSA, CSS Profile, EFC/SAI, grants, scholarships, work-study",
        ],
        "application": {
            "type": "realistic_fiction",
            "title": "Two Envelopes",
            "scenario": "Deshawn gets two thin envelopes on the same afternoon, both award letters. The first, from a four-year university, lists $18,000 in total aid: $4,000 Pell Grant, $2,000 institutional scholarship, $2,000 work-study, and $10,000 in loans. The second, from a smaller college with a higher sticker price, lists $22,000 in total aid: $9,000 in grants, $6,000 in merit scholarships, $2,000 work-study, and $5,000 in loans. Deshawn's first reaction is to text his mom, \"22 beats 18, easy choice,\" before he's looked at anything besides the total dollar amount at the top of each letter.",
            "task": "Recalculate what portion of each award letter is gift aid (grants and scholarships) versus money that must be earned or repaid, and write a two-sentence text back to Deshawn explaining which offer is actually the stronger deal and why the totals alone were misleading him.",
        },
        "academic_vocab": {
            "word": "Evaluate",
            "definition": "To carefully judge the value, quality, or significance of something.",
            "syllables": "ee-VAL-yoo-ate",
            "morphology": "Latin e- (out) + valere (to be strong, be worth) — literally 'to draw out the worth of something.'",
            "example": "To evaluate a financial aid award letter fairly, you have to look past the total number and check how much is gift aid versus loans.",
        },
    },
]
