UNIT_8_META = {
    "number": 8,
    "name": "Investing, Growth & Certification Review",
    "essential_question": "What investment options maximize financial resources, and am I ready for the GFL exam?",
    "overview": "This unit introduces the basic tools people use to grow money over time: stocks, bonds, mutual funds, cryptocurrency, retirement accounts, and the risk-reward-liquidity tradeoffs behind each one. The final four days shift into structured review and a practice exam covering every domain of the YouScience General Financial Literacy (GFL) certification, so students leave the semester both financially literate and certification-ready.",
    "vocabulary_bank": [
        {"word": "Risk", "definition": "The chance that an investment could lose value or not perform the way you hoped.",
         "syllables": "RISK (one syllable)", "morphology": "Possibly from Italian risco/rischio or Greek rhiza (root, cliff), via early nautical use describing the hazard of sailing close to a cliff or rock."},
        {"word": "Reward", "definition": "The potential gain or payoff you could earn from an investment or financial decision.",
         "syllables": "rih-WORD", "morphology": "Old North French rewarder (to look back at, to regard): re- (again) + warder (to watch, guard)."},
        {"word": "Stocks", "definition": "A share of ownership in a company; stock value rises and falls with how the company (and the market) performs.",
         "syllables": "STAHKS (one syllable)", "morphology": "Old English stocc (tree trunk, stump); came to mean a merchant's stored trading capital or 'stock' of goods, later shares of a company."},
        {"word": "Bonds", "definition": "A loan you make to a company or government that pays you back with interest over a set period of time.",
         "syllables": "BAHNDZ (one syllable)", "morphology": "Middle English band/bond, from Old Norse band ('something that binds') — a bond legally 'binds' the borrower to repay."},
        {"word": "Mutual Funds", "definition": "A pooled investment that buys many different stocks and/or bonds at once, managed by a professional fund manager.",
         "syllables": "MYOO-choo-uhl fundz", "morphology": "Latin mutuus (borrowed, reciprocal, exchanged) + 'fund,' from Latin fundus (bottom, base)."},
        {"word": "Crypto(currency)", "definition": "A digital currency, like Bitcoin, that is not controlled by a government or bank and can be extremely volatile in value.",
         "syllables": "KRIP-toh KUR-en-see", "morphology": "Greek kryptos (hidden, secret) + 'currency,' from Latin currere (to run) — money that 'runs' or circulates, here 'hidden' by cryptography."},
        {"word": "Liquidity", "definition": "How quickly and easily an asset can be turned into usable cash without losing value.",
         "syllables": "lih-KWID-ih-tee", "morphology": "Latin liquidus (flowing, liquid) + -ity (noun suffix) — literally 'the quality of flowing freely.'"},
        {"word": "Growth", "definition": "An increase in the value of money or an investment over time.",
         "syllables": "GROHTH (one syllable)", "morphology": "Old Norse groa (to grow) + -th (noun-forming suffix, as in 'width' or 'depth')."},
        {"word": "Compound Interest", "definition": "Interest calculated on both the original amount saved or invested and on the interest that has already been added to it.",
         "syllables": "KAHM-pownd IN-trist", "morphology": "'Compound': Latin com- (together) + ponere (to put); 'interest': Latin inter- (between) + esse (to be) — literally 'to be between/to matter.'"},
        {"word": "401(k)", "definition": "An employer-sponsored retirement account, often with pre-tax contributions and sometimes an employer match.",
         "syllables": "FOR-oh-WUN-KAY", "morphology": "Not an acronym but a legal citation: refers to Section 401, subsection (k), of the U.S. Internal Revenue Code, which created this type of retirement plan."},
        {"word": "Roth IRA", "definition": "An individual retirement account funded with after-tax money, where qualified withdrawals in retirement are tax-free.",
         "syllables": "RAHTH EYE-AR-AY", "morphology": "'Roth' is named for U.S. Senator William Roth, who sponsored the legislation; 'IRA' is an acronym: I = Individual, R = Retirement, A = Account."},
        {"word": "Diversification", "definition": "Spreading money across different types of investments to reduce overall risk.",
         "syllables": "dih-VER-suh-fih-KAY-shun", "morphology": "Latin diversus (turned in different directions): dis- (apart) + vertere (to turn) + -fication (the act of making) — 'the act of making varied.'"},
        {"word": "Dividend", "definition": "A portion of a company's profit paid out to shareholders, usually on a regular schedule.",
         "syllables": "DIV-ih-dend", "morphology": "Latin dividendum ('thing to be divided'), from dividere (to divide) — profit divided among shareholders."},
    ],
    "unit_assessment": {
        "title": "Unit 8 Assessment",
        "questions": [
            {"type": "multiple_choice", "q": "Which statement best describes the general relationship between risk and reward?",
             "choices": ["A. Higher risk always guarantees a higher reward.", "B. Investments with more potential reward usually carry more risk.", "C. Risk and reward have no real connection.", "D. Reward only matters for retirement accounts."], "answer": "B"},
            {"type": "multiple_choice", "q": "A share of ownership in a company is called a:",
             "choices": ["A. Bond", "B. Mutual fund", "C. Stock", "D. Dividend"], "answer": "C"},
            {"type": "multiple_choice", "q": "Which asset is generally the MOST liquid?",
             "choices": ["A. A house", "B. A savings account", "C. A 10-year bond", "D. A retirement account with an early withdrawal penalty"], "answer": "B"},
            {"type": "multiple_choice", "q": "What is the main difference between a 401(k) and a Roth IRA?",
             "choices": ["A. A 401(k) is only for teachers; a Roth IRA is for everyone else.", "B. A 401(k) typically uses pre-tax dollars through an employer; a Roth IRA uses after-tax dollars you open yourself.", "C. A Roth IRA can only be opened after age 50.", "D. There is no real difference."], "answer": "B"},
            {"type": "multiple_choice", "q": "Buying a mutual fund instead of a single stock is one way to increase:",
             "choices": ["A. Risk", "B. Diversification", "C. Liquidity only", "D. Dividend rate"], "answer": "B"},
            {"type": "multiple_choice", "q": "Why is cryptocurrency generally considered a higher-risk investment than a savings account?",
             "choices": ["A. It is illegal in most states.", "B. Its value can swing dramatically in short periods of time.", "C. It always loses value over time.", "D. Banks control its price."], "answer": "B"},
            {"type": "short_answer", "q": "Explain compound interest in your own words and describe why starting to invest at age 18 instead of age 28 can make a big difference.", "sample_answer": "Compound interest is interest earned on both your original money and on interest you've already earned, so your money grows faster the longer it sits. Starting at 18 gives your money ten extra years to compound, which can add up to tens of thousands of dollars more by retirement even if you invest the same monthly amount as someone who starts at 28."},
            {"type": "short_answer", "q": "Describe one real tradeoff between risk, reward, and liquidity someone might face when deciding where to put their savings.", "sample_answer": "Someone could keep money in a savings account for safety and easy access (high liquidity, low risk, low reward), or invest it in stocks for potentially higher growth, but they'd have less certainty and less easy access to that exact amount of cash if they needed it quickly."},
            {"type": "short_answer", "q": "What is a dividend, and how could it factor into someone's decision to buy a particular stock?", "sample_answer": "A dividend is a portion of a company's profit paid to shareholders on a regular schedule. Someone might choose a dividend-paying stock if they want steady income from their investment in addition to any growth in the stock's price."},
            {"type": "short_answer", "q": "Name two of the five GFL exam domains and one topic covered under each.", "sample_answer": "Saving & Investment covers topics like compound interest and comparing a 401(k) to a Roth IRA. Personal Money Management covers topics like budgeting and understanding your FICO credit score."},
        ],
    },
    "days": [72, 82],
}

UNIT_8_LESSONS = [
    {
        "day": 72,
        "unit": 8,
        "lesson_in_unit": 1,
        "title": "Risk and Reward: The Foundation of Investing",
        "objectives": [
            "I can explain the relationship between risk and reward in investing.",
            "I can identify my own risk tolerance based on age, goals, and timeline.",
        ],
        "vocab": [
            {"word": "Risk", "definition": "The chance that an investment could lose value or not perform the way you hoped.",
             "example": "Putting all your savings into one small company's stock is high risk because that one company's success isn't guaranteed.",
             "syllables": "RISK (one syllable)", "morphology": "Possibly from Italian risco/rischio or Greek rhiza (root, cliff), via early nautical use describing the hazard of sailing close to a cliff or rock."},
            {"word": "Reward", "definition": "The potential gain or payoff you could earn from an investment or financial decision.",
             "example": "The reward of investing early is that your money has more time to grow before you need it.",
             "syllables": "rih-WORD", "morphology": "Old North French rewarder (to look back at, to regard): re- (again) + warder (to watch, guard)."},
        ],
        "warm_up": "Would you rather have a guaranteed $50 today, or a coin-flip chance at $150? Write down your choice and explain why in one sentence.",
        "mini_lesson": [
            {"heading": "What Is Risk?", "body": "Risk is the chance that something you invest in loses value, underperforms, or doesn't pay off the way you expected. Every financial decision carries some risk, even keeping cash under your mattress carries the risk of inflation quietly shrinking its value. Investments are usually described as low-risk, medium-risk, or high-risk depending on how much their value can swing and how likely you are to lose money in the short term."},
            {"heading": "What Is Reward?", "body": "Reward is the payoff you're hoping to get in exchange for taking on that risk. This could be growth in value, interest, or dividends paid out over time. Generally, the market only offers bigger potential rewards to investors willing to accept bigger potential risk. There's no legitimate investment that offers huge rewards with zero risk. If something claims that, be very skeptical."},
            {"heading": "The Risk-Reward Tradeoff", "body": "Financial planning is largely about matching risk to your timeline and goals. A 17-year-old saving for retirement in 50 years can usually afford more risk, because there's time to recover from a bad year. Someone who needs cash next month for a car repair should not put it somewhere risky. Over this unit, you'll learn where stocks, bonds, mutual funds, crypto, and retirement accounts each fall on this risk-reward spectrum."},
        ],
        "activity": {
            "title": "The Risk Ladder",
            "instructions": "Give each student a set of five cards labeled Savings Account, Bonds, Mutual Fund, Stocks, and Cryptocurrency. Have students physically arrange the cards on their desk from lowest risk to highest risk based on gut instinct before any instruction on those specific tools. Collect a quick class tally on the board, then tell students they'll revisit this exact ranking at the end of the unit to see what's changed.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which best defines financial risk?",
                 "choices": ["A. A guaranteed loss of money", "B. The chance an investment loses value or underperforms", "C. A tax penalty", "D. The interest rate a bank offers"], "answer": "B"},
                {"type": "multiple_choice", "q": "Generally speaking, investments that offer a bigger potential reward also tend to carry:",
                 "choices": ["A. No risk at all", "B. Less risk than safer options", "C. More risk", "D. A fixed government guarantee"], "answer": "C"},
                {"type": "multiple_choice", "q": "A 17-year-old investing money for retirement 50 years from now can typically afford to:",
                 "choices": ["A. Take on more risk since there's time to recover from bad years", "B. Take on zero risk no matter what", "C. Avoid all investing until age 40", "D. Only use cash under a mattress"], "answer": "A"},
                {"type": "short_answer", "q": "If someone tells you about an investment that promises huge rewards with zero risk, what should you think?", "sample_answer": "You should be skeptical, because no legitimate investment offers a large reward without some real risk attached; that combination is a warning sign of a scam."},
            ],
        },
        "exit_ticket": {
            "prompt": "In one or two sentences, describe your own risk tolerance right now and one factor (age, goals, savings cushion) that shapes it.",
        },
        "slide_bullets": [
            "Unit 8: Investing, Growth & Certification Review begins today",
            "Risk = chance an investment loses value or underperforms",
            "Reward = the payoff you're hoping to earn",
            "Bigger potential reward usually means bigger potential risk",
            "Your timeline (when you need the money) shapes how much risk makes sense",
            "Today's Risk Ladder ranking: we'll revisit it at the end of the unit",
        ],
        "application": {
            "type": "simulation",
            "title": "Three Envelopes",
            "scenario": "At the front of the room, a teacher presents three sealed envelopes, each representing a different investment choice for $100 of pretend money. Envelope A is labeled 'Guaranteed': open it and you get exactly $80, no chance involved. Envelope B is labeled 'Coin Flip': there's a 50% chance of getting $200 and a 50% chance of getting $0. Envelope C is labeled 'Long Shot': there's a 10% chance of getting $1,000 and a 90% chance of getting $0. Before anything is opened, every student has to commit in writing to one envelope and explain why, based on their own risk tolerance, not on guessing which envelope will actually win today. The exercise isn't really about the money in the envelope. It's about noticing that three very different, reasonable people in the same room can look at the exact same three options and land on three completely different, defensible choices.",
            "task": "Calculate the expected value of each envelope (multiply each outcome by its probability and add the results together). Then choose which envelope you personally would pick if this were real money, and explain your choice in two to three sentences using your own risk tolerance, not just the expected value number.",
        },
        "academic_vocab": {
            "word": "Assess",
            "definition": "To carefully consider something in order to judge its value, condition, or importance.",
            "syllables": "uh-SES",
            "morphology": "Latin ad- (to) + sedere (to sit) — originally described a judge who would 'sit beside' to determine a case.",
            "example": "Before choosing where to put your money, you have to assess how much risk you're actually comfortable taking on.",
        },
    },
    {
        "day": 73,
        "unit": 8,
        "lesson_in_unit": 2,
        "title": "Stocks and Bonds: Owning vs. Lending",
        "objectives": [
            "I can explain the difference between owning a stock and holding a bond.",
            "I can read the basic parts of a stock chart, including ticker symbol and price movement.",
        ],
        "vocab": [
            {"word": "Stocks", "definition": "A share of ownership in a company; stock value rises and falls with how the company (and the market) performs.",
             "example": "When you buy a stock, you own a tiny slice of that company and share in its ups and downs.",
             "syllables": "STAHKS (one syllable)", "morphology": "Old English stocc (tree trunk, stump); came to mean a merchant's stored trading capital or 'stock' of goods, later shares of a company."},
            {"word": "Bonds", "definition": "A loan you make to a company or government that pays you back with interest over a set period of time.",
             "example": "Buying a government bond means you're lending the government money in exchange for regular interest payments.",
             "syllables": "BAHNDZ (one syllable)", "morphology": "Middle English band/bond, from Old Norse band ('something that binds') — a bond legally 'binds' the borrower to repay."},
        ],
        "warm_up": "If you lend a friend $20 and they pay you back $22 next month, is that more like owning part of their business, or more like a loan? Explain.",
        "mini_lesson": [
            {"heading": "Stocks: You Become a Part Owner", "body": "When you buy a stock, you're buying a small piece of ownership in a company. If the company does well and grows, your share is usually worth more, and you can sell it for a profit. If the company struggles, your share can lose value. Stock prices move up and down every single day based on how investors feel about a company's performance and future."},
            {"heading": "Bonds: You Become a Lender", "body": "When you buy a bond, you are not an owner, you're a lender. You give a company or government your money for a set period of time, and in exchange they pay you back with interest on a schedule. Bonds are generally more predictable and lower-risk than stocks, but they also usually offer a lower potential reward."},
            {"heading": "Reading a Basic Stock Chart", "body": "A stock chart tracks a company's share price over time, usually shown as a line or set of bars moving up and down across days, months, or years. Each company has a ticker symbol, a short code of letters that identifies it, like AAPL for Apple. When the line trends upward over time, the price is growing; when it dips, the price is falling. One bad day doesn't tell you much, long-term trends matter more."},
        ],
        "activity": {
            "title": "Stock Chart Basics (Banzai)",
            "instructions": "Have students complete the Banzai 'Stock Chart Basics' module in pairs, identifying the ticker symbol, the highest and lowest price shown, and the overall trend direction for two sample companies. Afterward, each pair picks one company and writes a two-sentence pitch for why they would or would not invest in it based only on the chart. Share a few pitches out loud and discuss what the chart does and doesn't tell you.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "When you buy a stock, you become:",
                 "choices": ["A. A lender to the company", "B. A partial owner of the company", "C. An employee of the company", "D. A tax collector for the company"], "answer": "B"},
                {"type": "multiple_choice", "q": "A bond is best described as:",
                 "choices": ["A. Ownership in a company", "B. A loan you make that pays back with interest", "C. A type of savings account", "D. A digital currency"], "answer": "B"},
                {"type": "multiple_choice", "q": "A ticker symbol is:",
                 "choices": ["A. The interest rate on a bond", "B. A short code of letters that identifies a company on the stock market", "C. A government tax form", "D. The number of shares you own"], "answer": "B"},
                {"type": "short_answer", "q": "Which generally carries more risk, a stock or a bond, and why?", "sample_answer": "A stock generally carries more risk because its value depends on how well the company performs and can swing up or down significantly, while a bond pays a more predictable, scheduled interest amount."},
            ],
        },
        "exit_ticket": {
            "prompt": "In your own words, explain the difference between owning a stock and holding a bond.",
        },
        "slide_bullets": [
            "Stocks = ownership; Bonds = lending",
            "Stock value rises and falls with company performance",
            "Bonds pay scheduled interest and are generally lower-risk",
            "Ticker symbol = short code identifying a company (example: AAPL)",
            "Stock charts show price trends over time, not just one day",
            "Today's activity: Banzai Stock Chart Basics",
        ],
        "application": {
            "type": "real_world_problem",
            "title": "One Year, Two Investments",
            "scenario": "A student invests $500 in a single company's stock at the start of the year. By year's end, the stock's price has dropped 12%, and the company didn't pay a dividend that year. A second student invests $500 in a corporate bond paying 5% annual interest, and at year's end the bond pays that interest and returns the original $500 in full since it hasn't matured yet. Both students started with the exact same amount of money on the exact same day. One of them is frustrated after watching market news all year expecting the stock to recover, while the other barely thought about their bond after buying it.",
            "task": "Calculate the dollar value each student's investment is worth at the end of the year. Then explain, using what you know about stocks versus bonds, why one investment's value could swing so much more than the other's over the exact same twelve months.",
        },
        "academic_vocab": {
            "word": "Differentiate",
            "definition": "To recognize or show the difference between two or more things.",
            "syllables": "dif-uh-REN-shee-ayt",
            "morphology": "Latin dis- (apart) + ferre (to carry) + -ate — literally 'to carry apart,' i.e., to separate and distinguish.",
            "example": "Today's lesson helps you differentiate between owning a stock and holding a bond.",
        },
    },
    {
        "day": 74,
        "unit": 8,
        "lesson_in_unit": 3,
        "title": "Mutual Funds, Diversification, and Crypto: Spreading (or Not Spreading) Risk",
        "objectives": [
            "I can explain how a mutual fund works and why it can reduce risk.",
            "I can describe cryptocurrency and explain why it is considered high-risk.",
        ],
        "vocab": [
            {"word": "Mutual Funds", "definition": "A pooled investment that buys many different stocks and/or bonds at once, managed by a professional fund manager.",
             "example": "Instead of picking one company's stock, Maya could invest in a mutual fund that owns small pieces of 200 different companies.",
             "syllables": "MYOO-choo-uhl fundz", "morphology": "Latin mutuus (borrowed, reciprocal, exchanged) + 'fund,' from Latin fundus (bottom, base)."},
            {"word": "Diversification", "definition": "Spreading money across different types of investments to reduce overall risk.",
             "example": "Diversification means not putting all your money into one stock, so one company's bad year doesn't wipe out your savings.",
             "syllables": "dih-VER-suh-fih-KAY-shun", "morphology": "Latin diversus (turned in different directions): dis- (apart) + vertere (to turn) + -fication (the act of making) — 'the act of making varied.'"},
            {"word": "Crypto(currency)", "definition": "A digital currency, like Bitcoin, that is not controlled by a government or bank and can be extremely volatile in value.",
             "example": "Crypto prices can jump or crash by huge percentages in a single day, which is part of why it's considered high-risk.",
             "syllables": "KRIP-toh KUR-en-see", "morphology": "Greek kryptos (hidden, secret) + 'currency,' from Latin currere (to run) — money that 'runs' or circulates, here 'hidden' by cryptography."},
        ],
        "warm_up": "Would you rather own one single slice of pizza from one restaurant, or one small slice from ten different restaurants? What does that have to do with investing?",
        "mini_lesson": [
            {"heading": "Mutual Funds: Buying a Basket, Not One Item", "body": "A mutual fund pools money from many investors and uses it to buy a mix of stocks and/or bonds, all managed by a professional fund manager. Instead of betting on one company, you own a small piece of many companies at once. This spreads out risk, if one company in the fund does poorly, the others can balance it out. Mutual funds are a common building block in retirement accounts."},
            {"heading": "Diversification: Don't Put All Your Eggs in One Basket", "body": "Diversification means spreading your money across different types of investments, industries, or asset types so that one bad outcome doesn't sink your whole portfolio. Someone who owns only one stock is undiversified and very exposed to that one company's risk. Someone who owns a mix of stocks, bonds, and funds across different industries is more diversified and generally more protected."},
            {"heading": "Cryptocurrency: High Risk, High Attention", "body": "Cryptocurrency is a digital currency, like Bitcoin or Ethereum, that isn't issued or controlled by a government or bank. Its value is driven purely by supply, demand, and investor sentiment, which means prices can swing by huge percentages in a single day. Crypto can be part of a portfolio, but financial experts generally warn against putting a large share of your savings into something this volatile, especially money you can't afford to lose."},
        ],
        "activity": {
            "title": "Build a Portfolio",
            "instructions": "Give each student a hypothetical $1,000 to allocate across four buckets: Stocks, Bonds, Mutual Fund, and Crypto, using a simple worksheet or pie-chart handout. Students must write one sentence justifying each allocation, referencing the risk tolerance they identified in the Day 72 Risk Ladder activity. Have a few students share contrasting portfolios and discuss why two students with different risk tolerances might split the same $1,000 very differently.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "A mutual fund is best described as:",
                 "choices": ["A. A single company's stock", "B. A pooled investment that buys many stocks and/or bonds at once", "C. A type of cryptocurrency", "D. A government savings bond"], "answer": "B"},
                {"type": "multiple_choice", "q": "Diversification is a strategy for:",
                 "choices": ["A. Increasing risk to maximize reward", "B. Spreading money across investments to reduce overall risk", "C. Guaranteeing a profit", "D. Avoiding taxes"], "answer": "B"},
                {"type": "multiple_choice", "q": "Why is cryptocurrency considered high-risk compared to a mutual fund?",
                 "choices": ["A. It is illegal to own", "B. Its value can swing dramatically in short periods with less regulation", "C. It always pays a fixed dividend", "D. It cannot be sold once purchased"], "answer": "B"},
                {"type": "short_answer", "q": "Explain how owning a mutual fund is an example of diversification.", "sample_answer": "A mutual fund pools your money with other investors to buy many different stocks or bonds at once, so instead of depending on one company's performance, your risk is spread across many companies."},
            ],
        },
        "exit_ticket": {
            "prompt": "Based on today's Build a Portfolio activity, what is one change you'd make to your allocation if your risk tolerance were the opposite of what it actually is?",
        },
        "slide_bullets": [
            "Mutual fund = pooled investment across many stocks/bonds",
            "Diversification = spreading money to reduce risk",
            "Crypto = digital currency, high volatility, high risk",
            "Undiversified = one company; diversified = many companies/asset types",
            "Today's activity: Build a Portfolio ($1,000 allocation)",
            "Your portfolio choices should match your risk tolerance from Day 72",
        ],
        "application": {
            "type": "case_study",
            "title": "Jamal's All-In Bet",
            "scenario": "Jamal, a college freshman, gets a $2,000 graduation gift from his grandparents. Excited after watching videos about a cryptocurrency that had tripled in value over the past few months, he puts the entire $2,000 into that one coin in a single transaction, expecting it to keep climbing. Three weeks later, the coin drops 40% in value after a single piece of bad news spreads online, and Jamal checks his account to find it's now worth $1,200. He calls his older cousin, upset, saying he 'did everything right' because he researched the coin online for two days before buying. His cousin, who took this same financial literacy course last year, asks him one question before saying anything else: 'How much of that $2,000 did you put anywhere else?'",
            "task": "Explain what Jamal's cousin is getting at with her question, using the concept of diversification. Then describe specifically how Jamal could have structured his original $2,000 differently to reduce his risk while still investing some of it in crypto if he wanted to.",
        },
        "academic_vocab": {
            "word": "Mitigate",
            "definition": "To make a problem, risk, or negative effect less severe.",
            "syllables": "MIT-ih-gayt",
            "morphology": "Latin mitis (soft, mild) + agere (to do, act) — literally 'to make mild.'",
            "example": "Spreading your $1,000 across several investment types is one way to mitigate the risk of any single one losing value.",
        },
    },
    {
        "day": 75,
        "unit": 8,
        "lesson_in_unit": 4,
        "title": "Risk, Reward, and Liquidity: Where Should Your Money Sit?",
        "objectives": [
            "I can define liquidity and explain why it matters when choosing where to keep money.",
            "I can rank common accounts and investments from most to least liquid.",
        ],
        "vocab": [
            {"word": "Liquidity", "definition": "How quickly and easily an asset can be turned into usable cash without losing value.",
             "example": "A checking account is highly liquid because you can access that cash almost instantly, but a retirement account is not.",
             "syllables": "lih-KWID-ih-tee", "morphology": "Latin liquidus (flowing, liquid) + -ity (noun suffix) — literally 'the quality of flowing freely.'"},
        ],
        "warm_up": "If your car broke down tomorrow and you needed $400 fast, where would that money come from? Would it be easy or hard to get to?",
        "mini_lesson": [
            {"heading": "What Is Liquidity?", "body": "Liquidity describes how quickly you can turn something into cash you can actually spend, without losing value in the process. Cash in your pocket is perfectly liquid. A savings account is highly liquid. A house or a retirement account is not, selling a house takes time and paperwork, and pulling money out of a retirement account early often comes with penalties."},
            {"heading": "Why Liquidity Matters Alongside Risk and Reward", "body": "It's tempting to only think about risk and reward when choosing where to put money, but liquidity is the third piece of the puzzle. Money you might need on short notice, like an emergency fund, belongs somewhere liquid, even if it earns less interest. Money you won't touch for decades, like retirement savings, can afford to be less liquid in exchange for more growth potential."},
        ],
        "activity": {
            "title": "The Liquidity Ladder Discussion",
            "instructions": "After the reading, have students rank six items from most liquid to least liquid: cash, a checking account, a savings account, a bond, a stock, and a house. Run this as a quick think-pair-share, then reveal the generally accepted order and discuss any disagreements. Ask students to connect this back to the Risk Ladder from Day 72, noting that liquid does not always mean low-risk or vice versa.",
        },
        "reading": {
            "type": "informational",
            "title": "Risk, Reward, and Liquidity: How to Think About Where Your Money Sits",
            "body": "When people talk about investing, they usually focus on two things: risk and reward. But there's a third factor that matters just as much, especially for someone just starting out: liquidity.\n\nLiquidity is how quickly and easily you can turn an asset into cash you can actually use, without losing value in the process. Cash itself is perfectly liquid. A checking or savings account is close behind, you can withdraw funds in minutes with no penalty. Further down the liquidity spectrum are things like bonds, which usually have to be held for a set term to get the full value, and stocks, which can be sold quickly but might be worth less than you paid depending on the day. At the least liquid end sit things like real estate and retirement accounts, both of which take time, paperwork, or penalties to convert into spendable cash.\n\nHere's the part people miss: liquidity does not automatically line up with risk. A savings account is both low-risk and highly liquid. But a retirement account can be relatively low-risk over the long run while still being very illiquid in the short run, because of early withdrawal penalties. Meanwhile, a stock can be sold in seconds (fairly liquid) while still being fairly high-risk, since its price might have dropped the day you needed the cash.\n\nThis is why financial planners often talk about matching the account to the purpose. Money for next month's rent belongs somewhere liquid, even if it earns almost no interest, because you need certainty and access. Money you won't touch for 30 years, like retirement savings, can sit in something less liquid, because you're trading short-term access for long-term growth. An emergency fund exists specifically to give you a liquid cushion so you're never forced to sell a less-liquid, longer-term investment at a bad time just to cover a surprise expense.\n\nThe question isn't just 'will this grow?' It's also 'how fast could I get this money if I actually needed it?' Both questions matter.\n\n(Adapted from a Federal Reserve consumer financial education resource.)",
            "questions": [
                "In your own words, what does liquidity mean?",
                "Why might a retirement account be considered low-risk over the long run but still very illiquid in the short run?",
                "Why does the reading suggest keeping an emergency fund somewhere liquid instead of investing it in stocks?",
                "Give one example from the reading of an asset that is liquid but still risky, and explain why both things can be true at once.",
            ],
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Liquidity refers to:",
                 "choices": ["A. How much an investment pays in dividends", "B. How quickly and easily an asset can become usable cash", "C. The interest rate on a bond", "D. The total risk of a portfolio"], "answer": "B"},
                {"type": "multiple_choice", "q": "Which of these is generally the LEAST liquid?",
                 "choices": ["A. Cash", "B. A checking account", "C. A retirement account", "D. A savings account"], "answer": "C"},
                {"type": "multiple_choice", "q": "According to the reading, why should an emergency fund be kept somewhere liquid?",
                 "choices": ["A. So it earns the highest possible interest", "B. So you never have to sell a longer-term investment at a bad time to cover a surprise expense", "C. Because liquid accounts are risk-free by law", "D. Because the IRS requires it"], "answer": "B"},
                {"type": "short_answer", "q": "Explain why a stock can be considered both fairly liquid and fairly risky at the same time.", "sample_answer": "A stock can usually be sold quickly, which makes it liquid, but the price you get for it depends on the market that day, so you might have to sell at a loss if you need the cash at a bad time, which makes it risky."},
            ],
        },
        "exit_ticket": {
            "prompt": "Name one thing you own or one account you have, and explain where it would fall on the liquidity spectrum.",
        },
        "slide_bullets": [
            "Liquidity = how fast an asset becomes usable cash",
            "Cash and checking/savings accounts are highly liquid",
            "Retirement accounts and real estate are not very liquid",
            "Liquidity does not always match risk level",
            "Emergency funds should be liquid, even at lower interest",
            "Today's reading: Risk, Reward, and Liquidity",
        ],
        "application": {
            "type": "real_world_problem",
            "title": "The 2 A.M. Emergency",
            "scenario": "A recent graduate gets a call at 2 a.m.: a family member needs $1,500 sent immediately for an emergency medical copay. She has access to $1,500 spread across three places: $400 in a checking account, $600 in a retirement account she can't touch until age 59½ without a steep tax penalty, and $500 in a brokerage account holding stock she'd have to sell, which could take a day or two to actually turn into usable cash and might sell for less than she paid if the market happens to dip that day.",
            "task": "Rank her three sources of money from most liquid to least liquid, explaining your reasoning for each. Then recommend which combination of sources she should actually use tonight to get as close to $1,500 in usable cash as fast as possible, and explain any tradeoff involved.",
        },
        "academic_vocab": {
            "word": "Prioritize",
            "definition": "To decide which things matter most and put them in order of importance, doing or listing the most important first.",
            "syllables": "pry-OR-ih-tyze",
            "morphology": "Latin prior (former, first, earlier) + -itize (verb-forming suffix meaning 'to make or treat as').",
            "example": "When deciding where to keep an emergency fund, you have to prioritize quick access over a slightly higher interest rate.",
        },
    },
    {
        "day": 76,
        "unit": 8,
        "lesson_in_unit": 5,
        "title": "The Fund, Part 13: Decisions and Growth (Series Finale)",
        "objectives": [
            "I can connect the ideas of risk, reward, and growth to a real long-term life decision.",
            "I can evaluate how a decision made today can compound into different outcomes over time.",
        ],
        "vocab": [
            {"word": "Growth", "definition": "An increase in the value of money or an investment over time.",
             "example": "Maya thinks about her college choice the same way she'd think about an investment: which path has more room for growth over the next ten years?",
             "syllables": "GROHTH (one syllable)", "morphology": "Old Norse groa (to grow) + -th (noun-forming suffix, as in 'width' or 'depth')."},
        ],
        "warm_up": "Think back to Day 68's installment of The Fund, when Priya talked about her credit card scare. What's one thing you remember about how she fixed her habits?",
        "mini_lesson": [
            {"heading": "Big Decisions Are Like Investments", "body": "A college choice, a career path, even a certification program, all of these are a lot like an investment decision. You're putting in time and money now (the 'cost'), hoping for a return later (the 'reward'), and accepting some uncertainty along the way (the 'risk'). There's rarely a single right answer, only tradeoffs that fit different people's goals, timelines, and comfort with uncertainty."},
            {"heading": "Growth Takes Different Shapes", "body": "Growth doesn't always look identical. A certification program might get you into the workforce faster with a quicker paycheck, that's real, immediate reward. A four-year degree might take longer and cost more upfront, but could open doors to higher long-term growth in some fields. Neither path is automatically better; it depends on the field, the person, and what they're optimizing for."},
        ],
        "activity": {
            "title": "Graphing Two Paths",
            "instructions": "After reading today's finale, have students sketch two simple line graphs on one grid: one representing Maya's certification-program path and one representing the state-school path, with time on the x-axis and 'financial and career growth' on the y-axis, based only on reasonable guesses. There's no single correct answer, the point is the reasoning. Discuss as a class why two thoughtful people could draw these lines differently.",
        },
        "reading": {
            "type": "realistic_fiction",
            "title": "The Fund, Part 13: What Maya Decided",
            "body": "The acceptance letter and the certification program brochure had been sitting on Maya's desk for two weeks, weighted down by the same coffee mug, like she was hoping one of them would just disappear on its own.\n\n'You're going to wear a hole in that desk from staring at it,' Priya said, dropping onto the end of Maya's bed. Ever since the credit card thing back in the spring, Priya had gotten weirdly good at showing up right when Maya needed to talk something through, no lecture, just presence.\n\n'I keep making a pros and cons list and then hating both lists,' Maya said. 'The state school is four years, more debt, but Mr. Alvarez keeps saying the long-term ceiling is higher if I actually finish. The certification program is ten months, way cheaper, and I could be working, like, actually earning, before some of my friends even declare a major.'\n\n'Sounds like a risk-reward problem,' Priya said, half-smiling. 'Didn't you just do a whole unit on that?'\n\n'Don't,' Maya said, but she was smiling too.\n\nDownstairs, there was a knock, and a second later Deshawn let himself in the way he always did, holding his laptop like it owed him money. 'Okay, don't panic, but I think I actually feel ready for FAFSA season,' he said, sitting on the floor. 'Like, ready-ready. I know what a Student Aid Index is now. I know what counts as income. I made a whole folder.'\n\n'That's growth,' Maya said, and meant it two ways at once.\n\n'Growth,' Deshawn repeated, testing the word. 'Feels weird that I used to be scared of a form.'\n\nPriya looked at the two of them, then at the mug, then at Maya. 'Can I say the thing I wish someone had said to me at eighteen?'\n\n'Please,' Maya said.\n\n'There isn't a version of this where you find the guaranteed answer with zero risk. That version doesn't exist. You just gather what you actually know, be honest about what you can't know yet, and pick the path that fits who you are, not who you think you're supposed to be. I picked the four-year school. It cost me some hard lessons, some late payments, a couple of very stressful phone calls with a credit card company. But it also gave me time to figure out what I actually wanted, and I don't regret that, even the expensive parts.'\n\nMaya looked at the two pieces of paper on her desk for a long moment. Then she picked up the certification program brochure, folded it once, and set the acceptance letter on top of it, not away from it, on top of it, like a decision instead of a rejection.\n\n'I'm doing the certification program,' she said. 'Ten months. I want to be earning while Deshawn's still doing his FAFSA. And if in two years I want more school, I'll know exactly what I'm investing in next time, instead of guessing.'\n\n'That's not a small decision,' Priya said. 'That's a smart one.'\n\nDeshawn looked between them. 'So is this the part where Mr. Alvarez shows up and says something wise?'\n\nRight on cue, a text buzzed on Maya's phone. It was from Mr. Alvarez, a group message to the whole class: 'Whatever you decide after this class ends, remember the framework, not the specific numbers. Risk, reward, growth, liquidity. You'll use it for the rest of your life, not just for college.'\n\nMaya laughed and showed the screen to Priya and Deshawn. 'He always knows.'\n\n'He doesn't know,' Priya said. 'He just asks good questions at the right time. There's a difference.'\n\nMaya put the brochure in her bag. For the first time in two weeks, the desk felt lighter.",
            "questions": [
                "What decision does Maya finally make, and what reasoning does she give for it?",
                "How has Deshawn changed since earlier installments, especially regarding FAFSA and money?",
                "What does Priya mean when she says 'there isn't a version of this where you find the guaranteed answer with zero risk'? How does this connect to what you learned about risk and reward this unit?",
                "Mr. Alvarez's text mentions risk, reward, growth, and liquidity as a framework for life, not just investing. Do you agree that framework applies beyond money? Give an example.",
                "How does this final installment tie back to Day 3 (Maya's impulse purchase) or Day 68 (Priya's credit card scare)? What's changed since then?",
            ],
        },
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Growth, as used in this lesson, means:",
                 "choices": ["A. A decrease in value over time", "B. An increase in the value of money or an investment over time", "C. The interest rate on a savings account only", "D. A type of cryptocurrency"], "answer": "B"},
                {"type": "multiple_choice", "q": "In the reading, Maya ultimately decides to:",
                 "choices": ["A. Attend the state school", "B. Enroll in the certification program", "C. Take a gap year", "D. Move in with Priya"], "answer": "B"},
                {"type": "short_answer", "q": "Explain the connection between Maya's college decision and the risk-reward-liquidity concepts from this unit.", "sample_answer": "Maya weighs the certification program's faster, more certain path to income (lower risk, quicker reward) against the state school's longer, more expensive path with a potentially higher long-term ceiling (higher risk and cost, but possibly higher long-term reward), similar to comparing a bond to a stock."},
            ],
        },
        "exit_ticket": {
            "prompt": "In one sentence, explain why Mr. Alvarez says the risk-reward-growth-liquidity framework matters beyond just investing money.",
        },
        "slide_bullets": [
            "The Fund, Part 13: Series Finale",
            "Growth = increase in value of money or an investment over time",
            "Big decisions (college, career) involve risk, reward, and growth, just like investments",
            "Maya chooses the certification program; Deshawn feels ready for FAFSA season",
            "Priya's reflection: no decision is guaranteed and risk-free",
            "Framework from this unit applies far beyond money",
        ],
        "application": {
            "type": "case_study",
            "title": "Elena's Two Acceptance Letters",
            "scenario": "Elena got into a competitive four-year university that will cost about $28,000 a year after aid, and she also got accepted into a two-year medical-assistant certificate program that costs $9,000 total and could have her working, and earning, within 14 months. The four-year path could lead to a higher-paying career eventually, but it also means four more years without full-time income and a much bigger total cost. The certificate path gets her earning sooner with far less debt, but her long-term earning ceiling in that specific field is lower than some careers the four-year degree could open up. Elena has to decide within two weeks, and she keeps changing her mind depending on which relative she talked to most recently.",
            "task": "Using the risk, reward, growth, and liquidity framework from this unit, write out one specific tradeoff for each of Elena's two options. Then state which path you would recommend for her specifically, using the numbers given, and acknowledge one real downside of the option you picked.",
        },
        "academic_vocab": {
            "word": "Reconcile",
            "definition": "To bring two seemingly different or conflicting things into agreement with each other.",
            "syllables": "REK-uhn-syle",
            "morphology": "Latin re- (again) + conciliare (to bring together, unite) — literally 'to bring together again.'",
            "example": "Maya has to reconcile the faster income of a certification program with the potentially higher long-term growth of a four-year degree.",
        },
    },
    {
        "day": 77,
        "unit": 8,
        "lesson_in_unit": 6,
        "title": "Compound Interest: Time Is Your Best Asset",
        "objectives": [
            "I can explain how compound interest works.",
            "I can calculate and compare the impact of starting to invest earlier versus later.",
        ],
        "vocab": [
            {"word": "Compound Interest", "definition": "Interest calculated on both the original amount saved or invested and on the interest that has already been added to it.",
             "example": "Because of compound interest, the $500 Maya invests at 18 will earn interest on itself every single year, not just on her original deposit.",
             "syllables": "KAHM-pownd IN-trist", "morphology": "'Compound': Latin com- (together) + ponere (to put); 'interest': Latin inter- (between) + esse (to be) — literally 'to be between/to matter.'"},
        ],
        "warm_up": "Would you rather receive $1,000 today, or a penny that doubles every day for 30 days? Guess which is worth more before you do the math.",
        "mini_lesson": [
            {"heading": "Simple Interest vs. Compound Interest", "body": "Simple interest is calculated only on your original amount. Compound interest is calculated on your original amount PLUS all the interest that has already been added. That might sound like a small difference, but over many years, it isn't. Each year's interest starts earning its own interest, which is why compound growth accelerates over time instead of staying flat."},
            {"heading": "Why Starting Early Matters So Much", "body": "Because compound interest builds on itself, time is the single biggest factor in how much your money grows. Someone who invests $200 a month starting at 18 will end up with significantly more by retirement than someone who invests the same $200 a month starting at 28, even though the second person invested for fewer years, not because they picked worse investments, but because they lost a decade of compounding."},
        ],
        "activity": {
            "title": "Compound Interest Calculator Challenge",
            "instructions": "Using a compound interest calculator (paper formula sheet or online calculator, teacher's choice), have students run two scenarios side by side: investing $150 a month starting at age 18 versus starting at age 28, both stopping contributions at age 65 with the same estimated annual return. Students record the final totals for both scenarios and calculate the dollar difference. Discuss as a class why the gap is so much larger than most students expect.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Compound interest is calculated on:",
                 "choices": ["A. Only your original deposit", "B. Your original deposit plus interest already earned", "C. Only the interest from the most recent year", "D. Nothing, it's a flat fee"], "answer": "B"},
                {"type": "multiple_choice", "q": "Why does starting to invest earlier usually lead to significantly more money by retirement?",
                 "choices": ["A. Earlier investors always pick better stocks", "B. More time allows compound growth to build on itself for longer", "C. Banks offer better rates to younger investors", "D. It doesn't actually matter when you start"], "answer": "B"},
                {"type": "multiple_choice", "q": "Two people invest the same monthly amount at the same return rate, but Person A starts 10 years before Person B. What is most likely true at retirement?",
                 "choices": ["A. They'll have exactly the same amount", "B. Person B will have more because they invested more recently", "C. Person A will likely have significantly more due to extra years of compounding", "D. Neither will have any growth"], "answer": "C"},
                {"type": "short_answer", "q": "Explain in your own words why compound interest is sometimes called 'interest on interest.'", "sample_answer": "Each time interest is added to an account, that interest becomes part of the balance, so the next round of interest is calculated on a bigger number, meaning you start earning interest on the interest you already earned, not just your original deposit."},
            ],
        },
        "exit_ticket": {
            "prompt": "Based on today's calculator challenge, what is one specific number (a dollar amount or difference) that surprised you, and why?",
        },
        "slide_bullets": [
            "Compound interest = interest on your original amount PLUS interest already earned",
            "Simple interest stays flat; compound interest accelerates",
            "Time is the biggest factor in how much your money grows",
            "Starting 10 years earlier can mean tens of thousands more by retirement",
            "Today's activity: Compound Interest Calculator Challenge",
            "Small amounts invested early can outgrow larger amounts invested late",
        ],
        "application": {
            "type": "simulation",
            "title": "Ten Years, Same Monthly Amount",
            "scenario": "Two friends, Tasha and Miguel, each decide to invest $150 a month at an estimated 7% average annual return until they turn 65. Tasha starts at age 20. Miguel starts at age 30, ten years later, but otherwise invests the exact same $150 a month at the exact same 7% return. Using a compound interest calculator or the standard compound interest formula, students project the very different final balances this ten-year head start produces, even though both friends contribute the same monthly amount for the entire time each of them is investing.",
            "task": "Using a compound interest calculator (or the formula A = P(1 + r/n)^(nt) applied to monthly contributions), estimate each friend's balance at age 65. Calculate the dollar difference between Tasha's and Miguel's final balances, and explain in your own words where that extra money actually came from.",
        },
        "academic_vocab": {
            "word": "Quantify",
            "definition": "To express or measure something as a specific, exact amount or number.",
            "syllables": "KWAHN-tih-fy",
            "morphology": "Latin quantus (how much, how great) + -fy (verb suffix meaning 'to make').",
            "example": "The calculator challenge asks you to quantify exactly how many extra dollars ten years of compounding is worth.",
        },
    },
    {
        "day": 78,
        "unit": 8,
        "lesson_in_unit": 7,
        "title": "Retirement Accounts and Dividends: 401(k) vs. Roth IRA",
        "objectives": [
            "I can compare how a 401(k) and a Roth IRA are taxed and funded.",
            "I can explain what a dividend is and how it can factor into an investment choice.",
        ],
        "vocab": [
            {"word": "401(k)", "definition": "An employer-sponsored retirement account, often with pre-tax contributions and sometimes an employer match.",
             "example": "If Maya's employer offers a 401(k) match, contributing enough to get the full match is essentially free money added to her retirement savings.",
             "syllables": "FOR-oh-WUN-KAY", "morphology": "Not an acronym but a legal citation: refers to Section 401, subsection (k), of the U.S. Internal Revenue Code, which created this type of retirement plan."},
            {"word": "Roth IRA", "definition": "An individual retirement account funded with after-tax money, where qualified withdrawals in retirement are tax-free.",
             "example": "Because a Roth IRA is funded with money that's already been taxed, Deshawn won't owe taxes on it when he withdraws it in retirement.",
             "syllables": "RAHTH EYE-AR-AY", "morphology": "'Roth' is named for U.S. Senator William Roth, who sponsored the legislation; 'IRA' is an acronym: I = Individual, R = Retirement, A = Account."},
            {"word": "Dividend", "definition": "A portion of a company's profit paid out to shareholders, usually on a regular schedule.",
             "example": "Some companies pay a dividend every quarter, giving shareholders a small cash payout just for holding the stock.",
             "syllables": "DIV-ih-dend", "morphology": "Latin dividendum ('thing to be divided'), from dividere (to divide) — profit divided among shareholders."},
        ],
        "warm_up": "Would you rather pay taxes on money now, while you're young and earning less, or later, once you're older and possibly earning more? Explain your gut answer.",
        "mini_lesson": [
            {"heading": "401(k): Employer-Sponsored and Often Pre-Tax", "body": "A 401(k) is a retirement account offered through an employer. Contributions are typically taken from your paycheck before taxes, which lowers your taxable income now, but you'll pay taxes on the money when you withdraw it in retirement. Many employers offer a 'match,' meaning they add extra money to your account when you contribute, up to a certain percentage. Not taking a full employer match is often described as leaving free money on the table."},
            {"heading": "Roth IRA: Individual and After-Tax", "body": "A Roth IRA is an account you open yourself, not through an employer, and it's funded with money you've already paid taxes on. The tradeoff is that qualified withdrawals in retirement are completely tax-free, including all the growth. For young workers in a lower tax bracket now than they expect to be in later, a Roth IRA can be especially valuable, since you're paying taxes today at a lower rate instead of later at a potentially higher one."},
            {"heading": "Dividends: Getting Paid to Hold a Stock", "body": "Some companies share a portion of their profits directly with shareholders on a regular schedule, this payment is called a dividend. Not all stocks pay dividends; some companies reinvest all their profit back into growing the business instead. Investors sometimes choose dividend-paying stocks specifically because they want steady income in addition to any change in the stock's price."},
        ],
        "activity": {
            "title": "401(k) vs. Roth IRA Comparison Worksheet",
            "instructions": "Give students a side-by-side worksheet comparing a 401(k) and a Roth IRA across four categories: who offers the account, when taxes are paid, whether an employer match is possible, and how withdrawals are taxed in retirement. In pairs, have students fill it out using today's mini-lesson, then apply it to a scenario: a first job with a 3% employer 401(k) match versus opening a Roth IRA on their own, and decide which they'd prioritize first and why.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "A 401(k) is typically:",
                 "choices": ["A. Funded with after-tax money you contribute on your own", "B. Offered through an employer, often with pre-tax contributions", "C. Only available to people over 50", "D. A type of cryptocurrency wallet"], "answer": "B"},
                {"type": "multiple_choice", "q": "The main tax advantage of a Roth IRA is that:",
                 "choices": ["A. Contributions are never taxed at all, ever", "B. Qualified withdrawals in retirement are tax-free", "C. It lowers your taxable income the year you contribute", "D. Employers are required to match every dollar"], "answer": "B"},
                {"type": "multiple_choice", "q": "A dividend is:",
                 "choices": ["A. A fee charged for owning a stock", "B. A portion of a company's profit paid out to shareholders", "C. A type of retirement penalty", "D. The interest rate on a bond"], "answer": "B"},
                {"type": "short_answer", "q": "Why might a financial advisor tell someone to contribute enough to their 401(k) to get the full employer match before doing anything else?", "sample_answer": "An employer match is essentially free additional money added to your retirement savings, so not contributing enough to get the full match means giving up money the employer would have otherwise given you."},
            ],
        },
        "exit_ticket": {
            "prompt": "If your first job offered both a 401(k) with a partial employer match and the option to open a Roth IRA, which would you prioritize first, and why?",
        },
        "slide_bullets": [
            "401(k): employer-sponsored, often pre-tax, possible employer match",
            "Roth IRA: individual, after-tax now, tax-free qualified withdrawals later",
            "Employer match = free money, worth contributing enough to capture it",
            "Dividend = a portion of company profit paid to shareholders",
            "Not all stocks pay dividends; some reinvest profits instead",
            "Today's activity: 401(k) vs. Roth IRA Comparison Worksheet",
        ],
        "application": {
            "type": "real_world_problem",
            "title": "Leaving Money on the Table",
            "scenario": "A new employee earns $40,000 a year and is eligible for a 401(k) with a 4% employer match, meaning the company will match up to 4% of her salary if she contributes at least that much herself. She decides to contribute only 2% of her salary because she wants more take-home pay right now, not realizing her employer will only match what she actually puts in.",
            "task": "Calculate the dollar amount of employer match she is receiving at a 2% personal contribution, and calculate the dollar amount she could be receiving if she contributed the full 4%. Find the dollar amount of free employer match she is giving up each year by under-contributing, and explain in one sentence why financial advisors call this 'leaving money on the table.'",
        },
        "academic_vocab": {
            "word": "Contrast",
            "definition": "To compare two things in order to highlight their differences.",
            "syllables": "KAHN-trast",
            "morphology": "Latin contra (against) + stare (to stand) — literally 'to stand against,' i.e., set side by side to show difference.",
            "example": "The worksheet asks you to contrast how a 401(k) and a Roth IRA are each taxed and funded.",
        },
    },
    {
        "day": 79,
        "unit": 8,
        "lesson_in_unit": 8,
        "title": "GFL Review Day 1: Concepts & Critical Thinking + Personal Financial Priorities",
        "objectives": [
            "I can apply supply-and-demand reasoning and basic stock chart reading to sample GFL-style questions.",
            "I can identify examples of financial psychology and practice a negotiation scenario tied to personal financial priorities.",
        ],
        "vocab": [
            {"word": "Risk", "definition": "The chance that an investment could lose value or not perform the way you hoped.",
             "example": "On a stock chart, a sharp drop in price is a visible example of risk playing out.",
             "syllables": "RISK (one syllable)", "morphology": "Possibly from Italian risco/rischio or Greek rhiza (root, cliff), via early nautical use describing the hazard of sailing close to a cliff or rock."},
            {"word": "Reward", "definition": "The potential gain or payoff you could earn from an investment or financial decision.",
             "example": "Successfully negotiating a lower price while bargain shopping is a small, real-world example of reward from a financial decision.",
             "syllables": "rih-WORD", "morphology": "Old North French rewarder (to look back at, to regard): re- (again) + warder (to watch, guard)."},
        ],
        "warm_up": "The YouScience GFL exam has five domains. Today and over the next three days, we review all of them before the practice exam. Which domain do you feel most confident about right now, and which one worries you?",
        "mini_lesson": [
            {"heading": "Meet the GFL Blueprint", "body": "The YouScience General Financial Literacy exam covers five domains: Concepts & Critical Thinking (8%), Personal Financial Priorities (11%), Income & Career Preparation (15%), Saving & Investment (33%), and Personal Money Management (33%). Notice that the last two domains make up two-thirds of the exam, so while every domain matters, Saving & Investment and Personal Money Management deserve extra attention over the next few days."},
            {"heading": "Concepts & Critical Thinking (8%)", "body": "This domain covers foundational economic reasoning, especially supply and demand, and basic financial concepts like reading a stock chart. Supply and demand explains why prices rise when something is scarce or in high demand, and fall when there's a surplus or low demand. You've already practiced reading stock charts on Day 73, today's review reconnects that skill to how the exam will frame it."},
            {"heading": "Personal Financial Priorities (11%)", "body": "This domain covers financial psychology, the biases and emotional pulls that affect financial decisions (like FOMO and impulse buying from Unit 1), as well as practical skills like negotiating a better price, sometimes called bargain shopping. Setting financial priorities means being able to tell the difference between a need, a want, and an emotional impulse, and being willing to advocate for a better deal when it matters."},
        ],
        "activity": {
            "title": "Two-Station Review: Supply & Demand / Stock Charts and Bargain Shopping Negotiation",
            "instructions": "Split the class into two groups that rotate through two stations after 15 minutes each. Station 1: students complete Banzai's 'Supply, Demand, and You' practice questions alongside a quick stock chart re-read, identifying trend direction and ticker basics. Station 2: students pair up for a 'Bargain Shopping' negotiation role-play, one plays a buyer trying to negotiate a lower price on a used item, the other plays a seller, then they swap roles and debrief what worked.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "According to the basic law of supply and demand, if demand for a product increases while supply stays the same, price will typically:",
                 "choices": ["A. Decrease", "B. Increase", "C. Stay exactly the same", "D. Become impossible to determine"], "answer": "B"},
                {"type": "multiple_choice", "q": "Which GFL domain covers financial psychology and negotiation skills like bargain shopping?",
                 "choices": ["A. Concepts & Critical Thinking", "B. Personal Financial Priorities", "C. Saving & Investment", "D. Personal Money Management"], "answer": "B"},
                {"type": "multiple_choice", "q": "On a stock chart, a line trending steadily upward over several months generally indicates:",
                 "choices": ["A. The company's share price has been falling", "B. The company's share price has been rising", "C. The company no longer trades publicly", "D. The company pays no dividend"], "answer": "B"},
                {"type": "short_answer", "q": "Give one example of financial psychology (a bias or emotional pull) that could affect someone's spending decisions.", "sample_answer": "FOMO, the fear of missing out, can push someone to make an impulse purchase they didn't plan for, just because they're afraid of missing a deal or a trend."},
            ],
        },
        "exit_ticket": {
            "prompt": "Rate your confidence (1-5) on today's two domains, Concepts & Critical Thinking and Personal Financial Priorities, and name one thing you'd like to review again before the practice exam.",
        },
        "slide_bullets": [
            "GFL Blueprint: 5 domains, weighted 8% / 11% / 15% / 33% / 33%",
            "Concepts & Critical Thinking (8%): supply/demand, stock chart basics",
            "Personal Financial Priorities (11%): financial psychology, bargain shopping negotiation",
            "Station 1: Banzai Supply, Demand, and You + stock chart re-read",
            "Station 2: Bargain Shopping negotiation role-play",
            "Two days from now: Saving & Investment and Personal Money Management (the big ones)",
        ],
        "application": {
            "type": "case_study",
            "title": "The Countdown Timer",
            "scenario": "While scrolling on her phone, a student sees an ad for a jacket originally priced at $60, now marked down to $40, with a bright red countdown timer reading 'fourteen minutes left!' She wasn't planning to buy a jacket today and doesn't need one right now, but the timer and the crossed-out original price make her feel like she has to decide immediately or lose the deal forever. She adds it to her cart within thirty seconds of seeing the ad, worried that if she closes the app to think it over, the deal will disappear.",
            "task": "Identify the specific financial psychology concept (from today's GFL review) at work in this scenario, and explain exactly which details in the ad are designed to trigger it. Then suggest one specific habit she could use next time to slow down before an impulse purchase like this one.",
        },
        "academic_vocab": {
            "word": "Categorize",
            "definition": "To sort things into groups based on shared characteristics.",
            "syllables": "KAT-ih-guh-ryze",
            "morphology": "Greek kategoria (accusation, statement, category) + -ize (verb-forming suffix).",
            "example": "Part of GFL review is learning to categorize a specific exam question under the correct one of the five domains.",
        },
    },
    {
        "day": 80,
        "unit": 8,
        "lesson_in_unit": 9,
        "title": "GFL Review Day 2: Income & Career Preparation + Saving & Investment",
        "objectives": [
            "I can apply resume, interview, and paycheck-deduction knowledge to sample GFL-style questions.",
            "I can solve compound interest and 401(k)/Roth IRA comparison problems similar to what the GFL exam will ask.",
        ],
        "vocab": [
            {"word": "Compound Interest", "definition": "Interest calculated on both the original amount saved or invested and on the interest that has already been added to it.",
             "example": "A GFL-style question might ask you to compare two savers' final balances after years of compound interest at different starting ages.",
             "syllables": "KAHM-pownd IN-trist", "morphology": "'Compound': Latin com- (together) + ponere (to put); 'interest': Latin inter- (between) + esse (to be) — literally 'to be between/to matter.'"},
            {"word": "401(k)", "definition": "An employer-sponsored retirement account, often with pre-tax contributions and sometimes an employer match.",
             "example": "Expect at least one exam question comparing a 401(k) to a Roth IRA on tax treatment.",
             "syllables": "FOR-oh-WUN-KAY", "morphology": "Not an acronym but a legal citation: refers to Section 401, subsection (k), of the U.S. Internal Revenue Code, which created this type of retirement plan."},
            {"word": "Roth IRA", "definition": "An individual retirement account funded with after-tax money, where qualified withdrawals in retirement are tax-free.",
             "example": "Remember: Roth IRA contributions are after-tax, and qualified withdrawals later are tax-free.",
             "syllables": "RAHTH EYE-AR-AY", "morphology": "'Roth' is named for U.S. Senator William Roth, who sponsored the legislation; 'IRA' is an acronym: I = Individual, R = Retirement, A = Account."},
        ],
        "warm_up": "Quick recall: what's the difference between gross pay and net pay on a paycheck? You covered this back in Unit 6, so dig up what you remember.",
        "mini_lesson": [
            {"heading": "Income & Career Preparation (15%)", "body": "This domain covers the practical steps of getting and keeping a job: building a resume, preparing for interviews, and understanding your paycheck. Remember from Unit 7 and Unit 6 how to read a pay stub, gross pay minus deductions like FICA, federal tax, state tax, and sometimes retirement contributions equals your net pay, the amount that actually lands in your account."},
            {"heading": "Saving & Investment (33%): The Biggest Single Domain", "body": "This is the single largest domain on the exam, tied with Personal Money Management, so it deserves serious review time. Expect questions on how compound interest works and why starting early matters, plus questions comparing a 401(k) to a Roth IRA on how each is taxed, who offers it, and whether an employer match applies. Review Days 77 and 78 carefully; this domain draws directly from that material."},
        ],
        "activity": {
            "title": "Two-Station Review: Paycheck & Resume Practice / Compound Interest & Retirement Account Problems",
            "instructions": "Station 1: students work through a sample pay stub, calculating net pay from gross pay and listed deductions, plus reviewing one resume bullet point and rewriting it to be stronger. Station 2: students solve two compound interest word problems (comparing an early starter to a late starter) and answer three 401(k)-versus-Roth-IRA scenario questions modeled on the exam blueprint. Rotate groups halfway through the period.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which GFL domain is the largest single domain on the exam by percentage, alongside Personal Money Management?",
                 "choices": ["A. Concepts & Critical Thinking", "B. Personal Financial Priorities", "C. Income & Career Preparation", "D. Saving & Investment"], "answer": "D"},
                {"type": "multiple_choice", "q": "On a pay stub, net pay is:",
                 "choices": ["A. The same as gross pay", "B. Gross pay minus deductions like taxes and FICA", "C. Only the employer's contribution", "D. The total yearly salary"], "answer": "B"},
                {"type": "multiple_choice", "q": "A GFL-style question describes two savers investing the same monthly amount at the same rate, but one starts 10 years earlier. Who will most likely have more money at retirement?",
                 "choices": ["A. The one who started later", "B. The one who started earlier", "C. They'll have the same amount", "D. Neither will grow their money"], "answer": "B"},
                {"type": "short_answer", "q": "Summarize the key tax difference between a 401(k) and a Roth IRA in one or two sentences, as if explaining it for an exam answer.", "sample_answer": "A 401(k) is usually funded with pre-tax money and taxed when withdrawn in retirement, while a Roth IRA is funded with after-tax money and qualified withdrawals in retirement are tax-free."},
            ],
        },
        "exit_ticket": {
            "prompt": "Rate your confidence (1-5) on today's two domains, Income & Career Preparation and Saving & Investment, and name one compound interest or retirement account concept you want to re-check tonight.",
        },
        "slide_bullets": [
            "Income & Career Preparation (15%): resume, interview, paycheck deductions",
            "Saving & Investment (33%): compound interest, 401(k) vs. Roth IRA",
            "Net pay = gross pay minus taxes/FICA/other deductions",
            "Starting earlier almost always wins in compound interest problems",
            "Station 1: paycheck & resume practice; Station 2: compound interest & retirement problems",
            "Saving & Investment is one of the two heaviest-weighted domains, review it hard",
        ],
        "application": {
            "type": "real_world_problem",
            "title": "Reading the Pay Stub",
            "scenario": "A sample GFL-style pay stub shows: gross pay of $620 for the pay period, federal tax withheld of $58, state tax withheld of $19, and FICA (Social Security and Medicare combined) withheld of $47. There are no other deductions on this particular pay stub.",
            "task": "Calculate the net (take-home) pay by subtracting all three deductions from the gross pay. Then explain in one sentence, exam-answer style, why net pay is always the more accurate number to budget with instead of gross pay.",
        },
        "academic_vocab": {
            "word": "Justify",
            "definition": "To give solid reasons that show a decision or claim is correct or reasonable.",
            "syllables": "JUS-tih-fy",
            "morphology": "Latin justus (just, lawful, right) + -fy (verb suffix meaning 'to make').",
            "example": "On the exam, you may need to justify why an earlier starting age produces a larger retirement balance.",
        },
    },
    {
        "day": 81,
        "unit": 8,
        "lesson_in_unit": 10,
        "title": "GFL Review Day 3: Personal Money Management + Cumulative Synthesis",
        "objectives": [
            "I can apply budgeting and FICO credit score knowledge to sample GFL-style questions.",
            "I can connect concepts from all five GFL domains into one cumulative review.",
        ],
        "vocab": [
            {"word": "Liquidity", "definition": "How quickly and easily an asset can be turned into usable cash without losing value.",
             "example": "A strong budget keeps enough liquidity on hand so an unexpected bill doesn't turn into a credit card balance.",
             "syllables": "lih-KWID-ih-tee", "morphology": "Latin liquidus (flowing, liquid) + -ity (noun suffix) — literally 'the quality of flowing freely.'"},
            {"word": "Diversification", "definition": "Spreading money across different types of investments to reduce overall risk.",
             "example": "Good personal money management and diversification work together: a solid budget frees up money to diversify instead of carrying it all in one risky place.",
             "syllables": "dih-VER-suh-fih-KAY-shun", "morphology": "Latin diversus (turned in different directions): dis- (apart) + vertere (to turn) + -fication (the act of making) — 'the act of making varied.'"},
        ],
        "warm_up": "What are the five factors that make up a FICO credit score? Try to recall as many as you can from Unit 6 before we review.",
        "mini_lesson": [
            {"heading": "Personal Money Management (33%): The Other Biggest Domain", "body": "Tied with Saving & Investment as the largest domain, Personal Money Management covers budgeting, tracking income and expenses, and understanding credit, especially your FICO score. Expect questions on building and adjusting a budget when income or expenses change, and questions testing whether you understand what factors (payment history, amounts owed, length of credit history, new credit, credit mix) make up a FICO score."},
            {"heading": "Bringing It All Together", "body": "You've now reviewed all five GFL domains: Concepts & Critical Thinking, Personal Financial Priorities, Income & Career Preparation, Saving & Investment, and Personal Money Management. Notice how connected they actually are, a budget (Personal Money Management) only works if you understand your paycheck deductions (Income & Career Prep), and a strong credit score protects your ability to get favorable rates on any future loan (Personal Money Management, but ties to Unit 6 credit content too)."},
        ],
        "activity": {
            "title": "Advanced Budgeting Game + FICO Fundamentals Review, Then GFL Domain Wheel",
            "instructions": "Have students play the 'Advanced Budgeting' game or worksheet, adjusting a monthly budget when a surprise expense and a raise both hit in the same month, then complete a short FICO Fundamentals review quiz on what factors make up a credit score. To close, run a 'GFL Domain Wheel,' spin or draw a domain name at random and ask a rapid-fire question from that domain to different students, touching all five domains briefly before tomorrow's practice exam.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "Which of the following is NOT one of the main factors in a FICO credit score?",
                 "choices": ["A. Payment history", "B. Amounts owed", "C. Favorite bank's advertising budget", "D. Length of credit history"], "answer": "C"},
                {"type": "multiple_choice", "q": "In the Advanced Budgeting game, if a surprise expense hits in the same month as a raise, the smartest first move is usually to:",
                 "choices": ["A. Ignore the raise until next year", "B. Adjust the budget to account for both changes together", "C. Spend the entire raise immediately on something unrelated", "D. Cancel all savings contributions permanently"], "answer": "B"},
                {"type": "multiple_choice", "q": "Personal Money Management and Saving & Investment together make up what percentage of the GFL exam?",
                 "choices": ["A. 8%", "B. 15%", "C. 44%", "D. 66%"], "answer": "D"},
                {"type": "short_answer", "q": "Explain one way that good personal money management (budgeting) connects to a topic from another GFL domain, like saving and investment or income.", "sample_answer": "A solid budget that tracks income and expenses frees up extra money each month that can be directed into a 401(k) or Roth IRA, connecting Personal Money Management to Saving & Investment."},
            ],
        },
        "exit_ticket": {
            "prompt": "Of all five GFL domains, which one do you still want to review tonight before tomorrow's practice exam, and what specifically will you look at?",
        },
        "slide_bullets": [
            "Personal Money Management (33%): budgeting, FICO credit score factors",
            "FICO factors: payment history, amounts owed, credit history length, new credit, credit mix",
            "Today's activity: Advanced Budgeting game + FICO Fundamentals review",
            "GFL Domain Wheel: rapid review touching all five domains",
            "Personal Money Management + Saving & Investment = 66% of the exam",
            "Tomorrow: full practice GFL exam",
        ],
        "application": {
            "type": "simulation",
            "title": "The Same Month, Two Changes",
            "scenario": "A monthly budget currently allocates $1,800 in income against $1,750 in planned expenses, leaving $50 as a cushion. In the same month, two things happen: a $200 raise takes effect on the first paycheck, and a surprise $310 car repair bill arrives unexpectedly halfway through the month. Both changes hit the same budget in the same 30-day period, and the budget has to be rebuilt to reflect both at once rather than one at a time.",
            "task": "Recalculate this month's budget by applying both changes: add the $200 raise to income and add the $310 repair to expenses. State the new total income, new total expenses, and the new cushion (or shortfall) for the month, and explain what you'd do next if the result is negative.",
        },
        "academic_vocab": {
            "word": "Integrate",
            "definition": "To combine separate parts into a single, unified whole.",
            "syllables": "IN-tih-grayt",
            "morphology": "Latin integer (whole, untouched, complete) + -ate (verb suffix).",
            "example": "Today's Domain Wheel asks you to integrate everything from all five GFL domains instead of studying them in isolation.",
        },
    },
    {
        "day": 82,
        "unit": 8,
        "lesson_in_unit": 11,
        "title": "Practice GFL Exam Day",
        "objectives": [
            "I can apply knowledge from all five GFL domains under practice-exam conditions.",
            "I can identify my remaining weak spots and make a specific plan to address them before the real certification exam.",
        ],
        "vocab": [
            {"word": "Risk", "definition": "The chance that an investment could lose value or not perform the way you hoped.",
             "example": "A practice exam question might ask you to identify the riskiest option out of stocks, bonds, and a savings account.",
             "syllables": "RISK (one syllable)", "morphology": "Possibly from Italian risco/rischio or Greek rhiza (root, cliff), via early nautical use describing the hazard of sailing close to a cliff or rock."},
            {"word": "Reward", "definition": "The potential gain or payoff you could earn from an investment or financial decision.",
             "example": "Remember: the exam expects you to connect risk and reward as a pair, not as separate ideas.",
             "syllables": "rih-WORD", "morphology": "Old North French rewarder (to look back at, to regard): re- (again) + warder (to watch, guard)."},
            {"word": "Growth", "definition": "An increase in the value of money or an investment over time.",
             "example": "Compound interest problems on the exam are really just testing your understanding of growth over time.",
             "syllables": "GROHTH (one syllable)", "morphology": "Old Norse groa (to grow) + -th (noun-forming suffix, as in 'width' or 'depth')."},
        ],
        "warm_up": "Before we start the practice exam, write down the five GFL domains and their percentages from memory. Check yourself against the slide once you're done.",
        "mini_lesson": [
            {"heading": "How to Take the Practice Exam", "body": "Today's practice exam samples all five GFL domains: Concepts & Critical Thinking, Personal Financial Priorities, Income & Career Preparation, Saving & Investment, and Personal Money Management. Read each question fully before answering, eliminate obviously wrong choices first, and don't spend too long on any single question, you can flag and return to tough ones. This mirrors the actual structure and pacing of the real YouScience GFL certification exam."},
            {"heading": "After the Exam: What to Do With Your Results", "body": "A practice exam is only useful if you actually use the results. After we review answers together, identify which domain(s) you missed the most questions in, and make a specific plan, not just 'study more,' but something concrete, like re-reading the Day 78 retirement account notes or redoing the Day 73 stock chart activity. The goal today isn't a perfect score, it's an honest, accurate map of what to review before the real exam."},
        ],
        "activity": {
            "title": "Mini Practice GFL Exam (All 5 Domains)",
            "instructions": "Administer today's quiz as a timed, individual mini practice exam under quiet, exam-like conditions, no notes, no partner work. After students finish and turn in answers, go through each question together as a class, having students explain their reasoning for both correct and incorrect answers. Close by having each student write down one specific domain and one specific action step for their remaining review time before the actual certification exam.",
        },
        "reading": None,
        "quiz": {
            "questions": [
                {"type": "multiple_choice", "q": "(Concepts & Critical Thinking) If supply of a product drops sharply while demand stays the same, price will typically:",
                 "choices": ["A. Decrease", "B. Increase", "C. Stay exactly the same", "D. Disappear entirely"], "answer": "B"},
                {"type": "multiple_choice", "q": "(Personal Financial Priorities) Buying something you didn't plan to buy because you're afraid of missing a limited-time deal is an example of:",
                 "choices": ["A. Diversification", "B. FOMO-driven impulse buying", "C. Dollar-cost averaging", "D. A dividend"], "answer": "B"},
                {"type": "multiple_choice", "q": "(Income & Career Preparation) Net pay is calculated by:",
                 "choices": ["A. Adding bonuses to gross pay", "B. Subtracting deductions like taxes and FICA from gross pay", "C. Multiplying hourly wage by 52", "D. Ignoring all taxes"], "answer": "B"},
                {"type": "multiple_choice", "q": "(Saving & Investment) Compared to a 401(k), a Roth IRA is generally funded with:",
                 "choices": ["A. Pre-tax money through an employer only", "B. After-tax money, with tax-free qualified withdrawals later", "C. Cryptocurrency exclusively", "D. Money that can never be withdrawn"], "answer": "B"},
                {"type": "multiple_choice", "q": "(Personal Money Management) Which of these is one of the main factors used to calculate a FICO credit score?",
                 "choices": ["A. Favorite color", "B. Payment history", "C. Number of siblings", "D. Zip code alone"], "answer": "B"},
                {"type": "short_answer", "q": "(Saving & Investment / Cumulative) Explain why an 18-year-old who starts investing a modest amount monthly will likely outperform a 28-year-old who invests a larger amount monthly, assuming similar rates of return.", "sample_answer": "Because of compound interest, the extra ten years of growth for the 18-year-old allow their contributions and earned interest to compound for far longer, often outweighing the larger monthly amount the 28-year-old contributes over a shorter time span."},
            ],
        },
        "exit_ticket": {
            "prompt": "Name the one GFL domain you'll spend tonight reviewing, and one specific thing (an activity, a set of notes, a worksheet) you'll revisit to prepare.",
        },
        "slide_bullets": [
            "Today: Mini Practice GFL Exam, all 5 domains sampled",
            "Concepts & Critical Thinking (8%) / Personal Financial Priorities (11%)",
            "Income & Career Preparation (15%) / Saving & Investment (33%) / Personal Money Management (33%)",
            "Read fully, eliminate wrong answers, flag and return to tough questions",
            "After the exam: identify your weakest domain and make a specific review plan",
            "This is your final rehearsal before the real YouScience GFL certification exam",
        ],
        "application": {
            "type": "case_study",
            "title": "Grading Your Own Practice Exam",
            "scenario": "After finishing the mini practice GFL exam, a student named Wren reviews which questions she missed: she got the Concepts & Critical Thinking question wrong (supply and demand), got both Personal Financial Priorities questions right, missed one of two Saving & Investment questions (mixed up which retirement account is funded with after-tax money), and missed the one Personal Money Management question about FICO score factors. She has one evening before the real certification exam and can't review everything equally.",
            "task": "Using the GFL domain weights from this unit (8%, 11%, 15%, 33%, 33%), decide which one or two domains Wren should prioritize studying tonight given both her missed questions and each domain's weight on the real exam. Justify your recommendation in three to four sentences.",
        },
        "academic_vocab": {
            "word": "Evaluate",
            "definition": "To carefully judge the value, accuracy, or quality of something.",
            "syllables": "ee-VAL-yoo-ayt",
            "morphology": "Latin e- (out) + valere (to be strong, be worth) + -ate — literally 'to draw out the worth of' something.",
            "example": "After the practice exam, you'll evaluate your own results to find which GFL domain needs the most review tonight.",
        },
    },
]
