"""
Teenager 101 — Curated YouTube video links per lesson.
Each entry has: title, channel, duration, watch_for (what to notice),
url (YouTube search URL — always resolves even if a video ID changes),
alt_title, alt_channel, alt_url (backup video).
"""

YOUTUBE = {
    # ── Unit 1: Basic Life Skills ──────────────────────────────────────────
    "1.1": {
        "title": "How to Do Laundry",
        "channel": "Good Housekeeping",
        "duration": "5 min",
        "watch_for": "Pay attention to how they sort clothes by color and fabric type — what happens if you skip that step?",
        "url": "https://www.youtube.com/results?search_query=how+to+do+laundry+step+by+step+beginners",
        "alt_title": "Laundry Care Label Symbols Explained",
        "alt_channel": "Clean My Space",
        "alt_url": "https://www.youtube.com/results?search_query=laundry+care+label+symbols+explained",
    },
    "1.2": {
        "title": "How to Sew on a Button",
        "channel": "Made to Sew",
        "duration": "4 min",
        "watch_for": "Notice the knotting technique at the start and end — this is what keeps the button from falling off again.",
        "url": "https://www.youtube.com/results?search_query=how+to+sew+on+a+button+tutorial+beginners",
        # This lesson covers TWO distinct skills (sewing a button + patching a hole with a
        # running stitch). The primary video only covers buttons, so alt is a REQUIRED second
        # clip, not a fallback — see alt_watch_for and build_slides.py's video_slide().
        "alt_title": "How to Fix Holes in Clothes with Needle and Thread",
        "alt_channel": "Twonu",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+patch+a+hole+in+fabric+running+stitch+tutorial",
        "alt_watch_for": "Notice the simple in-and-out running stitch they use to close the hole — that's the same stitch from today's vocabulary, just used for a patch instead of a button.",
    },
    "1.3": {
        "title": "How to Wash Dishes Properly",
        "channel": "Clean My Space",
        "duration": "5 min",
        "watch_for": "Watch for the order they wash dishes in — there's a reason certain items go first, and it has to do with food safety.",
        "url": "https://www.youtube.com/results?search_query=how+to+wash+dishes+properly+food+safety",
        "alt_title": "Kitchen Cleaning Tips for Teens",
        "alt_channel": "Melissa Maker",
        "alt_url": "https://www.youtube.com/results?search_query=kitchen+cleaning+tips+for+teens+beginners",
    },
    "1.4": {
        "title": "How to Organize Your Room — Minimalist Method",
        "channel": "Matt D'Avella",
        "duration": "7 min",
        "watch_for": "Think about which items in your own room you actually use every week — and which ones are just taking up space.",
        "url": "https://www.youtube.com/results?search_query=how+to+organize+your+room+minimalism+teens",
        "alt_title": "Marie Kondo Method for Teens",
        "alt_channel": "KonMari",
        "alt_url": "https://www.youtube.com/results?search_query=marie+kondo+method+for+teens+tidying+up",
    },

    # ── Unit 2: Gardening ──────────────────────────────────────────────────
    "2.1": {
        "title": "How to Plan a Vegetable Garden for Beginners",
        "channel": "Gardener Scott",
        "duration": "8 min",
        "watch_for": "Notice how sun exposure and spacing affect which vegetables can grow near each other — planning saves a lot of wasted effort.",
        "url": "https://www.youtube.com/results?search_query=how+to+plan+a+vegetable+garden+for+beginners",
        "alt_title": "Square Foot Gardening Method Explained",
        "alt_channel": "MIgardener",
        "alt_url": "https://www.youtube.com/results?search_query=square+foot+gardening+method+beginners+explained",
    },
    "2.2": {
        "title": "Understanding Garden Soil for Beginners",
        "channel": "GardenAnswer",
        "duration": "6 min",
        "watch_for": "Pay attention to what makes soil 'healthy' — it's not just dirt, it's a living ecosystem with billions of organisms.",
        "url": "https://www.youtube.com/results?search_query=understanding+garden+soil+beginners+extension",
        "alt_title": "Soil pH Explained for Gardeners",
        "alt_channel": "Epic Gardening",
        "alt_url": "https://www.youtube.com/results?search_query=soil+pH+explained+for+gardeners+beginners",
    },
    "2.3": {
        "title": "How to Start a Compost Bin for Beginners",
        "channel": "Epic Gardening",
        "duration": "7 min",
        "watch_for": "Watch for the 'greens vs. browns' ratio — getting that balance right is the secret to compost that actually works.",
        "url": "https://www.youtube.com/results?search_query=how+to+start+a+compost+bin+beginners",
        "alt_title": "Hot Composting vs Cold Composting",
        "alt_channel": "Roots and Refuge Farm",
        "alt_url": "https://www.youtube.com/results?search_query=hot+composting+vs+cold+composting+explained",
    },
    "2.4": {
        "title": "How to Plant Seeds Indoors — Step by Step",
        "channel": "MIgardener",
        "duration": "6 min",
        "watch_for": "Notice the depth and spacing rules for seeds — planting too deep or too shallow are the most common beginner mistakes.",
        "url": "https://www.youtube.com/results?search_query=how+to+plant+seeds+indoors+step+by+step+beginners",
        "alt_title": "Transplanting Seedlings Guide",
        "alt_channel": "Gardener Scott",
        "alt_url": "https://www.youtube.com/results?search_query=transplanting+seedlings+guide+beginners+garden",
    },
    "2.5": {
        "title": "Identifying Common Garden Pests — Organic Solutions",
        "channel": "Roots and Refuge Farm",
        "duration": "8 min",
        "watch_for": "Look at how they ID each pest by the damage it leaves — you often find the clue before you find the bug.",
        "url": "https://www.youtube.com/results?search_query=identifying+common+garden+pests+organic+solutions",
        "alt_title": "Companion Planting Guide to Repel Pests",
        "alt_channel": "Epic Gardening",
        "alt_url": "https://www.youtube.com/results?search_query=companion+planting+guide+repel+pests+beginners",
    },
    "2.6": {
        "title": "How to Water Your Garden Correctly — Deep Watering",
        "channel": "Gardening Know How",
        "duration": "5 min",
        "watch_for": "Pay attention to why shallow, frequent watering is actually worse for plants than deep, infrequent watering.",
        "url": "https://www.youtube.com/results?search_query=how+to+water+your+garden+correctly+deep+watering",
        "alt_title": "DIY Drip Irrigation for Beginners",
        "alt_channel": "MIgardener",
        "alt_url": "https://www.youtube.com/results?search_query=diy+drip+irrigation+for+beginners+garden",
    },
    "2.7": {
        "title": "When and How to Harvest Vegetables",
        "channel": "Gardening Know How",
        "duration": "6 min",
        "watch_for": "Notice the visual and texture cues for each vegetable — harvesting too early or too late changes the taste completely.",
        "url": "https://www.youtube.com/results?search_query=when+and+how+to+harvest+vegetables+garden+guide",
        "alt_title": "Vegetable Harvest Guide for Beginners",
        "alt_channel": "Epic Gardening",
        "alt_url": "https://www.youtube.com/results?search_query=vegetable+harvest+guide+beginners+when+to+pick",
    },
    "2.8": {
        "title": "How to Build a Raised Garden Bed — DIY",
        "channel": "This Old House",
        "duration": "8 min",
        "watch_for": "Watch the material choices they make and why — not all wood is safe for growing food, and the height matters more than you'd think.",
        "url": "https://www.youtube.com/results?search_query=how+to+build+a+raised+garden+bed+DIY+beginners",
        "alt_title": "Raised Bed Gardening for Beginners",
        "alt_channel": "Gardener Scott",
        "alt_url": "https://www.youtube.com/results?search_query=raised+bed+gardening+for+beginners+guide",
    },

    # ── Unit 3: Finance & Time ─────────────────────────────────────────────
    "3.1": {
        "title": "How Advertising Manipulates You",
        "channel": "Nerdwriter1",
        "duration": "7 min",
        "watch_for": "Try to spot every psychological trick they name — then think about the last ad that actually made you want something.",
        "url": "https://www.youtube.com/results?search_query=how+advertising+manipulates+you+marketing+tricks+explained",
        "alt_title": "How Social Media Ads Target Teens",
        "alt_channel": "Vox",
        "alt_url": "https://www.youtube.com/results?search_query=how+social+media+ads+target+teenagers+explained",
    },
    "3.2": {
        "title": "Needs vs Wants — Personal Finance for Teens",
        "channel": "Practical Personal Finance",
        "duration": "5 min",
        "watch_for": "Think about something you recently bought — was it a need or a want, and does it actually matter which one it was?",
        "url": "https://www.youtube.com/results?search_query=needs+vs+wants+personal+finance+for+teens",
        "alt_title": "Maslow's Hierarchy of Needs Explained Simply",
        "alt_channel": "Sprouts",
        "alt_url": "https://www.youtube.com/results?search_query=maslow+hierarchy+of+needs+explained+simply+animation",
    },
    "3.3": {
        "title": "50/30/20 Budget Rule Explained for Beginners",
        "channel": "Graham Stephan",
        "duration": "6 min",
        "watch_for": "Notice which category (needs, wants, savings) most people overspend in — and think about where your money would go right now.",
        "url": "https://www.youtube.com/results?search_query=50+30+20+budget+rule+explained+beginners",
        "alt_title": "How to Budget Your Money as a Teenager",
        "alt_channel": "Andrei Jikh",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+budget+your+money+teenagers+beginners",
    },
    "3.4": {
        "title": "Compound Interest Explained Simply",
        "channel": "TED-Ed",
        "duration": "5 min",
        "watch_for": "Pay attention to the charts showing money over time — the difference between starting at 15 vs. 25 is shocking.",
        "url": "https://www.youtube.com/results?search_query=compound+interest+explained+simply+animation+teens",
        "alt_title": "Why You Should Start Saving Young",
        "alt_channel": "Two Cents",
        "alt_url": "https://www.youtube.com/results?search_query=why+you+should+start+saving+money+young+compound+interest",
    },
    "3.5": {
        "title": "Time Management for Students — Eisenhower Matrix",
        "channel": "Thomas Frank",
        "duration": "7 min",
        "watch_for": "Watch how the Eisenhower Matrix sorts tasks into four boxes — think about what quadrant most of your daily activities fall into.",
        "url": "https://www.youtube.com/results?search_query=time+management+for+students+eisenhower+matrix",
        "alt_title": "How to Stop Procrastinating — Teen Edition",
        "alt_channel": "Mike and Matty",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+stop+procrastinating+for+teens+students",
    },
    "3.6": {
        "title": "How to Write a Resume With No Experience — Teens",
        "channel": "Career Sidekick",
        "duration": "6 min",
        "watch_for": "Notice how they turn everyday activities (clubs, chores, volunteering) into resume bullet points — you probably have more to list than you think.",
        "url": "https://www.youtube.com/results?search_query=how+to+write+a+resume+with+no+experience+teens",
        "alt_title": "Resume Tips for First Job High School",
        "alt_channel": "Self Made Millennial",
        "alt_url": "https://www.youtube.com/results?search_query=resume+tips+for+first+job+high+school+students",
    },
    "3.7": {
        "title": "How to Find a Job as a Teenager — First Job Tips",
        "channel": "Natalie Bacon",
        "duration": "6 min",
        "watch_for": "Watch for how they recommend approaching businesses in person versus applying online — one method has a much higher success rate.",
        "url": "https://www.youtube.com/results?search_query=how+to+find+a+job+as+a+teenager+first+job+tips",
        "alt_title": "Teen Job Hunting Mistakes to Avoid",
        "alt_channel": "CareerVidz",
        "alt_url": "https://www.youtube.com/results?search_query=teen+job+hunting+mistakes+to+avoid+first+job",
    },
    "3.8": {
        "title": "Job Interview Tips for Teenagers — First Interview",
        "channel": "Don Georgevich",
        "duration": "7 min",
        "watch_for": "Pay attention to body language and the way they recommend answering 'Tell me about yourself' — first impressions happen in the first 30 seconds.",
        "url": "https://www.youtube.com/results?search_query=job+interview+tips+for+teenagers+first+interview",
        "alt_title": "Common Interview Questions and Answers for Teens",
        "alt_channel": "Self Made Millennial",
        "alt_url": "https://www.youtube.com/results?search_query=common+interview+questions+and+answers+for+teens+high+school",
    },

    # ── Unit 4: Home Repair ────────────────────────────────────────────────
    "4.1": {
        "title": "Essential Tools Every Homeowner Needs — Beginner Guide",
        "channel": "This Old House",
        "duration": "6 min",
        "watch_for": "Notice which 5-10 tools they say you need before anything else — these are the ones worth learning to use first.",
        "url": "https://www.youtube.com/results?search_query=essential+tools+every+homeowner+needs+beginner+guide",
        "alt_title": "Basic Tool Identification Guide for Beginners",
        "alt_channel": "Home Repair Tutor",
        "alt_url": "https://www.youtube.com/results?search_query=basic+tool+identification+guide+beginners+home+repair",
    },
    "4.2": {
        "title": "How to Patch a Hole in Drywall — Beginner",
        "channel": "Home Repair Tutor",
        "duration": "7 min",
        "watch_for": "Watch the sanding and feathering steps — skipping those is exactly why patches stay visible after painting.",
        "url": "https://www.youtube.com/results?search_query=how+to+patch+a+hole+in+drywall+beginner",
        "alt_title": "How to Paint a Room Step by Step",
        "alt_channel": "This Old House",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+paint+a+room+step+by+step+beginners",
    },
    "4.3": {
        "title": "How to Unclog a Drain Without Chemicals",
        "channel": "Skill Builder",
        "duration": "5 min",
        "watch_for": "Notice how most clogs are actually within the first few inches of the drain — you often don't need any special tools at all.",
        "url": "https://www.youtube.com/results?search_query=how+to+unclog+a+drain+without+chemicals",
        "alt_title": "How to Fix a Running Toilet Simply",
        "alt_channel": "Home Repair Tutor",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+fix+a+running+toilet+simple+beginners",
    },
    "4.4": {
        "title": "How to Replace an Electrical Outlet Safely — Beginner",
        "channel": "The Spruce",
        "duration": "7 min",
        "watch_for": "Pay close attention to the safety steps before touching anything — electricity is forgiving until it suddenly isn't.",
        "url": "https://www.youtube.com/results?search_query=how+to+replace+an+outlet+safely+beginner+electrical",
        "alt_title": "How to Reset a Circuit Breaker at Home",
        "alt_channel": "This Old House",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+reset+a+circuit+breaker+home+beginners",
    },
    "4.5": {
        "title": "How to Fix a Flat Bike Tire — Step by Step",
        "channel": "Global Cycling Network",
        "duration": "6 min",
        "watch_for": "Watch how they find the exact puncture spot using water — it's a simple trick that saves a lot of guessing.",
        "url": "https://www.youtube.com/results?search_query=how+to+fix+a+flat+bike+tire+step+by+step",
        "alt_title": "Basic Bike Maintenance for Beginners",
        "alt_channel": "Park Tool",
        "alt_url": "https://www.youtube.com/results?search_query=basic+bike+maintenance+for+beginners+tutorial",
    },

    # ── Unit 5: Babysitting ────────────────────────────────────────────────
    "5.1": {
        "title": "How to Start a Babysitting Business — Teen Entrepreneur",
        "channel": "Young Entrepreneurs Forum",
        "duration": "6 min",
        "watch_for": "Notice how they recommend setting your rate — think about what value you're offering and how to communicate that to parents.",
        "url": "https://www.youtube.com/results?search_query=how+to+start+a+babysitting+business+teen+entrepreneur",
        "alt_title": "Babysitting Rates and Tips for Teens",
        "alt_channel": "Babysitting Business Academy",
        "alt_url": "https://www.youtube.com/results?search_query=babysitting+rates+and+tips+for+teens+how+much+to+charge",
    },
    "5.2": {
        "title": "Babysitting Safety Tips — Red Cross Guide",
        "channel": "American Red Cross",
        "duration": "5 min",
        "watch_for": "Pay attention to the list of information you should always get from parents before they leave — a missing detail could cost you in an emergency.",
        "url": "https://www.youtube.com/results?search_query=babysitting+safety+tips+red+cross+guide",
        "alt_title": "Babysitter Safety Checklist Walkthrough",
        "alt_channel": "Babysitting Business Academy",
        "alt_url": "https://www.youtube.com/results?search_query=babysitter+safety+checklist+walkthrough+teens",
    },
    "5.3": {
        "title": "What to Do in a Babysitting Emergency",
        "channel": "Babysitting Business Academy",
        "duration": "6 min",
        "watch_for": "Watch how they prioritize: your job is to stay calm first, then act — panic is the biggest obstacle in any real emergency.",
        "url": "https://www.youtube.com/results?search_query=what+to+do+in+a+babysitting+emergency+guide",
        "alt_title": "How to Handle Babysitting Emergencies — Teen Guide",
        "alt_channel": "American Red Cross",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+handle+babysitting+emergencies+teens",
    },
    "5.4": {
        "title": "Child Development Ages 0 to 5 — Milestones",
        "channel": "Sprouts",
        "duration": "7 min",
        "watch_for": "Notice the huge leap in language and social skills between ages 2 and 4 — it explains why toddlers act the way they do.",
        "url": "https://www.youtube.com/results?search_query=child+development+ages+0+to+5+milestones+explained",
        "alt_title": "How Toddlers Learn Through Play",
        "alt_channel": "Zero to Three",
        "alt_url": "https://www.youtube.com/results?search_query=how+toddlers+learn+through+play+child+development",
    },
    "5.5": {
        "title": "Middle Childhood Development Ages 6 to 10 — Psychology",
        "channel": "Sprouts",
        "duration": "6 min",
        "watch_for": "Watch for how peer relationships start to matter more than adult approval around age 7 — this changes how you should interact with kids in this range.",
        "url": "https://www.youtube.com/results?search_query=middle+childhood+development+6+to+10+psychology+explained",
        "alt_title": "Understanding School-Age Children Behavior",
        "alt_channel": "Child Mind Institute",
        "alt_url": "https://www.youtube.com/results?search_query=understanding+school+age+children+behavior+psychology",
    },
    "5.6": {
        "title": "Bedtime Routine Tips for Babysitters",
        "channel": "Babysitting Business Academy",
        "duration": "5 min",
        "watch_for": "Pay attention to how consistency in routine actually helps kids feel safe — the routine itself is the signal that everything is okay.",
        "url": "https://www.youtube.com/results?search_query=bedtime+routine+tips+for+babysitters",
        "alt_title": "Dealing With Picky Eaters as a Babysitter",
        "alt_channel": "Super Simple",
        "alt_url": "https://www.youtube.com/results?search_query=dealing+with+picky+eaters+as+a+babysitter+tips",
    },
    "5.7": {
        "title": "First Aid Basics Every Teen Should Know",
        "channel": "American Red Cross",
        "duration": "7 min",
        "watch_for": "Focus on the steps for treating cuts and burns — the order of the steps matters more than people realize, and doing them wrong can make things worse.",
        "url": "https://www.youtube.com/results?search_query=first+aid+basics+every+teen+should+know+red+cross",
        "alt_title": "How to Treat Cuts and Burns at Home",
        "alt_channel": "Howcast",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+treat+cuts+and+burns+at+home+first+aid",
    },
    "5.8": {
        "title": "Hands-Only CPR Tutorial",
        "channel": "American Heart Association",
        "duration": "3 min",
        "watch_for": "Count along with the compression rhythm — the beat of 'Stayin' Alive' by the Bee Gees is literally the right speed, and that's worth remembering.",
        "url": "https://www.youtube.com/results?search_query=hands+only+CPR+tutorial+American+Heart+Association",
        "alt_title": "How to Do CPR Step by Step — Bystander Guide",
        "alt_channel": "St John Ambulance",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+do+CPR+step+by+step+bystander+guide",
    },

    # ── Unit 6: Food Prep ──────────────────────────────────────────────────
    "6.1": {
        "title": "Food Safety Temperature Danger Zone Explained",
        "channel": "StateFoodSafety",
        "duration": "4 min",
        "watch_for": "Pay attention to the specific temperature range of the danger zone — this is the range where bacteria double every 20 minutes.",
        "url": "https://www.youtube.com/results?search_query=food+safety+temperature+danger+zone+explained",
        # This lesson covers TWO distinct concepts (temperature danger zone/2-hour rule +
        # cross-contamination). The primary video is temperature-only, so alt is a REQUIRED
        # second clip, not a fallback — see alt_watch_for and build_slides.py's video_slide().
        "alt_title": "How Does Cross-Contamination Happen?",
        "alt_channel": "USDA Food Safety",
        "alt_url": "https://www.youtube.com/results?search_query=cross+contamination+food+safety+kitchen+explained",
        "alt_watch_for": "Watch for how germs move from raw meat to other food WITHOUT any direct contact — through hands, cutting boards, or countertops. That's the part of food safety that has nothing to do with temperature.",
    },
    "6.2": {
        "title": "Basic Knife Skills for Beginners",
        "channel": "Gordon Ramsay",
        "duration": "6 min",
        "watch_for": "Watch the 'claw grip' technique for holding food — it looks awkward at first but it's the one thing that actually prevents cuts.",
        "url": "https://www.youtube.com/results?search_query=basic+knife+skills+for+beginners+chef+tutorial",
        "alt_title": "Knife Safety for Teens Cooking Class",
        "alt_channel": "America's Test Kitchen",
        "alt_url": "https://www.youtube.com/results?search_query=knife+safety+for+teens+cooking+class+beginners",
    },
    "6.3": {
        "title": "Basic Cooking Terms and Techniques Explained",
        "channel": "Ethan Chlebowski",
        "duration": "7 min",
        "watch_for": "Notice how many of these terms are about heat control — most beginner cooking mistakes come down to the wrong temperature, not the wrong ingredient.",
        "url": "https://www.youtube.com/results?search_query=basic+cooking+terms+and+techniques+explained+beginners",
        "alt_title": "How to Read a Recipe for Beginners",
        "alt_channel": "America's Test Kitchen",
        "alt_url": "https://www.youtube.com/results?search_query=how+to+read+a+recipe+for+beginners+cooking",
    },
    "6.4": {
        "title": "Air Fryer Basics for Beginners — How It Works",
        "channel": "Tasty",
        "duration": "5 min",
        "watch_for": "Watch how they explain air circulation — understanding why you shouldn't overcrowd the basket will save you from soggy fries every time.",
        "url": "https://www.youtube.com/results?search_query=air+fryer+basics+for+beginners+how+it+works",
        "alt_title": "Best Things to Cook in an Air Fryer for Beginners",
        "alt_channel": "The Stay At Home Chef",
        "alt_url": "https://www.youtube.com/results?search_query=best+things+to+cook+in+an+air+fryer+beginners",
    },
    "6.5": {
        "title": "Instant Pot for Beginners — Getting Started Guide",
        "channel": "Amy + Jacky",
        "duration": "8 min",
        "watch_for": "Pay close attention to the sealing valve — it's the most common mistake beginners make, and it can ruin a whole meal.",
        "url": "https://www.youtube.com/results?search_query=instant+pot+for+beginners+getting+started+guide",
        "alt_title": "Pressure Cooker Basics and Safety Tips",
        "alt_channel": "Serious Eats",
        "alt_url": "https://www.youtube.com/results?search_query=pressure+cooker+basics+safety+tips+beginners",
    },
    "6.6": {
        "title": "How to Use a Toaster Oven — Convection Cooking",
        "channel": "America's Test Kitchen",
        "duration": "5 min",
        "watch_for": "Notice how convection (the fan) affects cooking time compared to a regular oven — recipes often need to be adjusted when you switch between them.",
        "url": "https://www.youtube.com/results?search_query=how+to+use+a+toaster+oven+convection+cooking+beginners",
        "alt_title": "Countertop Oven Cooking Tips for Beginners",
        "alt_channel": "Tasty",
        "alt_url": "https://www.youtube.com/results?search_query=countertop+oven+cooking+tips+beginners",
    },
    "6.7": {
        "title": "Easy No-Bake Snacks for Beginners — Teens Cooking",
        "channel": "Preppy Kitchen",
        "duration": "6 min",
        "watch_for": "Watch how they modify recipes by swapping ingredients — once you understand why each ingredient is there, you can make it your own.",
        "url": "https://www.youtube.com/results?search_query=easy+no+bake+snacks+for+beginners+teens+cooking",
        "alt_title": "Healthy No-Bake Energy Balls Recipe Tutorial",
        "alt_channel": "Minimalist Baker",
        "alt_url": "https://www.youtube.com/results?search_query=healthy+no+bake+energy+balls+recipe+tutorial+beginners",
    },
}
